<html>
<head>
    <title> 신비의 물성 </title>
    <link rel="stylesheet" type="text/css" href="/public_html/reset_style.css" />
    <script type="text/javascript">
        var tmpUser = navigator.userAgent;

        if (tmpUser.indexOf("iPhone") > 0 || tmpUser.indexOf("iPad") > 0 || tmpUser.indexOf("Android ") > 0 )
        {
            document.location ="http://www.hassed.kr/mystery_m.html";
        }
        else
        {

        }
    </script>
</head>

<body>
<video loop id="video" width="360" height="720" class="video-js vjs-default-skin" autoplay preload="auto" poster="/public_html/images/mystery.jpg">
    <source src="/public_html/movie/mystery.mp4" type="video/mp4" />
    <video>
</body>
</html>
