<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/img_e/img_b2b.jpg" border="0" alt="">
    </div>
    <div id="" class="box_outline_b" style="padding:76px 50px;">
        <div id="" class="box_b2btitle">
            <img src="/public_html/img_e/title_privacy.png" border="0" alt="">
        </div>
        <div id="" class="" style="margin-top:50px; overflow:hidden; color:#666;">
            <div id="" class="fl_left txt_just" style="width:468px;">
                <span class="" style="font-weight:bold;">1. Privacy</span>
                <br>
                .HASSED is committed to protecting customer’s privacy.<br><br>

                We provide you with information about how you use your personal information and give you the choice of how to use such data. We therefore recommend that you read this Privacy Policy (the "Policy").<br><br>

                This policy applies to Korean consumers who access www.hassed.kr and move their cursor to "Korean" for access.<br><br>

                This policy applies only to the information we collect through the .HASSED site. It does not apply to customers outside of Korea, and Korean law applies to collecting personal information through the .HASSED site.<br><br><br>


                <span class="" style="font-weight:bold;">2. Collection and Use of Information</span>
                <br>
                Users can browse and view our website anonymously, but users voluntarily register or subscribe to .HASSED, contact us through the .HASSED site, or voluntarily provide personal information for purchase on the .HASSED site. If so, we collect personally identifiable personal information ("personal information") of .HASSED site users.<br><br>

                .HASSED site users may provide personal information for various reasons such as collecting newsletter, product information, event information, service, response to questionnaire survey, contest participation and other promotion event notice and also for the purpose of purchase, such as shipping and delivery, payment and invoice, complaint, purchase purpose and user registration management.
            </div>
            <div id="" class="fl_right txt_just" style="width:468px;">
                <br><br>The types of personal information we may collect include your name, address, phone number, email address, and purchase information such as credit or debit card information used to facilitate payment for purchases of .HASSED products. We may also use the information you provide to create your personal customer profile for the purpose of providing information about products or events you may be interested in and simplifying purchases in future purchases. We may combine personal information collected on the .HASSED site with other information about our users that we collect offline, for other purposes such as internal research or to provide better customized services for marketing or website content.<br><br><br>

                <span class="" style="font-weight:bold;">3. Department Contact Information</span>
                <br>
                If you have any question or comment about this policy or wish to update your information about us, please contact us at: <br>.HASSED CUSROMER CARE CENTER: 82-2-401-5073
                <br><br><br><br><br><br><br><br><br>
                <span class="" style="text-align:right;">Last updated on: December 2015<br>
ⓒ HASSED, 2015 All rights are reserved by .HASSED.
</span>

            </div>
        </div>
    </div>
</div>