
<div id="tx_trex_container" class="tx-editor-container">
    <div id="tx_sidebar" class="tx-sidebar">
        <div class="tx-sidebar-boundary">
            <ul class="tx-bar tx-bar-left tx-nav-attach">
                <li class="tx-list">
                    <div unselectable="on" id="tx_image" class="tx-image tx-btn-trans">
                        <a href="javascript:;" title="사진" class="tx-text">사진</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>

    <div id="tx_toolbar_basic" class="tx-toolbar tx-toolbar-basic">
        <div class="tx-toolbar-boundary">
            <ul class="tx-bar tx-bar-left">
                <li class="tx-list">
                    <div unselectable="on" class="tx-slt-100bg tx-fontsize" id="tx_fontsize">
                        <a href="javascript:;" title="글자크기">9pt</a>
                    </div>
                    <div id="tx_fontsize_menu" class="tx-fontsize-menu tx-menu" unselectable="on"></div>
                </li>
            </ul>
            <ul class="tx-bar tx-bar-left tx-group-font">

                <li class="tx-list">
                    <div unselectable="on" class="tx-btn-lbg tx-bold" id="tx_bold">
                        <a href="javascript:;" class="tx-icon" title="굵게 (Ctrl+B)">굵게</a>
                    </div>
                </li>
                <li class="tx-list">
                    <div unselectable="on" class="tx-btn-bg tx-underline" id="tx_underline">
                        <a href="javascript:;" class="tx-icon" title="밑줄 (Ctrl+U)">밑줄</a>
                    </div>
                </li>
                <li class="tx-list">
                    <div unselectable="on" class="tx-btn-bg tx-italic" id="tx_italic">
                        <a href="javascript:;" class="tx-icon" title="기울임 (Ctrl+I)">기울임</a>
                    </div>
                </li>
                <li class="tx-list">
                    <div unselectable="on" class="tx-btn-bg tx-strike" id="tx_strike">
                        <a href="javascript:;" class="tx-icon" title="취소선 (Ctrl+D)">취소선</a>
                    </div>
                </li>
                <li class="tx-list">
                    <div unselectable="on" class="tx-slt-tbg tx-forecolor" id="tx_forecolor">
                        <a href="javascript:;" class="tx-icon" title="글자색">글자색</a>
                        <a href="javascript:;" class="tx-arrow" title="글자색 선택">글자색 선택</a>
                    </div>
                    <div id="tx_forecolor_menu" class="tx-menu tx-forecolor-menu tx-colorpallete" unselectable="on"></div>
                </li>
                <li class="tx-list">
                    <div unselectable="on" class="tx-slt-brbg tx-backcolor" id="tx_backcolor">
                        <a href="javascript:;" class="tx-icon" title="글자 배경색">글자 배경색</a>
                        <a href="javascript:;" class="tx-arrow" title="글자 배경색 선택">글자 배경색 선택</a>
                    </div>
                    <div id="tx_backcolor_menu" class="tx-menu tx-backcolor-menu tx-colorpallete" unselectable="on"></div>
                </li>
            </ul>


            <ul class="tx-bar tx-bar-left tx-group-align">
                <li class="tx-list">
                    <div unselectable="on" class="tx-btn-lbg tx-alignleft" id="tx_alignleft">
                        <a href="javascript:;" class="tx-icon" title="왼쪽정렬 (Ctrl+,)">왼쪽정렬</a>
                    </div>
                </li>
                <li class="tx-list">
                    <div unselectable="on" class="tx-btn-bg tx-aligncenter" id="tx_aligncenter">
                        <a href="javascript:;" class="tx-icon" title="가운데정렬 (Ctrl+.)">가운데정렬</a>
                    </div>
                </li>
                <li class="tx-list">
                    <div unselectable="on" class="tx-btn-bg tx-alignright" id="tx_alignright">
                        <a href="javascript:;" class="tx-icon" title="오른쪽정렬 (Ctrl+/)">오른쪽정렬</a>
                    </div>
                </li>
                <li class="tx-list">
                    <div unselectable="on" class="tx-btn-rbg tx-alignfull" id="tx_alignfull">
                        <a href="javascript:;" class="tx-icon" title="양쪽정렬">양쪽정렬</a>
                    </div>
                </li>
            </ul>

        </div>
    </div>


    <div id="tx_canvas" class="tx-canvas">
        <div id="tx_loading" class="tx-loading">
            <div><img src="/public_html/d_editor/images/icon/editor/loading2.png" width="113" height="21" align="absmiddle"/></div>
        </div>
        <div id="tx_canvas_wysiwyg_holder" class="tx-holder" style="display:block;"><%=B_Content %>
            <iframe id="tx_canvas_wysiwyg" name="tx_canvas_wysiwyg" allowtransparency="true" frameborder="0"></iframe>
        </div>
        <div class="tx-source-deco">
            <div id="tx_canvas_source_holder" class="tx-holder">
                <textarea id="tx_canvas_source" rows="30" cols="30"></textarea>
            </div>
        </div>
        <div id="tx_canvas_text_holder" class="tx-holder">
            <textarea id="tx_canvas_text" rows="30" cols="30"></textarea>
        </div>
    </div>
    <div id="tx_resizer" class="tx-resize-bar">
        <div class="tx-resize-bar-bg"></div>
        <img id="tx_resize_holder" src="/public_html/d_editor/images/icon/editor/skin/01/btn_drag01.gif" width="58" height="12" unselectable="on" alt=""/>
    </div>
    <div id="tx_attach_div" class="tx-attach-div">
        <div id="tx_attach_txt" class="tx-attach-txt">파일 첨부</div>
        <div id="tx_attach_box" class="tx-attach-box">
            <div class="tx-attach-box-inner">
                <div id="tx_attach_preview" class="tx-attach-preview">
                    <p></p>
                    <img src="/public_html/d_editor/images/icon/editor/pn_preview.gif" width="147" height="108" unselectable="on"/>
                </div>
                <div class="tx-attach-main">
                    <div id="tx_upload_progress" class="tx-upload-progress">
                        <div>0%</div>
                        <p>파일을 업로드하는 중입니다.</p>
                    </div>
                    <ul class="tx-attach-top">
                        <li id="tx_attach_delete" class="tx-attach-delete"><a>전체삭제</a></li>
                        <li id="tx_attach_size" class="tx-attach-size" style="display:none;">
                            파일: <span id="tx_attach_up_size" class="tx-attach-size-up"></span>/
                            <span id="tx_attach_max_size"></span>
                        </li>
                        <li id="tx_attach_tools" class="tx-attach-tools">
                        </li>
                    </ul>
                    <ul id="tx_attach_list" class="tx-attach-list"></ul>
                </div>
            </div>
        </div>
    </div>
</div>