
<div id="tx_trex_container" class="tx-editor-container">
    <div id="tx_sidebar" class="tx-sidebar">
        <div class="tx-sidebar-boundary">
            <ul class="tx-bar tx-bar-left tx-nav-attach">
                <li class="tx-list">
                    <div unselectable="on" id="tx_image" class="tx-image tx-btn-trans">
                        <a href="javascript:;" title="사진" class="tx-text">사진</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>

    <div id="tx_toolbar_basic" class="tx-toolbar tx-toolbar-basic">
        <div class="tx-toolbar-boundary">
            <ul class="tx-bar tx-bar-left">
                <li class="tx-list">
                    <div unselectable="on" class="tx-slt-100bg tx-fontsize" id="tx_fontsize">
                        <a href="javascript:;" title="글자크기">9pt</a>
                    </div>
                    <div id="tx_fontsize_menu" class="tx-fontsize-menu tx-menu" unselectable="on"></div>
                </li>
            </ul>
            <ul class="tx-bar tx-bar-left tx-group-font">

                <li class="tx-list">
                    <div unselectable="on" class="tx-btn-lbg tx-bold" id="tx_bold">
                        <a href="javascript:;" class="tx-icon" title="굵게 (Ctrl+B)">굵게</a>
                    </div>
                </li>
                <li class="tx-list">
                    <div unselectable="on" class="tx-btn-bg tx-underline" id="tx_underline">
                        <a href="javascript:;" class="tx-icon" title="밑줄 (Ctrl+U)">밑줄</a>
                    </div>
                </li>
                <li class="tx-list">
                    <div unselectable="on" class="tx-btn-bg tx-italic" id="tx_italic">
                        <a href="javascript:;" class="tx-icon" title="기울임 (Ctrl+I)">기울임</a>
                    </div>
                </li>
                <li class="tx-list">
                    <div unselectable="on" class="tx-btn-bg tx-strike" id="tx_strike">
                        <a href="javascript:;" class="tx-icon" title="취소선 (Ctrl+D)">취소선</a>
                    </div>
                </li>
                <li class="tx-list">
                    <div unselectable="on" class="tx-slt-tbg tx-forecolor" id="tx_forecolor">
                        <a href="javascript:;" class="tx-icon" title="글자색">글자색</a>
                        <a href="javascript:;" class="tx-arrow" title="글자색 선택">글자색 선택</a>
                    </div>
                    <div id="tx_forecolor_menu" class="tx-menu tx-forecolor-menu tx-colorpallete" unselectable="on"></div>
                </li>
                <li class="tx-list">
                    <div unselectable="on" class="tx-slt-brbg tx-backcolor" id="tx_backcolor">
                        <a href="javascript:;" class="tx-icon" title="글자 배경색">글자 배경색</a>
                        <a href="javascript:;" class="tx-arrow" title="글자 배경색 선택">글자 배경색 선택</a>
                    </div>
                    <div id="tx_backcolor_menu" class="tx-menu tx-backcolor-menu tx-colorpallete" unselectable="on"></div>
                </li>
            </ul>


            <ul class="tx-bar tx-bar-left tx-group-align">
                <li class="tx-list">
                    <div unselectable="on" class="tx-btn-lbg tx-alignleft" id="tx_alignleft">
                        <a href="javascript:;" class="tx-icon" title="왼쪽정렬 (Ctrl+,)">왼쪽정렬</a>
                    </div>
                </li>
                <li class="tx-list">
                    <div unselectable="on" class="tx-btn-bg tx-aligncenter" id="tx_aligncenter">
                        <a href="javascript:;" class="tx-icon" title="가운데정렬 (Ctrl+.)">가운데정렬</a>
                    </div>
                </li>
                <li class="tx-list">
                    <div unselectable="on" class="tx-btn-bg tx-alignright" id="tx_alignright">
                        <a href="javascript:;" class="tx-icon" title="오른쪽정렬 (Ctrl+/)">오른쪽정렬</a>
                    </div>
                </li>
                <li class="tx-list">
                    <div unselectable="on" class="tx-btn-rbg tx-alignfull" id="tx_alignfull">
                        <a href="javascript:;" class="tx-icon" title="양쪽정렬">양쪽정렬</a>
                    </div>
                </li>
            </ul>

        </div>
    </div>


    <div id="tx_canvas" class="tx-canvas">
        <div id="tx_loading" class="tx-loading">
            <div><img src="/public_html/d_editor/images/icon/editor/loading2.png" width="113" height="21" align="absmiddle"/></div>
        </div>
        <div id="tx_canvas_wysiwyg_holder" class="tx-holder" style="display:block;">
            <iframe id="tx_canvas_wysiwyg" name="tx_canvas_wysiwyg" allowtransparency="true" frameborder="0"></iframe>
        </div>
        <div class="tx-source-deco">
            <div id="tx_canvas_source_holder" class="tx-holder">
                <textarea id="tx_canvas_source" rows="30" cols="30"></textarea>
            </div>
        </div>
        <div id="tx_canvas_text_holder" class="tx-holder">
            <textarea id="tx_canvas_text" rows="30" cols="30"></textarea>
        </div>
    </div>
    <div id="tx_resizer" class="tx-resize-bar">
        <div class="tx-resize-bar-bg"></div>
        <img id="tx_resize_holder" src="/public_html/d_editor/images/icon/editor/skin/01/btn_drag01.gif" width="58" height="12" unselectable="on" alt=""/>
    </div>
    <div id="tx_attach_div" class="tx-attach-div">
        <div id="tx_attach_txt" class="tx-attach-txt">파일 첨부</div>
        <div id="tx_attach_box" class="tx-attach-box">
            <div class="tx-attach-box-inner">
                <div id="tx_attach_preview" class="tx-attach-preview">
                    <p></p>
                    <img src="/public_html/d_editor/images/icon/editor/pn_preview.gif" width="147" height="108" unselectable="on"/>
                </div>
                <div class="tx-attach-main">
                    <div id="tx_upload_progress" class="tx-upload-progress">
                        <div>0%</div>
                        <p>파일을 업로드하는 중입니다.</p>
                    </div>
                    <ul class="tx-attach-top">
                        <li id="tx_attach_delete" class="tx-attach-delete"><a>전체삭제</a></li>
                        <li id="tx_attach_size" class="tx-attach-size" style="display:none;">
                            파일: <span id="tx_attach_up_size" class="tx-attach-size-up"></span>/
                            <span id="tx_attach_max_size"></span>
                        </li>
                        <li id="tx_attach_tools" class="tx-attach-tools">
                        </li>
                    </ul>
                    <ul id="tx_attach_list" class="tx-attach-list"></ul>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var config = {
        txHost: '', /* 런타임 시 리소스들을 로딩할 때 필요한 부분으로, 경로가 변경되면 이 부분 수정이 필요. ex) http://xxx.xxx.com */
        txPath: '', /* 런타임 시 리소스들을 로딩할 때 필요한 부분으로, 경로가 변경되면 이 부분 수정이 필요. ex) /xxx/xxx/ */
        txService: 'sample', /* 수정필요없음. */
        txProject: 'sample', /* 수정필요없음. 프로젝트가 여러개일 경우만 수정한다. */
        initializedId: "", /* 대부분의 경우에 빈문자열 */
        wrapper: "tx_trex_container", /* 에디터를 둘러싸고 있는 레이어 이름(에디터 컨테이너) */
        form: 'tx_editor_form'+"", /* 등록하기 위한 Form 이름 */
        txIconPath: "images/icon/editor/", /*에디터에 사용되는 이미지 디렉터리, 필요에 따라 수정한다. */
        txDecoPath: "images/deco/contents/", /*본문에 사용되는 이미지 디렉터리, 서비스에서 사용할 때는 완성된 컨텐츠로 배포되기 위해 절대경로로 수정한다. */
        canvas: {
            initHeight: 200, //(원하시는 값을 픽셀값으로 입력하시면 됩니다.)
            styles: {
                color: "#123456", /* 기본 글자색 */
                fontFamily: "굴림", /* 기본 글자체 */
                fontSize: "12pt", /* 기본 글자크기 */
                backgroundColor: "#fff", /*기본 배경색 */
                lineHeight: "1.5", /*기본 줄간격 */
                padding: "8px" /* 위지윅 영역의 여백 */
            },
            showGuideArea: false
        },
        events: {
            preventUnload: false
        },
        sidebar: {
            attachbox: {
                show: true,
                confirmForDeleteAll: true

            },
            attacher:{
                image: {
                    features:{left:250, top:250, width:500, height:188},
                    checksize: false,
                    popPageUrl: "/public_html/d_editor/pages/trex/image_m.php",
                }
            },
            capacity:{maximum: 1014572800 }
        },

        size: {
            contentWidth: 900 /* 지정된 본문영역의 넓이가 있을 경우에 설정 */

        }


    };

    EditorJSLoader.ready(function(Editor) {
        var editor = new Editor(config);
    });

</script>
<script type="text/javascript">
    /* 예제용 함수 */
    function saveContent() {
        if($('#b_index').val()){
            if($('#b_password').val() == "") {
                alert('비밀번호를 입력해 주세요.');
                b_password.focus();
                return;
            }
            $.ajax({
                type : "POST",
                url : "/ajax/board/check_pass",
                dataType: 'json',
                data: {
                    csrf_token: $('input[name=csrf_token]').val(),
                    b_index : $('#b_index').val() ,
                    pass :$('#b_password').val()
                },
                success: function(result) {
                    if(result == "fail"){
                        alert('비밀번호가 틀렸습니다.');
                        b_password.focus();
                        return;
                    }else if(result == "success"){
                        Editor.save(); // 이 함수를 호출하여 글을 등록하면 된다.
                    }

                }
            });
        }else{
            Editor.save(); // 이 함수를 호출하여 글을 등록하면 된다.
        }

    }

    function validForm(editor) {
        var validator = new Trex.Validator();
        var content = editor.getContent();


        if($('#b_writer').val() == "") {
            alert('고객명을 입력해 주세요.');
            b_writer.focus();
            return;
        }
        if($('#b_password').val() == "") {
            alert('비밀번호를 입력해 주세요.');
            b_password.focus();
            return;
        }
        if($('#b_title').val() == "") {
            alert('제목을 입력해 주세요.');
            b_title.focus();
            return;
        }
        if($('#b_email1').val() == "" || $('#b_email2').val() == "") {
            alert('이메일을 입력해 주세요.');
            B_Email1.focus();
            return;
        }
        if (!validator.exists(content)) {
            alert('내용을 입력하세요');
            return false;
        }

        return true;
    }

    function setForm(editor) {
        var i, input;
        var form = editor.getForm();
        var content = editor.getContent();

        var textarea = document.createElement('textarea');

        textarea.name = 'b_content';
        $(textarea).css('display','none');
        textarea.value = content;
        form.createField(textarea);
        //var images = editor.getAttachments('image');
        var images = Editor.getSidebar().getAttachments("image");
        for (i = 0; i < images.length; i++) {
            // existStage는 현재 본문에 존재하는지 여부
            // if (images[i].existStage) {
            var entry = images[i];
            if( entry.deletedMark == false ){
                // data는 팝업에서 execAttach 등을 통해 넘긴 데이터
                //alert('attachment information - image[' + i + '] \r\n' + JSON.stringify(images[i].data));
                input = document.createElement('input');
                input.type = 'hidden';
                input.name = 'attach_image[]';
                //input.value = images[i].data.filename;  // 예에서는 이미지경로만 받아서 사용
                input.value =  images[i].data.f_rename + '|' +images[i].data.filename + '|'+  images[i].data.mimeType + '|'+  images[i].data.imageWidth + '|'+  images[i].data.filesize;  // 예에서는 이미지경로만 받아서 사용
                form.createField(input);
            }
        }

        var files = editor.getAttachments('file');
        for (i = 0; i < files.length; i++) {
            input = document.createElement('input');
            input.type = 'hidden';
            input.name = 'attach_file';
            //input.value = files[i].data.attachurl;
            //input.value = files[i].data.filename;
            //  alert('attachment information - image[' + i + '] \r\n' + JSON.stringify(files[i].data));
            input.value =  files[i].data.f_rename + '|' +images[i].data.filename + '|'+  files[i].data.mimeType + '|'+  files[i].data.imageWidth + '|'+  files[i].data.filesize+ '|'+  files[i].data.attachurl ;  // 예에서는 이미지경로만 받아서 사용
            form.createField(input);
        }
        return true;
    }
</script>
<script type="text/javascript">
    <!--

    $(function(){
        <?php if(!empty($b_index)) { ?>
        getContents();
        <?php }?>
    });

    function getContents() {

        $.ajax({
            type: "POST",
            url: "/ajax/board/get_view",
            dataType: 'json',
            data: {
                csrf_token: $('input[name=csrf_token]').val(),
                b_index : $("#b_index").val(),
                mode : 'site'
            } ,
            beforeSubmit: function (data, frm, opt) {
                console.log('데이타를 불러오는 중입니다.');
            },
            success: function(result) {
                //console.log(result);
                if(result.result == 'success') {
                    if(result.view.b_board_type == 1) {
                        if(result.view.file_cnt > 0) {
                            // 첨부 있을때
                            loadContents(result.view,result.file);
                        } else {
                            // 첨부 없을때
                            loadContents(result.view);
                        }
                    } else{
                        loadContents(result.view);
                    }
                } else {
                    // TODO 실패에 따른 처리
                    alert( result.msg);
                    history.back();
                }
            }
        });
    }


    function loadContents(reDate, files) {

        var attachments = {};
        attachments['image'] = [];
        attachments['file'] = [];

        if(typeof(reDate) != "undefined") {
            console.log(files);
            $.each(files, function(i, obj) {
                if(obj.f_index != null ) {
                    tmp_type = obj.f_type.split('/');
                    if(tmp_type[0] == "image") {
                        //console.log(obj[8]);  f_index,b_code,b_index,f_name ,f_type,f_position,f_width ,f_show ,f_size,f_rename,list_img ,file_path,reg_date
                        attachments['image'].push({
                            'attacher': 'image',
                            'data': {
                                'imageurl': obj.file_path,
                                'filename': obj.f_name,
                                'f_rename': obj.f_rename,
                                'filesize': obj.f_size,
                                'originalurl': obj.file_path,
                                'thumburl': obj.thumburl
                            }
                        });
                    } else {
                        attachments['file'].push({
                            'attacher': 'file',
                            'data': {
                                'attachurl': obj.file_path,
                                'filemime': obj.f_type,
                                'filename': obj.f_name,
                                'f_rename': obj.f_rename,
                                'filesize': obj.f_size
                            }
                        });
                    }
                }
            });
        }

        //console.log(attachments);
        $('#b_writer').val(reDate.b_writer);
        $('#b_title').val(reDate.b_title);
        $('#b_board_type').val(reDate.b_board_type);
        var _Email = reDate.b_email.split('@');
        $('#b_email1').val(_Email[0]);
        $('#b_email2').val(_Email[1]);
        $('#proc_type').val("M");
        /* 저장된 컨텐츠를 불러오기 위한 함수 호출 */
        Editor.modify({
            "attachments": function () { /* 저장된 첨부가 있을 경우 배열로 넘김, 위의 부분을 수정하고 아래 부분은 수정없이 사용 */
                var allattachments = [];
                for (var i in attachments) {
                    allattachments = allattachments.concat(attachments[i]);
                }
                return allattachments;
            }(),
            "content": reDate.b_content	/* 내용 문자열, 주어진 필드(textarea) 엘리먼트 */
        });
    }

    //-->
    $(document).ready(function(){
        $(document).on('click',".tx-name",function(){

            alert("현재 이미지를 대표이미지로 선택합니다.");
            var index = $( ".tx-name" ).index( this );
            $("#select_img").val(index);
        });

        // 폼 초기화
        $('#clear').click(function(){
            if (confirm("작성하던 내용을 모두 삭제 하시겠습니까?") == true){    //확인
                $('#b_writer').val("");
                $('#b_password').val("");
                $('#b_title').val("") ;
                $('#b_email1').val("") ;
                $('#b_email2').val("");
                $('#s_email').val("");
                $("#select_img").val('');
                new Editor(config);
//                Editor.modify({
//                    "attachments": function () { /* 저장된 첨부가 있을 경우 배열로 넘김, 위의 부분을 수정하고 아래 부분은 수정없이 사용 */
//                        var allattachments = [];
//                        return allattachments;
//                    }(),
//                    "content": function(){
//                        var temp ='<p></p>';
//                        return temp;
//                    }()	/* 내용 문자열, 주어진 필드(textarea) 엘리먼트 */
//                });
                //$('#tx-attach-preview').empty();
                //$('#tx-attach-preview').append("<img src='/public_html/d_editor/images/icon/editor/pn_preview.gif' width='147' height='108' unselectable='on'>");
                //$('#tx_attach_div').find('img').attr('src','/public_html/d_editor/images/icon/editor/pn_preview.gif');

            }
            //window.location.reload();
        });

    });
</script>