
<div id="" class="box_delivery" style="margin-top:110px;">
    <div id="" class="box_delivery_div01">
        <!-- <img src="/public_html/m/img/delivery01.png" border="0" alt=""> -->
        <div id="" class="text01">
            DELIVERY INFORMATION<br>
            &CAUTION
        </div>
        <div id="" class="text02">
            배송 관련 정보
        </div>
        <div id="" class="text03">
            고객센터 02-401-5073
        </div>

        <!-- <img src="/public_html/m/img/delivery03.png" border="0" alt=""> -->
    </div>
    <div id="" class="box_delivery_div02">
        <div id="" class="text07">
            01 배송 기간
        </div>

        <div id="" class="text08">
            고객님의 취향과 선택에 따라 재고없이, 주문 제작을 하기 때문에 일정 기간이 소요됩니다.<br>

            <span class="textbold">※ 구매 고객이 급증 할 경우 배송 기간이 연장되기에 미리 여유를 가지시고 <br>&nbsp;&nbsp;&nbsp;&nbsp;계획을 세우시길 권장합니다. </span>
        </div>

        <div id="" class="text07">
            02 배송 안내
        </div>
        <div id="" class="text08">
            배송일정 : 헷세드 구매 후 7일 이내 안내를 드립니다.<br>
            배송시간 : 배송 전날 안내를 드립니다.<br>
            <span class="textbold">※ 토, 일요일 배송은 진행하지 않습니다.</span>
        </div>

        <div id="" class="text07">
            03 배송 지역
        </div>
        <div id="" class="text08">
            전국 무료 배송입니다. <br>
            단, 해상운임 및 항공운임은 별도 고객님 부담입니다.<br>
            ※ 항공운임에는 현지 공항 도착 후 사용처까지의 운임도 포함합니다.

        </div>

        <div id="" class="text07">
            04 배송 업무
        </div>
        <div id="" class="text08">
            제품 이송은 (주)헷세드 정규 직원이 담당하며 직접 설치하여 드립니다.
        </div>

        <div id="" class="text07">
            유의사항
        </div>
        <div id="" class="text08">
            - 배송 전까지 설치 장소에 사물과 가구는 미리 정리하여 주시기 바랍니다.<br>
            - 사다리, 스카이차 등 특수 장비가 필요한 특수사항의 비용은 고객님 부담입니다.<br>
            - 고객님께서 사용 하시던 가구는 수거하지 않습니다.
        </div>
        <!-- <img src="/public_html/m/img/delivery02.png" border="0" alt="">
        <img src="/public_html/m/img/delivery04.png" border="0" alt=""> -->
        <div id="" class="img_onestop">
            <img src="/public_html/m/img/img_onestop.png" border="0" alt="">
        </div>
    </div>

</div>

<div id="" class="box_delivery" style="margin-top:13px;">
    <div id="" class="box_delivery_div03">
        <div id="" class="text04">
            AFTER-SALES SERVICE
        </div>
        <div id="" class="text05">
            A/S 규정
        </div>
        <div id="" class="text06">
            고객센터 02-401-5073
        </div>
    </div>
    <div id="" class="box_delivery_div04">
        <div id="" class="text07">
            AS 책임
        </div>
        <div id="" class="text08">
            헷세드는 매장만 갖춘 채 제품을 하청업자/중간유통업자/수입업자 등, 제3의 업자로부터 매입하여 판매하는 <br>
            일반유통브랜드가 아닙니다. 일반유통브랜드의 경우 판매 한 제품에 하자 및 반품에 대한 결함이 발생 할 경우 <br>
            AS의 책임을 제3의 공급업자를 찾아 전가해야 하는 리스크가 있습니다.  <br>
            (주)헷세드는 제품의 설계/제조/판매/배송을 동시에, 분석/결정/조치 할 수 있는 메이커브랜드입니다. <br>
            ‘가정의 소파와 침대’는 10년 이상 사용해야 하는 장기설치물로써 고객님들의 부주의에 의한 AS사항을 포함하여 <br>
            편리하게 조치 할 수 있는, 먼 약속을 지킬 수 있는 구조적 메이커브랜드를 전제하는 시스템을 갖추었습니다.

        </div>
        <div id="" class="text07">
            AS 무상
        </div>
        <div id="" class="text08">
            고객님들께서 직접 볼 수 없는 <span class="" style="font-weight:bold; display:inline-block;">내장재에 대한 일체 결함 및 하자에 대한 책임</span>을 본사로 귀결, <br>
            겉감을 고객님들 입장에서 다 사용하였다 할 때 까지는 무상처리 합니다.
        </div>

        <div id="" class="text07">
            AS유상
        </div>
        <div id="" class="text08">
            <span class="" style="font-weight:bold;">고객님들의 부주의에 의하여 발생된 유상AS는 추가 소요되는 재료비 및 배송비만 청구됩니다.</span>
            <br>(참고로, 매입판매식 결산으로 일체의 모든 비용을 취합 청구해야 하는 일반유통브랜드와 달리
            <br>메이커브랜드는 노임, 수수료 등 일반비용을 자체의 고정비로 처리할 수 있는 구조적 장점을 지녔습니다.)
        </div>
    </div>
</div>
