<div class="box_premium">
    <div id="" class="fl_left">
        <div class="box_premium_div01">
            프리미엄 라텍스와 오리지널 엑센느가<br>
            완벽한 숙면을 책임집니다.
        </div>

        <div id="" class="box_premium_div02 txt_just">
            <span class="" style="font-weight:bold;">R.V 라텍스 매트리스</span>

            헷세드는 유럽에서 최고 품질의 라텍스를 생산하는 네덜란드 회사의 R.V 라텍스를 사용합니다. 탄력성, 내구성, 인장도 면에서 프리미엄 퀄리티를 자랑하며, 네덜란드의 강력한 환경기준을 모두 통과한 환경친화적인 라텍스를 생산하고 있습니다. 또한 세계 3대 회사에서만 생산 가능한 탈라레이 공법으로 제작하는 프리미엄 라텍스입니다.
        </div>
    </div>


    <div id="" class="fl_right">
        <div id="" class="box_premium_div03">
            <span class="" style="font-weight:bold;">탈라레이공법 라텍스 침대의 특장점</span>

            <b>01</b>  촘촘한 핀홀의 연동작용으로 인체 하중을 가장 자연스럽게 받쳐 줍니다.<br>
            <b>02</b>  Air-Cell이 천연의 스프링 역할을 하여 옆 사람의 수면을 방해하지 않습니다. <br>
            <b>03</b>  매트리스 위에서 뛰어도 내부에서 먼지가 발생하지 않아 매우 위생적입니다. <br>
            <b>04</b>  Air-Cell에 의한 우수한 통기성으로 여름에는 시원하고 겨울에는 따뜻합니다. <br>
            <b>05</b>  유럽 최고 품질을 자랑하는 탄력성과 내구성으로 쾌적한 숙면을 제공합니다.
        </div>
    </div>

</div>