<link rel="stylesheet" type="text/css" href="/public_html/m/css/main_2017.css" />
<link rel="stylesheet" type="text/css" href="/public_html/m/css/main_2019_m.css" />
<!-- mySlider script file -->
<script src="/public_html/m/js/myslider.js"></script>
<link rel="stylesheet" type="text/css" href="/public_html/m/css/myslider.css" />

<!-- mySlider css file -->

	<div id="" class="wrap_middle">
		<div class="main_img-2019">
			<img src="public_html/img/hassed_smart-main5.jpg" border="0" alt="">
		</div>	
		<div class="main_img-2019">
			<img src="public_html/img/hassed_smart-main6.jpg" border="0" alt="">
		</div>	
	</div> 
