<link rel="stylesheet" type="text/css" href="/public_html/m/css/main_2017-cb<?php echo CACHE_VERSION;?>.css" />
<script>
	$(document).ready(function() {
		$('#pop1_close').click(function() {
			$('#pop1').hide();

		});
		$('#pop2_close').click(function() {
			$('#pop2').hide();

		});

        if(document.cookie.indexOf("popToday=close") < 0 ){      // 쿠키 저장여부 체크
            document.getElementById("main_dim").style.display = "block";
        }else {
            document.getElementById("main_dim").style.display = "none";
        }


        $('#pop_close').click(function() {
            $('#main_dim').hide();

        });
        $('#day_close').click(function() {
            setCookie( "popToday", "close");
            $('#main_dim').hide();

        });


	});
</script>
<!-- 새로운 레이어 팝업 2023.07.22 김현범 -->


<style type="text/css">
input[type="checkbox"] {
	display:none;
}
input[type="checkbox"]:checked ~ .modal, input[type="checkbox"]:checked ~ .modal-background {
	display: block;
}
.modal-background {
	width: 100%;
	height: 100%;
	background-color: rgba(0,0,0,0.5);
	position: fixed;
	top: 0;
	left: 0;
	display: none;
	z-index: 9998;
}
.modal {
	position: fixed;
	top: 0;
	left: 0;
	right: 0;
	bottom: 0;
	margin: auto;
	display: none;	
	width: 500px;
	height: 432px;
/*    height: 1122px;*/
	background-color: #fff;
	box-sizing: border-box;
	z-index: 9999;
}
.modal > p {
	padding: 0px;
	margin: 0;
}
.modal-header label {
	cursor: pointer;
}
.modal-header label:hover img {
	opacity: 0.6;
}

#dim_1 {
    top: 0px; left: 0px; width: 100%; height: 100%; z-index: 11001; opacity: 0.7; background-color: rgb(0, 0, 0);
    position: fixed;
    float : left;


}
#dim_2{
    position: fixed;
    bottom: 0;
    left: 0;
    width: 100%;
    z-index: 11002;
}


</style>
<!-- 새로운 레이어 팝업 2023.07.22 김현범 -->

<!-- mySlider script file -->
<script src="/public_html/m/js/myslider.js"></script>
<script>
    function vimeo_open(){
        document.getElementById("vimeo_img").style.display='none';
        document.getElementById("vimeo_frame").style.display='block';
    }
</script>

<!-- mySlider css file -->
<link rel="stylesheet" type="text/css" href="/public_html/m/css/myslider.css" />
	<div id="" class="wrap_middle">
		<div class="main_img">
			<div class="myslider">
				<div id='layerA' class="slider_img01"><img src="public_html/img/main_img01.jpg" border="0" alt=""></div>
				<div class="slider_img02"><img src="public_html/img/main_img02.jpg" border="0" alt=""></div>
				<div class="slider_img03"><img src="public_html/img/main_img03.jpg" border="0" alt=""></div>
			</div>
		</div>
		<div id="bx-point">
			<a href="#a"><div id="bt_point01"><img src="public_html/img/pagepoint.png" /></div></a>
			<a href="#b"><div id="bt_point02"><img src="public_html/img/pagepoint.png" /></div></a>
			<a href="#c"><div id="bt_point03"><img src="public_html/img/pagepoint.png" /></div></a>
		</div>

		<div id="" class="reviewnews">
			<div id="" class="box_news">
				<div id="" class="box_news_inline">
					<div class="mysliderb">
						<div class="sliderb_img01"><a href="https://cafe.naver.com/hassedhouse/48778"><img src="public_html/img/news-img-20250307.jpg" border="0" alt="" style="width:337px; height:384px;"></a></div>
						<div class="sliderb_img02"><a href="/notice/notice"><img src="public_html/img/news-img-20210112-04.jpg" border="0" alt=""></a></div>
					</div>
<!--						<div class="sliderb_img02"><a href="/notice/notice"><img src="public_html/img/news-img-20211111-03.jpg" border="0" alt=""></a></div>
-->
					<!-- <div id="" class="img_center">
						<img src="public_html/img/news_img01.jpg" border="0" alt="">
					</div> -->
					<div id="" class="title_news ">
						news
					</div>
					<!-- <div id="bx-point-news">
						<a href="#d"><div id="bt_pointb01"><img src="public_html/img/pagepoint.png" /></div></a>
						<a href="#e"><div id="bt_pointb02"><img src="public_html/img/pagepoint.png" /></div></a>
						<a href="#f"><div id="bt_pointb03"><img src="public_html/img/pagepoint.png" /></div></a>
						<a href="#g"><div id="bt_pointb04"><img src="public_html/img/pagepoint.png" /></div></a>
						<a href="#h"><div id="bt_pointb05"><img src="public_html/img/pagepoint.png" /></div></a>
					</div> -->

					<!-- <div id="" class="box_contest">
					마이홈자랑 콘테스트 진행중
					</div> -->
				</div>
			</div>
			<div id="" class="box_review bgcolor-ivory">
				<div id="" class="title_sub01 txt_darkgray">
					review
				</div>
				<div id="" class="box_review_2d">
					<div id="" class="mysliderc">
						
						<div id="slideA" class="review_slideA">
							<ul>
								<li><a href="/gallery/customer_view?b_index=26862"><img src="public_html/img/review-01-0120.jpg" border="0" alt=""></a></li>
								<li><a href="/gallery/customer_view?b_index=27425"><img src="public_html/img/review-02-0120.jpg" border="0" alt=""></a></li>
							</ul>
						</div>
						<div id="slideB" class="review_slideB">
							<ul>
								<li><a href="/gallery/customer_view?b_index=28360"><img src="public_html/img/review-03-0120.jpg" border="0" alt=""></a></li>
								<li><a href="/gallery/customer_view?b_index=26779"><img src="public_html/img/review-04-0120.jpg" border="0" alt=""></a></li>
							</ul>
						</div>
						<div id="slideC" class="review_slideC">
							<ul>
								<li><a href="/gallery/customer_view?b_index=28182"><img src="public_html/img/review-05-0120.jpg" border="0" alt=""></a></li>
								<li><a href="/gallery/customer_view?b_index=27038"><img src="public_html/img/review-06-0120.jpg" border="0" alt=""></a></li>
							</ul>
						</div>

					</div>
					<!-- <ul>
						<li><img src="public_html/img/review_img01.jpg" border="0" alt=""></li>
						<li><img src="public_html/img/review_img02.jpg" border="0" alt=""></li>
					</ul> -->
				</div>
				<div id="" class="box_7years">
					<?=date('Y')-2009?> years of customer reviews
				</div>
				<div id="bx-point-review">
					<a href="#i"><div id="bt_pointc01"><img src="public_html/img/pagepoint.png" /></div></a>
					<a href="#j"><div id="bt_pointc02"><img src="public_html/img/pagepoint.png" /></div></a>
					<a href="#k"><div id="bt_pointc03"><img src="public_html/img/pagepoint.png" /></div></a>
				</div>
			</div>

		</div>
		<div id="" class="movie_m">
			<div id="" class="title_movie">
				<img src="public_html/img/title_movie_BG.jpg" border="0" alt="">
			</div>
			<div id="wrap_mainvideo_m" class="mainvideo">
				<ul>
                    <div id="vimeo_img" onclick="javascript:vimeo_open();"><img src="public_html/img/bt_youtube_upscale.jpg" border="0" alt="" width="1080px" height="510px"></div>
					<div id="vimeo_frame" class="" style="display:none;"><iframe  id="player" type="text/html" width="1080" height="510" src="https://player.vimeo.com/video/208591714?title=0&transparent=0" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe></div>
				</ul>
			</div>
		</div>

		<div id="" class="product_store">
			<div id="" class="product_store_left">
				<img src="public_html/img/title_product.jpg" border="0" alt="">
				<div id="" class="box_product">
					<div id="" class="box_product_in01">
						<a href="/product/detail_view?code=arponio"><img src="public_html/img/img_product_sofa.jpg" border="0" alt=""></a>
					</div>
					<div id="" class="box_product_in02">
						<a href="/product/detail_view?code=august"><img src="public_html/img/img_product_bed.jpg" border="0" alt=""></a>
					</div>
				</div>

			</div>
			<div id="" class="product_store_right">
				<img src="public_html/img/title_store.jpg" border="0" alt="">
				<div id="" class="box_store">
					<div id="" class="box_store_in01">
						<a href="/about/shop_info?location=point_store"><img src="public_html/img/bt_roadshop.jpg" border="0" alt=""></a>
					</div>
					<div id="" class="box_store_in02">
						<a href="/about/shop_info?location=point_depart"><img src="public_html/img/index-store-img.png" border="0" alt=""></a>
					</div>
				</div>
			</div>
		</div>
	</div>

<?php
$current_date = date("Y-m-d");
$end_date = "2025-04-23";
$end_end_date = "2025-06-21";
if ($current_date <= $end_end_date) {
	if ($current_date <= $end_date) { ?>
		<div>
			<div id="pop1" class="main_pop2">
				<div><img src="public_html/images/250428_pop_up_570.jpg" usemap="#ex" border="0">
                    <map name="ex">
                        <area id="pop1_close" alt="닫기" title="닫기" href="javascript:void(0);" coords="0,0,14,14" shape="rect">
                        <area target="_blank" alt="" title="" href="https://cafe.naver.com/hassedhouse/48962" coords="0,19,569,435" shape="rect">
                    </map>
				</div>
			</div>
		</div>
		<?php
	} else {
		?>
		<div>
<!--			<div id="pop1" class="main_pop">-->
<!--				<div><img src="public_html/images/250428_pop_up_570.jpg" usemap="#ex" border="0">-->
<!--					<map name="ex">-->
<!--                        <area id="pop1_close" alt="닫기" title="닫기" href="javascript:void(0);" coords="0,0,14,14" shape="rect">-->
<!--                        <area target="_blank" alt="" title="" href="https://cafe.naver.com/hassedhouse/48962" coords="0,19,569,435" shape="rect">-->
<!--                    </map>-->
<!--					</map>-->
<!--				</div>-->
<!--			</div>-->
			<div id="pop2" class="main_pop2">
				<div><img src="public_html/images/250513_busan_570.jpg" usemap="#ex2" border="0"></div>
				<map name="ex2">
                    <area id="pop2_close" alt="닫기" title="닫기" href="javascript:void(0);" coords="0,0,14,14" shape="rect">
                    <area target="_blank" alt="" title="" href="https://cafe.naver.com/hassedhouse/49000" coords="570,437,1,17" shape="rect">

				</map>
			</div>

		</div>
	<?php }
}
?>
<!-- 새로운 레이어 팝업 2023.07.22 김현범 -->


<!--
	<input type="checkbox" id="modal" checked>
	<label for="modal" class="modal-background"></label>
	<div class="modal" onclick="document.getElementById('modal').prop('checked', false);"><div class="modal-header"><label for="modal"><img src="/public_html/img/20240116m.jpg"></label></div></div>
-->


<!-- 새로운 레이어 팝업 2023.07.22 김현
.modal css 의 width height를 이미지의 크기로 수정 (모바일에서 가로는 800)
-->

	<!-- <div id="hpopup" class="main_pop">
		<div>
		<img src="public_html/images/workshop2018.jpg">
		</div>
		<a href="#1"><div id="hclose" class="pop_close"> close </div></a>
	</div> -->



	<?PHP
	$current_date = date("Y-m-d");
	$end_date = "2025-02-15";
	if ($current_date <= $end_date) {
	?>
	<input type="checkbox" id="modal" checked>
	<label for="modal" class="modal-background"></label>
	<div class="modal" onclick="document.getElementById('modal').prop('checked', false);"><div class="modal-header"><label for="modal"><img src="/public_html/img/popup250110-250215b.jpg"></label></div></div>

	<!-- 새로운 레이어 팝업 2025.01.10 김현범
	이미지 사이즈 657 x 567
	-->

	<?PHP
	}
	?>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css"/>
<script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>
<div id="main_dim">
    <div id="dim_1"></div>
    <div id="dim_2">
        <div class="swiper">
            <!-- Additional required wrapper -->
            <div class="swiper-wrapper">
                <!-- Slides -->
                <?php foreach ($list_result as $key => $value){ ?>
                <div class="swiper-slide" style="height:400px">
                    <a href="<?php echo $value->pop_link;?>"> <img height="400px" width='100%' src="<?php echo $value->file_path?>/<?php echo $value->file_reName?>"></a>
                </div>
                <?php } ?>
            </div>
          </div>
        <div style="overflow: hidden; height:66px;">
            <div style="float: left; width: 50%;" id="pop_close"><img src="public_html/images/Close_button_normal.jpg"></div>
            <div style="float: left; width: 50%;" id="day_close"><img src="public_html/images/Close_button_today.jpg"></div>
    </div>

</div>
<script>
    const swiper = new Swiper('.swiper', {
        // Optional parameters
        autoplay: {
            // 슬라이드가 자동으로 이동하는 시간 간격
            delay: 3000,

            // disableOnInteraction true로 지정시 사용자 조작시 autoplay의 지속 여부를 결정 사용자 조작이란 이전,다음 버튼클릭 마우스로 슬라이더 이동 등을 의미
            disableOnInteraction: false,

            // pauseOnMouseEnter true로 지정시 슬라이더 위에 마우스를 올리면 autoplay가 자동으로 정지, 떼면 다시 시작을 의미
            pauseOnMouseEnter: false,

            // stopOnLastSlide true로 지정시 마지막 슬라이드에서 자동 슬라이드를 멈추는 옵션
            // loop를 true로 설정했다면 그 의도가 충돌되는 것이므로 상황에 맞게 선택해야 함
            stopOnLastSlide: false
        },
        loop: true,
        slidesPerView: 1
        // If we need pagination
        //pagination: {
            //el: '.swiper-pagination',
        //},

        // Navigation arrows
        //navigation: {
        //   nextEl: '.swiper-button-next',
        //   prevEl: '.swiper-button-prev',
        //},

        // And if we need scrollbar
        //scrollbar: {
        //    el: '.swiper-scrollbar',
        //},
    });

    //팝업 닫기


    function setCookie( name, value, expiredays ) {  // 쿠키저장

        var now = new Date(),
            year= now.getFullYear(),
            mon = now.getMonth(),
            day = now.getDate();

        // 시간지정(현재시간 + 지정시간)
        document.cookie = name + "=" + value + "; path=/; expires=" +  new Date( year, mon, day+1, 0, 0, 0 ) + ";"
        //위 정보를 쿠키에 굽는다
    }

</script>

