<link rel="stylesheet" type="text/css" href="/public_html/m/css/main_2017.css" />
<!-- mySlider script file -->
<script src="/public_html/m/js/myslider.js"></script>
<!-- mySlider css file -->
<link rel="stylesheet" type="text/css" href="/public_html/m/css/myslider.css" />
	<div id="" class="wrap_middle">
		<div class="main_img">
			<div class="myslider">
				<div id='layerA' class="slider_img01"><img src="public_html/img/main_img01.jpg" border="0" alt=""></div>
				<div class="slider_img02"><img src="public_html/img/main_img02.jpg" border="0" alt=""></div>
				<div class="slider_img03"><img src="public_html/img/main_img03.jpg" border="0" alt=""></div>
			</div>
		</div>
		<div id="bx-point">
			<a href="#a"><div id="bt_point01"><img src="public_html/img/pagepoint.png" /></div></a>
			<a href="#b"><div id="bt_point02"><img src="public_html/img/pagepoint.png" /></div></a>
			<a href="#c"><div id="bt_point03"><img src="public_html/img/pagepoint.png" /></div></a>
		</div>

		<div id="" class="reviewnews">
			<div id="" class="box_news">
				<div id="" class="box_news_inline">
					<div class="mysliderb">
						<div class="sliderb_img01"><a href="https://cafe.naver.com/hassedhouse/16472"><img src="public_html/img/news-img-20230131-01.jpg" border="0" alt="" style="width:337px; height:384px;"></a></div>
						<div class="sliderb_img02"><a href="/notice/notice"><img src="public_html/img/news-img-20210112-04.jpg" border="0" alt=""></a></div>
					</div>
<!--						<div class="sliderb_img02"><a href="/notice/notice"><img src="public_html/img/news-img-20211111-03.jpg" border="0" alt=""></a></div>
-->
					<!-- <div id="" class="img_center">
						<img src="public_html/img/news_img01.jpg" border="0" alt="">
					</div> -->
					<div id="" class="title_news ">
						news
					</div>
					<!-- <div id="bx-point-news">
						<a href="#d"><div id="bt_pointb01"><img src="public_html/img/pagepoint.png" /></div></a>
						<a href="#e"><div id="bt_pointb02"><img src="public_html/img/pagepoint.png" /></div></a>
						<a href="#f"><div id="bt_pointb03"><img src="public_html/img/pagepoint.png" /></div></a>
						<a href="#g"><div id="bt_pointb04"><img src="public_html/img/pagepoint.png" /></div></a>
						<a href="#h"><div id="bt_pointb05"><img src="public_html/img/pagepoint.png" /></div></a>
					</div> -->

					<!-- <div id="" class="box_contest">
					마이홈자랑 콘테스트 진행중
					</div> -->
				</div>
			</div>
			<div id="" class="box_review bgcolor-ivory">
				<div id="" class="title_sub01 txt_darkgray">
					review
				</div>
				<div id="" class="box_review_2d">
					<div id="" class="mysliderc">
						
						<div id="slideA" class="review_slideA">
							<ul>
								<li><a href="/gallery/customer_view?b_index=26862"><img src="public_html/img/review-01-0120.jpg" border="0" alt=""></a></li>
								<li><a href="/gallery/customer_view?b_index=27425"><img src="public_html/img/review-02-0120.jpg" border="0" alt=""></a></li>
							</ul>
						</div>
						<div id="slideB" class="review_slideB">
							<ul>
								<li><a href="/gallery/customer_view?b_index=28360"><img src="public_html/img/review-03-0120.jpg" border="0" alt=""></a></li>
								<li><a href="/gallery/customer_view?b_index=26779"><img src="public_html/img/review-04-0120.jpg" border="0" alt=""></a></li>
							</ul>
						</div>
						<div id="slideC" class="review_slideC">
							<ul>
								<li><a href="/gallery/customer_view?b_index=28182"><img src="public_html/img/review-05-0120.jpg" border="0" alt=""></a></li>
								<li><a href="/gallery/customer_view?b_index=27038"><img src="public_html/img/review-06-0120.jpg" border="0" alt=""></a></li>
							</ul>
						</div>

					</div>
					<!-- <ul>
						<li><img src="public_html/img/review_img01.jpg" border="0" alt=""></li>
						<li><img src="public_html/img/review_img02.jpg" border="0" alt=""></li>
					</ul> -->
				</div>
				<div id="" class="box_7years">
					<?=date('Y')-2009?> years of customer reviews
				</div>
				<div id="bx-point-review">
					<a href="#i"><div id="bt_pointc01"><img src="public_html/img/pagepoint.png" /></div></a>
					<a href="#j"><div id="bt_pointc02"><img src="public_html/img/pagepoint.png" /></div></a>
					<a href="#k"><div id="bt_pointc03"><img src="public_html/img/pagepoint.png" /></div></a>
				</div>
			</div>

		</div>
		<div id="" class="movie_m bgcolor-ivory">
			<div id="" class="title_movie">
				<img src="public_html/img/title_movie.png" border="0" alt="">
			</div>
			<div id="wrap_mainvideo_m" class="mainvideo">
				<ul>
					<iframe id="player" type="text/html" width="720" height="480" src="https://player.vimeo.com/video/208591714" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
				</ul>
			</div>
		</div>

		<div id="" class="product_store">
			<div id="" class="product_store_left">
				<img src="public_html/img/title_product.jpg" border="0" alt="">
				<div id="" class="box_product">
					<div id="" class="box_product_in01">
						<a href="/product/detail_view?code=arponio"><img src="public_html/img/img_product_sofa.jpg" border="0" alt=""></a>
					</div>
					<div id="" class="box_product_in02">
						<a href="/product/detail_view?code=august"><img src="public_html/img/img_product_bed.jpg" border="0" alt=""></a>
					</div>
				</div>

			</div>
			<div id="" class="product_store_right">
				<img src="public_html/img/title_store.jpg" border="0" alt="">
				<div id="" class="box_store">
					<div id="" class="box_store_in01">
						<a href="/about/shop_info?location=point_store"><img src="public_html/img/bt_roadshop.jpg" border="0" alt=""></a>
					</div>
					<div id="" class="box_store_in02">
						<a href="/about/shop_info?location=point_depart"><img src="public_html/img/index-store-img.png" border="0" alt=""></a>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- <div id="hpopup" class="main_pop">
		<div>
		<img src="public_html/images/workshop2018.jpg">
		</div>
		<a href="#1"><div id="hclose" class="pop_close"> close </div></a>
	</div> -->



