<SCRIPT LANGUAGE="JavaSCRIPT">
    //강아지 동영상 열기
    function windOPE()
    {
        noticeWindow  =  window.open("/public_html/mystery.html","ECSAINE",'left=200, top=40, width=360, height=720, resizable=no, scrollbars=no, status=no location=no ');
    }
</SCRIPT>
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/img_e/img_ecs_sp.jpg" border="0" alt="">
    </div>
    <div id="" class="box_full_in_center" style="padding-top:70px;">
        <img src="/public_html/img_e/titleimg_mat03.png" border="0" alt="">
    </div>
    <!-- 단락 ////////////////////////////////// 1 start-->
    <div id="" class="" style="width:100%; margin-top:109px; background: url('/public_html/img_e/bg_ecsaine01.jpg') no-repeat center;">
        <div id="" class="box_full_in_center" style="height:748px;">
            <div id="" class="fl_left" style="width:486px;">
                <div id="" class="">
                    <img src="/public_html/img_e/img_ecsaine01.png" border="0" alt="">
                </div>
                <div id="" class="txt_just" style="padding-top:56px; line-height:28px;">
                    Enjoy healthy skin contact and human breathing with original ECSAINE without leather chemical odor, harmful heavy metal chemicals. In everyday life at home, since furniture has something to do with the skin contact and body respiration, .HASSED presupposes a property of matter for happiness and health. Original ECSAINE, which forms a product of .HASSED, strictly restricts post-processing chemical treatment (such as flame retardancy / flame resistant/ water repellency) which may harm human body and skin.
                </div>
            </div>
            <div id="" class="fl_right" style="width:476px;">
                <div id="" class="" style="padding-top:44px;">
                    <img src="/public_html/img_e/titleimg_mat04.png" border="0" alt="">
                </div>
                <div id="" class="txt_just" style="padding-top:56px; line-height:28px;">
                    Original ECSAINE is an innovative material that exceeds the limits of conventional materials such as limited color such as black and white color, and the texture of vinyl leather, rough texture of textile and stagnation atmosphere. It has high sensitive color development that adds beauty and affectionate value in the bright light. It has a luxurious and distinctive atmosphere of our home in various colors, and it has an attractive touch and high sensitive emotion for valuable family and neighbors.
                </div>
                <div id="" class="" style="padding-top:33px;">
                    <img src="/public_html/img_e/img_ecsaine16.jpg" border="0" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- 단락 ////////////////////////////////////// 1 end-->


    <!-- 단락 ////////////////////////////////// 2 start-->
    <div id="" class="" style="width:100%; margin-top:129px; background: url('/public_html/img_e/bg_ecsaine02.jpg') no-repeat center;">
        <div id="" class="box_full_in_center" style="height:778px;">
            <div id="" class="fl_left" style="width:486px;">
                <div id="" class="" style="padding-top:65px;">
                    <img src="/public_html/img_e/titleimg_mat05.png" border="0" alt="">
                </div>
                <div id="" class="txt_just" style="padding-top:30px; line-height:28px;">
                    Original ECSAINE adopts the form of a whole process and has emotionally delicate yet attractive touch. In addition, there is no stiffness of touch which occurs in multilayer and coding work, but it has luxurious and soft flexibility which completes perfect silhouette of product as well as skin touch.

                </div>
                <div id="" class="" style="padding-top:100px;">
                    <img src="/public_html/img_e/titleimg_mat06.png" border="0" alt="">
                </div>
                <div id="" class="txt_just" style="padding-top:30px; line-height:28px;">
                    It maintains the constant temperature of the material, and has excellent air permeability for breathing with skin regardless of changes in external temperature, so you can enjoy being cool in Summer and being warm in Winter. That is the reason why Original ECSAINE is loved for a long time. Original ECSAINE protects the family's happiness and hygiene with a feeling of smoothness throughout the entire 365 days / 4 seasons, because there is no dampness in moisture due to air permeability block with multilayer.
                </div>
            </div>
            <div id="" class="fl_right" style="width:476px;">
                <div id="" class="" style="padding-top:0px;">
                    <img src="/public_html/img_e/titleimg_mat07.png" border="0" alt="">
                </div>
                <div id="" class="txt_just" style="padding-top:30px; line-height:28px;">
                    The excellent air permeability and the structural features that filter out fine particles make it easy to wipe off contamination of everyday life such as chocolate / coffee / ice cream with wet towel, which helps maintain the rhythm of happiness. Furthermore, the excellent shape resilience and durability that are strong against the claw marks of pets, loose strand and scratches add happiness to the family to raise pets.
                </div>
                <div id="" class="" style="padding-top:40px;">
                    <a href="javascript:windOPE();"><img src="/public_html/img_e/img_ecsaine17.jpg" border="0" alt=""></a>
                </div>
            </div>
        </div>
    </div>
    <!-- 단락 ////////////////////////////////////// 2 end-->

    <!-- 단락 ////////////////////////////////// 3 start-->
    <div id="" class="" style="margin-top:169px;">
        <div id="" class="box_full_in_center" style="height:357px; ">
            <div id="" class="fl_left" style="width:486px;">
                <div id="" class="">
                    <img src="/public_html/img_e/img_ecsaine18.jpg" border="0" alt="">
                </div>
            </div>
            <div id="" class="fl_right" style="width:476px;">
                <div id="" class="" style="padding-top:0px;">
                    <img src="/public_html/img_e/titleimg_mat08.png" border="0" alt="">
                </div>
                <div id="" class="txt_just" style="padding-top:40px; line-height:28px; clear: both;">
                    Original ECSAINE is leading the value of luxury goods around the world as it is best reputation. Feel the scarcity value of our pride with .HASSED goods. The secret for the best harmony at home is in .HASSED's philosophy of pursuing the beauty, harmony, happiness and health of a precious family.
                </div>
            </div>
        </div>
    </div>
    <!-- 단락 ////////////////////////////////////// 3 end-->


</div>