<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/img/img_ecsaine.jpg" border="0" alt="">
    </div>
    <div id="" class="box_title3">
        <img src="/public_html/img/title_ecsaine01.jpg" border="0" alt="">
    </div>
    <div id="" class="box_full bgcolor-ivory4" style="height:887px;">
        <div id="" class="box_full_in_center" style="padding-top: 70px;">
            <div id="" class="fl_left bgcolor-white" style="padding-top: 77px;">
                <div id="" class="" style="padding-bottom: 60px;">
                    <img src="/public_html/img/titleimg_mat01.png" border="0" alt="">
                </div>
                <div id="" class="txt_just" style="width:523px; padding: 0 37px; padding-bottom:40px; line-height:28px;">
                    Original ECSAINE는 가죽도 천도 인조피혁도 아닌 소재로서 기존 소재의 불편했던 단점을 모든 장점으로 즐길 수 있는  꿈의 소재입니다. <br>
                    3차원 망상구조의 일체가공형태로 이루어진 Original ECSAINE의 신비는 기존 소재의 한계를 넘어 우수한 물성을 지닐 수 있게 한 첨단 과학에 있습니다. 오늘날까지 전 세계적으로 Original ECSAINE를 그대로 재현하는  제품은 전무한 상태입니다.
                </div>
                <div id="" class="" style="width:523px; padding: 0 37px; padding-bottom: 70px">
                    <img src="/public_html/img/mat01img_01.jpg" border="0" alt="">
                </div>
            </div>
            <div id="" class="fl_right bgcolor-white" style="padding-top: 77px;">
                <div id="" class="" style="padding-bottom: 60px;">
                    <img src="/public_html/img/titleimg_mat02.png" border="0" alt="">
                </div>
                <div id="" class="txt_just" style="width:523px; padding: 0 37px; padding-bottom:40px; line-height:28px;">
                    기존의 소재와 전혀 다른 새로운 장르의 소재인 Original ECSAINE는 TORAY 社에서 세계 최초 개발되었습니다.<br>
                    전 세계의 섬유시장을 리드하고 있는 TORAY 社는 Original ECSAINE의 원천기술력에 따른 권위와 최초/최고/최대 가치를 창출하는 베스트 지위에 있습니다. 또한 전 세계를 하나의 품질과 하나의 운영 체계로, 명품적 가치 발전을 이끌어가는  시스템하에 있습니다.
                </div>
                <div id="" class="" style="width:523px; padding: 0 37px; padding-bottom: 70px">
                    <img src="/public_html/img/mat01img_02.jpg" border="0" alt="">
                </div>
            </div>
        </div>
    </div>

    <div id="" class="box_full_in_center" style="padding-top:98px; overflow:hidden;">
        <div id="" class="fl_left">
            <img src="/public_html/img/mat01img_03.jpg" border="0" alt="">
        </div>
        <div id="" class="fl_right">
            <img src="/public_html/img/mat01img_04.jpg" border="0" alt="">
        </div>
    </div>

    <div id="" class="box_full_in_center" style="padding-top:98px;">
        <img src="/public_html/img/mat01img_05.jpg" border="0" alt="">
    </div>

    <div id="" class="box_full_in_center" style="padding-top:98px;">
        <img src="/public_html/img/mat01img_06.jpg" border="0" alt="">
    </div>


</div>