<link rel="stylesheet" type="text/css" href="<?php echo CSS_DIR; ?>/board_hassed_2017.css" />
<link href='http://fonts.googleapis.com/css?family=Libre+Baskerville' rel='stylesheet' type='text/css'>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script type="text/javascript" src="/public_html/se2/js/HuskyEZCreator.js" charset="utf-8"></script>



<div id="wrap_middle" class="" style="margin-top:140px;">
    <div id="" class="box_full">
        <div class="sub_img">
            <img src="/public_html/img/img_board_main.png" border="0" alt="">
        </div>
        <div id="" class="" style="width:100%; height:308px; position:absolute; background-color:#faf8f6; display:block; z-index:-10; margin-top:-570px;">
        </div>
    </div>

    <div id="" class="box_full_in_center">
        <!--contents_info-->
        <div id="" style="width:1080px;height:879px">
            <div class="wrap_board">
                <div class="board_area">
                    <?php echo form_open_multipart('/gallery/customerStore/'); ?>
                        <input type="hidden" id="B_Code" name="B_Code" value="<%=B_Code%>" />
                        <input type="hidden" name="ProcType" id="ProcType" value="NW">
                        <input type="hidden" name="B_Depth" value="0">
                        <input type="hidden" name="B_ParentIndex" value="">
                        <input type="hidden" name="B_Board_Type" id="B_Board_Type" value="1">
                        <input type="hidden" id="B_Index" name="B_Index" value="">
                        <input type="hidden" name="select_img" id="select_img">
                        <div style="margin:0 0 14px;">
                            <label class="input_tit">고객명</label>
                            <input type="text" attr="1" name="B_Writer" id="B_Writer"  class="input_txt" style="width:200px;margin-right:206px;" value="<%=B_Writer %>"/>
                            <label class="input_tit">비밀번호</label>
                            <input type="password" attr="1" name="B_Password" id="B_Password" class="input_txt" style="width:200px;">
                        </div>
                        <div style="margin-bottom:14px;">
                            <label class="input_tit" style="margin-right:13px;" >제목</label>
                            <input type="text" attr="1" id="B_Title" name="B_Title" class="input_txt" style="width:365px;margin-right:50px;" placeholder="제목을 입력해주세요"  value="<%=B_Title%>" />
                            <label class="input_tit">E-mail</label>
                            <input type="text" attr="1"  name="B_Email1" id="B_Email1"  class="input_txt" style="width:66px;"   value="" />
                            @
                            <input type="text" attr="1" id="B_Email2" name="B_Email2" class="input_txt" style="width:138px;" value="" />
                            <select id="s_email" attr="1" title="E-Mail 선택" class="input_sel" style="width:80px;height:26px;" onChange="if(this.value==''){with(document.tx_editor_form){B_Email2.readOnly=false;B_Email2.value='';B_Email2.focus();}}else{with(document.tx_editor_form){B_Email2.readOnly=true;B_Email2.value=this.value;}}">
                                <option value="">직접입력</option>
                                <option value="gmail.com">G메일</option>
                                <option value="naver.com">네이버</option>
                                <option value="nate.com">네이트</option>
                                <option value="daum.net">다음</option>
                                <option value="hanmail.net">한메일</option>
                                <option value="empal.com" >엠팔</option>
                                <option value="hotmail.com">핫메일</option>
                                <option value="msn.com">MSN</option>
                            </select>
                        </div>
                        <div style="margin-bottom:20px;">
                            <input type="checkbox" name="B_Locked" class="textbox" value="Y" <%'If B_Code = "QANDA0" Then Response.write "checked"%>>
                            <font color="blue">※ 답변을 확인하실때 입력하신 비밀번호로 확인이 가능합니다.</font></br>
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="blue">※ 사진을 첨부하신 뒤, 하단 파일첨부 영역에서 이미지 이름을 클릭하여, 메인이미지를 설정해주세요.</font>
                        </div>
                        <textarea name="ir1" id="ir1" rows="10" cols="500" style="width:700px;"></textarea>
                        <div style="height:25px;overflow:hidden;">
                            <span style="float:right;">
                                <input type="button" class="btn_gray" id="clear" value="다시작성">
                                <input type="button" class="btn_blue" onclick="saveContent()" value="등록">
                                <input type="button" class="btn_white" value="취소" onclick="javascript:history.back();">
                            </span>
                        </div>
                    </div>
                </form>
            </div>
            <div style="height:200px;background:white;"></div>
        </div>
        <!--//contents_info-->
    </div>
</div>
<script type="text/javascript">

    var oEditors = [];

    nhn.husky.EZCreator.createInIFrame({
        oAppRef: oEditors,
        elPlaceHolder: "ir1",
        sSkinURI: "/public_html/se2/SmartEditor2Skin.html",
        fCreator: "createSEditor2",
        htParams : {
            bUseToolbar : true,             // 툴바 사용 여부 (true:사용/ false:사용하지 않음)
            bUseVerticalResizer : true,     // 입력창 크기 조절바 사용 여부 (true:사용/ false:사용하지 않음)
            bUseModeChanger : true,         // 모드 탭(Editor | HTML | TEXT) 사용 여부 (true:사용/ false:사용하지 않음)
            bSkipXssFilter : true,      // client-side xss filter 무시 여부 (true:사용하지 않음 / 그외:사용)
            //aAdditionalFontList : aAdditionalFontSet,     // 추가 글꼴 목록
            fOnBeforeUnload : function(){
                //alert("완료!");
            },

        }
    });

</script>