<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<div id="" class="wrap_middle">

    <div class="sub_img">
        <img src="/public_html/imgpro/img_ailish.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_ailish.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            This bed puts worries to sleep
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/ailish.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            burgundy in color
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/ailish_1.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/ailish_2.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/ailish_3.jpg" border="0" alt="">
        </div>

        <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_premium.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>
	<div id="" class="box_design">
	<img src="/public_html/imgpro/dim-bed-ailish-200514.jpg" border="0" alt="">
	</div>


<div class="btprolist">
 <a href="/product" ><img src="/public_html/prolist/bt-prolist.png"></a>
</div>

    <!-- topmenu ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- topmenu ////////////////////////////// -->

</div>