<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/imgpro/img_anjoo-bed.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_anjoo-bed.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            A cozy sleep in the flower field
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/img_anjoo-bed02.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            coral color
        </div>
         <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_premium.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>


<!--
    <div id="" class="box_colorfull">
        <div class="box_contents3">
            <div id="" class="fl_left">
                <div id="" class="txt_concept">
                    <div id="" class="txt_concept_div02">
                        anjoo design concept
                    </div>
                    <div id="" class="txt_concept_div03">
                        coral color
                    </div>
                    <div id="" class="txt_concept_div04">
                        부드러우면도 강한, 아름다우면서도 세련된 <br>미시적 멋의 섬세한 실루엣
                    </div>
                </div>
            </div>
            <div id="" class="fl_right conceptimg">
                <img src="/public_html/imgpro/img_anjoo-bed03.jpg" border="0" alt="">
            </div>
        </div>
    </div>
 -->


    <div id="" class="box_design">
        <img src="/public_html/imgpro/img_anjoo-bed04.jpg" border="0" alt="">
    </div>

    <!-- delivery ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- delivery ////////////////////////////// -->
</div>