<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/imgpro/img_becky.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_becky.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            The comfortable and elegant design stirs the emotion of women
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/Becky_0.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            red in color
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/Becky_1.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/Becky_2.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/Becky_3.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/Becky_4.jpg" border="0" alt="">
        </div>
        <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_special.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>


    <div id="" class="box_design">
        <!--<img src="/public_html/imgpro/becky04.jpg" border="0" alt="">-->
	<img src="/public_html/imgpro/dim-sofa-becky-200514.jpg" border="0" alt="">
    </div>

    <!-- delivery ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- delivery ////////////////////////////// -->
</div>