<link rel="stylesheet" type="text/css" href="/public_html/css/product_2021.css" />
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/img_product/arponio-main.png?v01" border="0" alt="">
    </div>
    <div class="box_title">
       <div class="eng">arponio
       </div>
       <div class="kor">섬세한 퀼팅 패턴으로 디테일에 집중하다
       </div>
    </div>
    <div class="box_outline">
        <div id="" class="div_proimg_left">
            <img src="/public_html/img_product/arponio-01.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center">
            <img src="/public_html/img_product/arponio-02.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_right">
            <img src="/public_html/img_product/arponio-03.jpg" border="0" alt="">
        </div>
	<!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_special.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>

    <div class="box_outline">
	<div id="" class="box_dimension">
		<div class="box_dim_left">
			<div class="box_dim_title">arponio <span>아르포니오</span></div>
			<div class="box_dim_menu">
				<ul>
					<li id="btn_A"><div class="bt_dim_menu">4인 코너</div></li>
					<li id="btn_B"><div class="bt_dim_menu">4인 일자</div></li>
					<li id="btn_C"><div class="bt_dim_menu">3인 일자</div></li>
					<!--<li id="btn_D"><div class="bt_dim_menu">1인 모듈</div></li>
					<li id="btn_E"><div class="bt_dim_menu">카우치 모듈</div></li>-->
				</ul>
			</div>
			<div class="box_dim_left_list">
				<ul>
					<li>등판높이<span>810mm</span></li>
					<li>좌판높이<span>400mm</span></li>
				</ul>
			
			</div>
			<div class="box_dim_left_txt">
				<ul>
					<li>- 제품 사이즈는 측정방법에 따라 1~2cm 오차범위를 허용하고 있으며, 제품 업그 레이드에 따라 변경될 수 있습니다.<br><br>- 우측 이미지는 이해를 돕기위한 3D 이미지 입니다. 사용자의 환경에 따라 실제와 다를 수 있으며, 매장에서 실제로 체험하시길 권장합니다.</li>
				</ul>
			
			</div>
		</div>
		<div class="box_dim_right">
			<div class="text_dimension">DIMENSION</div>
			<div class="box_contents">
				<div id="div_A" class="box_contents_div">
					<ul>
						<li><img src="/public_html/img-dim/4pc-arponio-coral.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-arponio-southbeach.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-arponio-red.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-arponio-yellow.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-arponio-green.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-arponio-sky.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-arponio-sweetviolet.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-arponio-darkblue.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-arponio-darkgreen.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-arponio-gray.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-arponio-purple.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-arponio-sandygray.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-arponio-landbrown.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-arponio-burgundy.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-arponio-camel.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-arponio-lightpink.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-arponio-neomint.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-arponio-goldlime.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-arponio-deeppeach.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-arponio-bettablue.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-arponio-blue.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-arponio-beige.jpg?v1" border="0" alt=""></li>
					</ul>
					<ul>
						<li><img src="/public_html/img-dim/4ps-arponio-coral.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-arponio-southbeach.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-arponio-red.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-arponio-yellow.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-arponio-green.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-arponio-sky.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-arponio-sweetviolet.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-arponio-darkblue.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-arponio-darkgreen.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-arponio-gray.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-arponio-purple.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-arponio-sandygray.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-arponio-landbrown.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-arponio-burgundy.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-arponio-camel.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-arponio-lightpink.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-arponio-neomint.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-arponio-goldlime.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-arponio-deeppeach.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-arponio-bettablue.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-arponio-blue.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-arponio-beige.jpg?v1" border="0" alt=""></li>
					</ul>
					<ul>
						<li><img src="/public_html/img-dim/3ps-arponio-coral.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-arponio-southbeach.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-arponio-red.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-arponio-yellow.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-arponio-green.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-arponio-sky.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-arponio-sweetviolet.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-arponio-darkblue.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-arponio-darkgreen.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-arponio-gray.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-arponio-purple.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-arponio-sandygray.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-arponio-landbrown.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-arponio-burgundy.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-arponio-camel.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-arponio-lightpink.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-arponio-neomint.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-arponio-goldlime.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-arponio-deeppeach.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-arponio-bettablue.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-arponio-blue.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-arponio-beige.jpg?v1" border="0" alt=""></li>
					</ul>
					
				</div>
			</div>
			<div class="box_color">
				<ul>
					<li><div id="btn_red" class="box_color_inbox bg-red"></div>red</li>
					<li><div id="btn_coral" class="box_color_inbox bg-coral"></div>coral</li>
					<li><div id="btn_yellow" class="box_color_inbox bg-yellow"></div>yellow</li>			
					<li><div id="btn_goldlime" class="box_color_inbox bg-goldlime"></div>gold lime</li>
					<li><div id="btn_sandygray" class="box_color_inbox bg-sandygray"></div>snady gray</li>
					<li><div id="btn_green" class="box_color_inbox bg-green"></div>green</li>
					<li><div id="btn_darkgreen" class="box_color_inbox bg-darkgreen"></div>dark green</li>
					<li><div id="btn_camal" class="box_color_inbox bg-camal"></div>camel</li>
					<li><div id="btn_landbrown" class="box_color_inbox bg-landbrown"></div>land brown</li>
					<li><div id="btn_deeppeach" class="box_color_inbox bg-deeppeach"></div>deep peach</li>
					<li><div id="btn_burgundy" class="box_color_inbox bg-burgundy"></div>burgundy</li>
				</ul>
				<ul>
					<li><div id="btn_purple" class="box_color_inbox bg-purple"></div>purple</li>
					<li><div id="btn_sweetviolet" class="box_color_inbox bg-sweetviolet"></div>sweet violet</li>
					<li><div id="btn_lightpink" class="box_color_inbox bg-lightpink"></div>light pink</li>
					<li><div id="btn_beige" class="box_color_inbox bg-beige"></div>beige</li>
					<li><div id="btn_gray" class="box_color_inbox bg-gray"></div>gray</li>
					<li><div id="btn_neomint" class="box_color_inbox bg-neomint"></div>neo mint</li>
					<li><div id="btn_southbeach" class="box_color_inbox bg-southbeach"></div>south beach</li>
					<li><div id="btn_sky" class="box_color_inbox bg-sky"></div>sky</li>
					<li><div id="btn_bettablue" class="box_color_inbox bg-bettablue"></div>bettablue</li>
					<li><div id="btn_blue" class="box_color_inbox bg-blue"></div>blue</li>
					<li><div id="btn_darkblue" class="box_color_inbox bg-darkblue"></div>dark blue</li>
				</ul>
				
			</div>
		</div>
	</div>
    </div>



    <!-- delivery ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- delivery ////////////////////////////// -->
</div>

