<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/imgpro/img_arriba.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_arriba.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            It creates an antique living room atmosphere
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/arriba.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            dark green in color
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/arriba_1.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/arriba_2.jpg" border="0" alt="">
        </div>
        <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_special.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>


<!--
    <div id="" class="box_colorfull">
        <div class="box_contents3">
            <div id="" class="fl_left">
                <div id="" class="txt_concept">
                    <div id="" class="txt_concept_div02">
                        arriba design concept
                    </div>
                    <div id="" class="txt_concept_div03">
                        coral color
                    </div>
                    <div id="" class="txt_concept_div04">
                        퀄팅처리를 현대적으로 표현한 모던 클래식 디자인<br>
                        거실 분위기를 아늑하게 바꿔주는 섬세한 디자인
                    </div>
                </div>
            </div>
            <div id="" class="fl_right conceptimg">
                <img src="/public_html/imgpro/img_arriba02.jpg" border="0" alt="">
            </div>
        </div>
    </div>
 -->

    <div id="" class="box_design">
       <!--  <img src="/public_html/imgpro/img_arriba03.jpg" border="0" alt=""> -->
	<img src="/public_html/imgpro/dim-sofa-arriba-200514.jpg" border="0" alt="">
    </div>
    <!-- delivery ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- delivery ////////////////////////////// -->

</div>