<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<div id="" class="wrap_middle">

    <div class="sub_img">
        <img src="/public_html/imgpro/img_bambi.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_bambi.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            It builds an angle of sensation
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/Bambi.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            dark green in color
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/Bambi_1.jpg" border="0" alt="">
        </div>
	 <div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/Bambi_2.jpg" border="0" alt="">
        </div>
        <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_special.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>


<!--
    <div id="" class="box_colorfull">
        <div class="box_contents3">
            <div id="" class="fl_left">
                <div id="" class="txt_concept">
                    <div id="" class="txt_concept_div02">
                        bambi design concept
                    </div>
                    <div id="" class="txt_concept_div03">
                        gray color
                    </div>
                    <div id="" class="txt_concept_div04">
                        넓고 편안한 등받이와 이중좌판의 안락함<br>
                        소파 전체에 엣지를 살린 감각적인 디자인
                    </div>
                </div>
            </div>
            <div id="" class="fl_right conceptimg">
                <img src="/public_html/imgpro/img_bambi02.jpg" border="0" alt="">
            </div>
        </div>
    </div>
-->


    <div id="" class="box_design">
        <img src="/public_html/imgpro/dim-sofa-bambi-200514.jpg" border="0" alt="">
    </div>


<div class="btprolist">
 <a href="/product" ><img src="/public_html/prolist/bt-prolist.png"></a>
</div>

    <!-- delivery ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- delivery ////////////////////////////// -->

</div>