<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<div id="" class="wrap_middle">

    <div class="sub_img">
        <img src="/public_html/imgpro/img_besso.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_besso.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            This sofa merges practicality and simplicity
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/Besso.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            baige in color
        </div>

	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/Besso_1.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/Besso_2.jpg" border="0" alt="">
        </div>
        <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_special.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>


<!--
    <div id="" class="box_colorfull">
        <div class="box_contents3">
            <div id="" class="fl_left">
                <div id="" class="txt_concept">
                    <div id="" class="txt_concept_div01"> -->
                        <!-- <img src="./img/concept_top_point.png" border="0" alt=""> -->
                    <!-- </div>
                    <div id="" class="txt_concept_div02">
                        besso design concept
                    </div>
                    <div id="" class="txt_concept_div03">
                        south beach
                    </div>
                    <div id="" class="txt_concept_div04">
                        실용적이고 모던한 미니멀 디자인<br>
                        실용과 심플함이 만나 감동이 된 스태디셀러
                    </div>
                </div>
            </div>
            <div id="" class="fl_right conceptimg">
                <img src="/public_html/imgpro/img_besso02.jpg" border="0" alt="">
            </div>
        </div>
    </div>
-->


    <div id="" class="box_design">
        <!--<img src="/public_html/imgpro/img_besso03.jpg" border="0" alt="">-->
	<img src="/public_html/imgpro/dim-sofa-besso-200514.jpg" border="0" alt="">
    </div>
    <!-- delivery ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- delivery ////////////////////////////// -->
</div>