<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/imgpro/img_boheme.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_boheme.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            feeling the smoothness of a latex silhouette and concise line design
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/boheme.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            landbrown in color
        </div>
        <div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/boheme_1.jpg" border="0" alt="">
        </div>
        <div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/boheme_2.jpg" border="0" alt="">
        </div>
        <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_special.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>


    <!--
        <div id="" class="box_colorfull">
            <div class="box_contents3">
                <div id="" class="fl_left">
                    <div id="" class="txt_concept">
                        <div id="" class="txt_concept_div02">
                            boheme design concept 
                        </div>
                        <div id="" class="txt_concept_div03">
                            landbrown color
                        </div>
                        <div id="" class="txt_concept_div04">
                           feeling the smoothness of a latex silhouette and concise line design
                        </div>
                    </div>
                </div>
                <div id="" class="fl_right conceptimg">
                    <img src="/public_html/imgpro/img_lavien03.jpg" border="0" alt="">
                </div>
            </div>
        </div>
    -->

    <div id="" class="box_design">
	<img src="/public_html/imgpro/dim-sofa-boheme-200514.jpg" border="0" alt="">
    </div>

    <!-- delivery ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- delivery ////////////////////////////// -->
</div>