<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/imgpro/img_brise.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_brise.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            Sophisticated design that gives a sense of stability in a comfortable pattern
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/brise.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            sweet violet in color
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/brise_1.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/brise_2.jpg" border="0" alt="">
        </div>
        <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_premium.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>


<!--
    <div id="" class="box_colorfull">
        <div class="box_contents3">
            <div id="" class="fl_left">
                <div id="" class="txt_concept">
                    <div id="" class="txt_concept_div02">
                        brise design concept
                    </div>
                    <div id="" class="txt_concept_div03">
                        sweet violet color
                    </div>
                    <div id="" class="txt_concept_div04">
                        아늑하고 우아한 분위기의 세미클래식 디자인<br>
                        이중좌판의 고급스러움과 안락함
                    </div>
                </div>
            </div>
            <div id="" class="fl_right conceptimg">
                <img src="/public_html/imgpro/img_brise03.jpg" border="0" alt="">
            </div>
        </div>
    </div>
-->

    <div id="" class="box_design">
        <img src="/public_html/imgpro/dim-bed-brise-210209.jpg" border="0" alt="">
    </div>

    <!-- delivery ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- delivery ////////////////////////////// -->
</div>