<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/imgpro/img_cozzy.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_cozzy.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            Simple soft line design which adds more comforts
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/cozzy.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            beta blue in color
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/cozzy_1.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/cozzy_2.jpg" border="0" alt="">
        </div>
         <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_premium.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>


<!--
    <div id="" class="box_colorfull">
        <div class="box_contents3">
            <div id="" class="fl_left">
                <div id="" class="txt_concept">
                    <div id="" class="txt_concept_div02">
                        cozzy design concept
                    </div>
                    <div id="" class="txt_concept_div03">
                        green color
                    </div>
                    <div id="" class="txt_concept_div04">
                        간결하면서도 부드러운 라인에 아늑함을 더한 디자인

                    </div>
                </div>
            </div>
            <div id="" class="fl_right conceptimg">
                <img src="/public_html/imgpro/img_cozzy03.jpg" border="0" alt="">
            </div>
        </div>
    </div>
-->

    <div id="" class="box_design">
        <img src="/public_html/imgpro//dim-sofa-cozzy.png" border="0" alt="">
    </div>

    <!-- delivery ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- delivery ////////////////////////////// -->
</div>