<link rel="stylesheet" type="text/css" href="/public_html/css_e/h_product.css" />
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/imgpro/img_crane.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro_e/title_crane.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            The young European sensibility is reflected on the sofa
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/crane.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            coral color
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/crane_1.jpg" border="0" alt="">
        </div>
	 <div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/crane_2.jpg" border="0" alt="">
        </div>
        <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('e_frame_special.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>


<!--
    <div id="" class="box_colorfull">
        <div class="box_contents3">
            <div id="" class="fl_left">
                <div id="" class="txt_concept">
                    <div id="" class="txt_concept_div02">
                        crane design concept
                    </div>
                    <div id="" class="txt_concept_div03">
                        sky color
                    </div>
                    <div id="" class="txt_concept_div04">
                        Comfort of spacious and convenient seat and back <br>
                        Young and sophisticated urban sensible design
                    </div>
                </div>
            </div>
            <div id="" class="fl_right ">
                <img src="/public_html/imgpro_e/img_crane02.jpg" border="0" alt="">
            </div>
        </div>
    </div>
-->

    <div id="" class="box_design">
        <img src="/public_html/imgpro_e/img-crane04.png" border="0" alt="">
    </div>

    <!-- delivery ////////////////////////////// -->
    <?php $this->load->view('e_frame_delivery.phtml');?>
    <!-- delivery ////////////////////////////// -->
</div>