<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<link rel="stylesheet" type="text/css" href="/public_html/css/product_2021.css" />


<div id="viewer" style="overflow: hidden; height: 380px;" class="vrcontainer">
<div class="vr" tabindex="0">
<img src="/public_html/imgvr/feecore-green0000.jpg">
</div>
<div class="spinner spinLeft" style="height: 380px;"></div>
<div class="spinner spinRight" style="height: 380px;"></div>
</div>

<script type="text/javascript">
  Firejune(function() {
    window.jQuery && jQuery.noConflict() && (jQuery.noConflict = function() { return jQuery; });
    
    Firejune.main('2.73', !1);

      try {
 
threeSixty = {
    init: function() {
        this._vr = new AC.VR('viewer', '/public_html/imgvr/feecore-green00##.jpg', 72, {
            invert: true
        });
    },
    didShow: function() {
        this.init();
    },
    willHide: function() {
        recycleObjectValueForKey(this, "_vr");
    },
    shouldCache: function() {
        return false;
    }
}

if (!window.isLoaded) {
    Event.observe(window, "load", function() {
        threeSixty.init();
    }, false);
}

 
} catch (e) { alert('ERROR: ' + e.message); }
  });
  </script>


</div>