<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/imgpro/img_esther.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_esther.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            It improves functionality through the multipurpose cushions

        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/esther.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            green in color
        </div>
	 <div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/esther_1.jpg" border="0" alt="">
        </div>
	 <div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/esther_2.jpg" border="0" alt="">
        </div>
        <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_special.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>

<!--
    <div id="" class="box_colorfull">
        <div class="box_contents3">
            <div id="" class="fl_left">
                <div id="" class="txt_concept">
                    <div id="" class="txt_concept_div02">
                        esther design concept
                    </div>
                    <div id="" class="txt_concept_div03">
                        sky color
                    </div>
                    <div id="" class="txt_concept_div04">
                        감싸주는 듯한 팔걸이의 안정감있는 디자인<br>
                        이중 등쿠션이 주는 풍성한 안락함
                    </div>
                </div>
            </div>
            <div id="" class="fl_right conceptimg">
                <img src="/public_html/imgpro/img_esther02.jpg" border="0" alt="">
            </div>
        </div>
    </div>
-->


<div class="btprolist">
 <a href="/product" ><img src="/public_html/prolist/bt-prolist.png"></a>
</div>

    <div id="" class="box_design">
        <img src="/public_html/imgpro/dim-sofa-esther-200514.jpg" border="0" alt="">
    </div>
    <!-- delivery ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- delivery ////////////////////////////// -->

</div>