<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/imgpro/img_feecore.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_feecore.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            Premium design with magnificent solid patterns 
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/feecore.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            dark green in color
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/feecore_1.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/feecore_2.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/feecore_3.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/feecore_4.jpg" border="0" alt="">
        </div>
        <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_special.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>


<!--
    <div id="" class="box_colorfull">
        <div class="box_contents3">
            <div id="" class="fl_left">
                <div id="" class="txt_concept">
                    <div id="" class="txt_concept_div02">
                        feecore design concept
                    </div>
                    <div id="" class="txt_concept_div03">
                        darkgreen color
                    </div>
                    <div id="" class="txt_concept_div04">
                        가족들의 라이프 스타일을 고려한 탈착형 등받이와 <br>공간 활용도를 높인 디테일한 설계로 실용성을 높임
                    </div>
                </div>
            </div>
            <div id="" class="fl_right conceptimg">
                <img src="/public_html/imgpro/img_feecore03.jpg" border="0" alt="">
            </div>
        </div>
    </div>
-->
    <div id="" class="box_design">
        <img src="/public_html/imgpro/dim-sofa-feecore-211026.jpg" border="0" alt="">
    </div>

    <!-- delivery ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- delivery ////////////////////////////// -->
</div>