<link rel="stylesheet" type="text/css" href="/public_html/css/product_2021.css" />
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/img_product/feecore-main.png?v01" border="0" alt="">
    </div>
    <div class="box_title">
       <div class="eng">feecore
       </div>
       <div class="kor">가족들의 라이프 스타일을 고려한  <br>탈착형 등받이와 공간 활용도를 높인 <br>디테일한 설계로 실용성을 높임
       </div>
    </div>
    <div class="box_outline">
        <div id="" class="div_proimg_left">
            <img src="/public_html/img_product/feecore-01.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center">
            <img src="/public_html/img_product/feecore-02.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_right">
            <img src="/public_html/img_product/feecore-03.jpg" border="0" alt="">
        </div>
	<!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_special.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>

    <div class="box_outline">
	<div id="" class="box_dimension">
		<div class="box_dim_left">
			<div class="box_dim_title">feecore <span>피코르</span></div>
			<div class="box_dim_menu">
				<ul>
					<li id="btn_A"><div class="bt_dim_menu">8인 코너</div></li>
					<li id="btn_B"><div class="bt_dim_menu">6인 코너</div></li>
					<li id="btn_C"><div class="bt_dim_menu">4인 코너</div></li>
					<li id="btn_D"><div class="bt_dim_menu">4인 일자</div></li>
					<li id="btn_E"><div class="bt_dim_menu">3인 일자</div></li>
				</ul>
			</div>
			<div class="box_dim_left_list">
				<ul>
					<li>등판높이<span>750mm</span></li>
					<li>좌판높이<span>370mm</span></li>
				</ul>
			
			</div>
			<div class="box_dim_left_txt">
				<ul>
					<li>- 제품 사이즈는 측정방법에 따라 1~2cm 오차범위를 허용하고 있으며, 제품 업그 레이드에 따라 변경될 수 있습니다.<br><br>- 우측 이미지는 이해를 돕기위한 3D 이미지 입니다. 사용자의 환경에 따라 실제와 다를 수 있으며, 매장에서 실제로 체험하시길 권장합니다.</li>
				</ul>
			
			</div>
		</div>
		<div class="box_dim_right">
			<div class="text_dimension">DIMENSION</div>
			<div class="box_contents">
				<div id="div_A" class="box_contents_div">
					<ul>
						<li><img src="/public_html/img-dim/8pc-feecore-coral.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/8pc-feecore-southbeach.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/8pc-feecore-red.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/8pc-feecore-yellow.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/8pc-feecore-green.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/8pc-feecore-sky.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/8pc-feecore-sweetviolet.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/8pc-feecore-darkblue.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/8pc-feecore-darkgreen.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/8pc-feecore-gray.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/8pc-feecore-purple.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/8pc-feecore-sandygray.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/8pc-feecore-landbrown.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/8pc-feecore-burgundy.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/8pc-feecore-camal.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/8pc-feecore-lightpink.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/8pc-feecore-neomint.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/8pc-feecore-goldlime.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/8pc-feecore-deeppeach.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/8pc-feecore-bettablue.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/8pc-feecore-blue.jpg?v1" border="0" alt=""></li>
					</ul>
					<ul>
						<li><img src="/public_html/img-dim/6pc-feecore-coral.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/6pc-feecore-southbeach.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/6pc-feecore-red.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/6pc-feecore-yellow.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/6pc-feecore-green.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/6pc-feecore-sky.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/6pc-feecore-sweetviolet.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/6pc-feecore-darkblue.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/6pc-feecore-darkgreen.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/6pc-feecore-gray.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/6pc-feecore-purple.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/6pc-feecore-sandygray.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/6pc-feecore-landbrown.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/6pc-feecore-burgundy.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/6pc-feecore-camal.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/6pc-feecore-lightpink.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/6pc-feecore-neomint.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/6pc-feecore-goldlime.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/6pc-feecore-deeppeach.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/6pc-feecore-bettablue.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/6pc-feecore-blue.jpg?v1" border="0" alt=""></li>
					</ul>
					<ul>
						<li><img src="/public_html/img-dim/4pc-feecore-coral.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-feecore-southbeach.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-feecore-red.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-feecore-yellow.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-feecore-green.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-feecore-sky.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-feecore-sweetviolet.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-feecore-darkblue.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-feecore-darkgreen.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-feecore-gray.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-feecore-purple.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-feecore-sandygray.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-feecore-landbrown.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-feecore-burgundy.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-feecore-camal.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-feecore-lightpink.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-feecore-neomint.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-feecore-goldlime.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-feecore-deeppeach.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-feecore-bettablue.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4pc-feecore-blue.jpg?v1" border="0" alt=""></li>
					</ul>
					<ul>
						<li><img src="/public_html/img-dim/4ps-feecore-coral.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-feecore-southbeach.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-feecore-red.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-feecore-yellow.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-feecore-green.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-feecore-sky.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-feecore-sweetviolet.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-feecore-darkblue.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-feecore-darkgreen.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-feecore-gray.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-feecore-purple.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-feecore-sandygray.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-feecore-landbrown.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-feecore-burgundy.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-feecore-camal.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-feecore-lightpink.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-feecore-neomint.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-feecore-goldlime.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-feecore-deeppeach.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-feecore-bettablue.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/4ps-feecore-blue.jpg?v1" border="0" alt=""></li>
					</ul>
					<ul>
						<li><img src="/public_html/img-dim/3ps-feecore-coral.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-feecore-southbeach.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-feecore-red.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-feecore-yellow.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-feecore-green.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-feecore-sky.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-feecore-sweetviolet.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-feecore-darkblue.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-feecore-darkgreen.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-feecore-gray.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-feecore-purple.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-feecore-sandygray.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-feecore-landbrown.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-feecore-burgundy.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-feecore-camal.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-feecore-lightpink.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-feecore-neomint.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-feecore-goldlime.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-feecore-deeppeach.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-feecore-bettablue.jpg?v1" border="0" alt=""></li>
						<li><img src="/public_html/img-dim/3ps-feecore-blue.jpg?v1" border="0" alt=""></li>
					</ul>
				</div>
			</div>
			<div class="box_color">
				<ul>
					<li><div id="btn_red" class="box_color_inbox bg-red"></div>red</li>
					<li><div id="btn_coral" class="box_color_inbox bg-coral"></div>coral</li>
					<li><div id="btn_yellow" class="box_color_inbox bg-yellow"></div>yellow</li>			
					<li><div id="btn_goldlime" class="box_color_inbox bg-goldlime"></div>gold lime</li>
					<li><div id="btn_sandygray" class="box_color_inbox bg-sandygray"></div>snady gray</li>
					<li><div id="btn_green" class="box_color_inbox bg-green"></div>green</li>
					<li><div id="btn_darkgreen" class="box_color_inbox bg-darkgreen"></div>dark green</li>
					<li><div id="btn_camal" class="box_color_inbox bg-camal"></div>camel</li>
					<li><div id="btn_landbrown" class="box_color_inbox bg-landbrown"></div>land brown</li>
					<li><div id="btn_deeppeach" class="box_color_inbox bg-deeppeach"></div>deep peach</li>
					<li><div id="btn_burgundy" class="box_color_inbox bg-burgundy"></div>burgundy</li>
				</ul>
				<ul>
					<li><div id="btn_purple" class="box_color_inbox bg-purple"></div>purple</li>
					<li><div id="btn_sweetviolet" class="box_color_inbox bg-sweetviolet"></div>sweet violet</li>
					<li><div id="btn_lightpink" class="box_color_inbox bg-lightpink"></div>light pink</li>
					<li><div id="btn_gray" class="box_color_inbox bg-gray"></div>gray</li>
					<li><div id="btn_neomint" class="box_color_inbox bg-neomint"></div>neo mint</li>
					<li><div id="btn_southbeach" class="box_color_inbox bg-southbeach"></div>south beach</li>
					<li><div id="btn_sky" class="box_color_inbox bg-sky"></div>sky</li>
					<li><div id="btn_bettablue" class="box_color_inbox bg-bettablue"></div>bettablue</li>
					<li><div id="btn_blue" class="box_color_inbox bg-blue"></div>blue</li>
					<li><div id="btn_darkblue" class="box_color_inbox bg-darkblue"></div>dark blue</li>
					
					<!--<li><div id="btn_beige" class="box_color_inbox bg-beige"></div>beige</li>-->
				</ul>
				
			</div>
		</div>
	</div>
    </div>





    <!-- delivery ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- delivery ////////////////////////////// -->
</div>