<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/imgpro/img_fliche.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_fliche.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            Elegant and elegant design with asymmetrical lines
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/fliche.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            gray in color
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/fliche_1.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/fliche_2.jpg" border="0" alt="">
        </div>
         <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_premium.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>


<!--
    <div id="" class="box_colorfull">
        <div class="box_contents3">
            <div id="" class="fl_left">
                <div id="" class="txt_concept">
                    <div id="" class="txt_concept_div02">
                        fliche design concept
                    </div>
                    <div id="" class="txt_concept_div03">
                        gray color
                    </div>
                    <div id="" class="txt_concept_div04">
                        비대칭 라인에서 느껴지는 절제된 아름다움으로<br> 우아하고 품격있는 디자인
                    </div>
                </div>
            </div>
            <div id="" class="fl_right conceptimg">
                <img src="/public_html/imgpro/img_fliche03.jpg" border="0" alt="">
            </div>
        </div>
    </div>
-->

    <div id="" class="box_design">
        <!--<img src="/public_html/imgpro/img_fliche04.jpg" border="0" alt="">-->
	<img src="/public_html/imgpro/dim-bed-fliche-211026.jpg" border="0" alt="">
    </div>

    <!-- delivery ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- delivery ////////////////////////////// -->
</div>