<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/imgpro/img_francis.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_francis.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            It adds practicality to modernity
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/francis.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            yellow in color
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/francis_1.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/francis_2.jpg" border="0" alt="">
        </div>
        <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_special.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>


<!--
    <div id="" class="box_colorfull">
        <div class="box_contents3">
            <div id="" class="fl_left">
                <div id="" class="txt_concept">
                    <div id="" class="txt_concept_div02">
                        francis design concept
                    </div>
                    <div id="" class="txt_concept_div03">
                        sky color
                    </div>
                    <div id="" class="txt_concept_div04">
                        계단형 등받이의 인체공학적 디자인<br>
                        아이들의 놀이공간으로도 좋은 실용적 디자인
                    </div>
                </div>
            </div>
            <div id="" class="fl_right conceptimg">
                <img src="/public_html/imgpro/img_francis02.jpg" border="0" alt="">
            </div>
        </div>
    </div>
-->



    <div id="" class="box_design">
        <!--<img src="/public_html/imgpro/img_francis03.jpg" border="0" alt="">-->
	<img src="/public_html/imgpro/img-sofa-francis04.png" border="0" alt="">
    </div>
    <!-- delivery ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- delivery ////////////////////////////// -->

</div>