<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/imgpro/img_haesta.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_haesta.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            Noblesse leads to hexagonal puzzles
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/haesta.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            southbeach color
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/haesta_1.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/haesta_2.jpg" border="0" alt="">
        </div>
         <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_premium.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>


<!--
    <div id="" class="box_colorfull">
        <div class="box_contents3">
            <div id="" class="fl_left">
                <div id="" class="txt_concept">
                    <div id="" class="txt_concept_div02">
                        haesta design concept
                    </div>
                    <div id="" class="txt_concept_div03">
                        southbeach color
                    </div>
                    <div id="" class="txt_concept_div04">
                      
                        퀄팅을 더하여 우아한 매력이 돋보이는 디자인 침대
                    </div>
                </div>
            </div>
            <div id="" class="fl_right conceptimg">
                <img src="/public_html/imgpro/img_haesta03.jpg" border="0" alt="">
            </div>
        </div>
    </div>
-->

    <div id="" class="box_design">
        <img src="/public_html/imgpro/img_haesta04.jpg" border="0" alt="">
    </div>

    <!-- delivery ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- delivery ////////////////////////////// -->
</div>