<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/imgpro-2022/img-laffine.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro-2022/title_laffine.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            It's more than simple, funtionable
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro-2022/img-laffine-s01.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro-2022/img-laffine-s02.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro-2022/img-laffine-s03.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            yellow in color
        </div>
        <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_special.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>

    <div id="" class="box_design">
        <img src="/public_html/imgpro-2022/img-dim-laffine.jpg" border="0" alt="">
    </div>

    <!-- delivery ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- delivery ////////////////////////////// -->
</div>