<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/imgpro/img_miner.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_miner.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            Designed with modern sensibility and soft shilhouette creating family lifestyle
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/miner.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            sky blue in color
        </div>
	 <div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/miner_1.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/miner_2.jpg" border="0" alt="">
        </div>
        <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_special.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>


<!--
    <div id="" class="box_colorfull">
        <div class="box_contents3">
            <div id="" class="fl_left">
                <div id="" class="txt_concept">
                    <div id="" class="txt_concept_div02">
                        miner design concept
                    </div>
                    <div id="" class="txt_concept_div03">
                        sand gray color
                    </div>
                    <div id="" class="txt_concept_div04">
                        
			풍성한 볼륨감으로 온 가족이 함께 사용 가능한 패밀리 스타일

                    </div>
                </div>
            </div>
            <div id="" class="fl_right conceptimg">
                <img src="/public_html/imgpro/img_miner03.jpg" border="0" alt="">
            </div>
        </div>
    </div>
-->
    <div id="" class="box_design">
        <img src="/public_html/imgpro/dim-sofa-miner-211026.jpg" border="0" alt="">
    </div>

    <!-- delivery ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- delivery ////////////////////////////// -->
</div>