<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/imgpro/img_olo.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_olo.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            Simple & unique design which best matches with other furnitures
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/olo.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            yellow in color
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/olo_1.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/olo_2.jpg" border="0" alt="">
        </div>
        <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_special.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>


<!--
    <div id="" class="box_colorfull">
        <div class="box_contents3">
            <div id="" class="fl_left">
                <div id="" class="txt_concept">
                    <div id="" class="txt_concept_div02">
                        olo design concept
                    </div>
                    <div id="" class="txt_concept_div03">
				yellow & coral color
                    </div>
                    <div id="" class="txt_concept_div04">
                        다른 가구와 믹스매치 하여 개성있는 <br>분위기 연출이 가능한 포인트 소파
                    </div>
                </div>
            </div>
            <div id="" class="fl_right conceptimg">
                <img src="/public_html/imgpro/img_olo03.jpg" border="0" alt="">
            </div>
        </div>
    </div>
-->

<div class="btprolist">
 <a href="/product" ><img src="/public_html/prolist/bt-prolist.png"></a>
</div>

    <div id="" class="box_design">
        <img src="/public_html/imgpro/dim-sofa-olo-200514.jpg" border="0" alt="">
    </div>

    <!-- delivery ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- delivery ////////////////////////////// -->
</div>