<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/imgpro/img_peanut.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_peanut.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            Future urban sense designed sofa with puzzle combination
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/peanut.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            south beach in color
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/peanut_1.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/peanut_2.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/peanut_3.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/peanut_4.jpg" border="0" alt="">
        </div>
        <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_special.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>


<!--
    <div id="" class="box_colorfull">
        <div class="box_contents3">
            <div id="" class="fl_left">
                <div id="" class="txt_concept">
                    <div id="" class="txt_concept_div02">
                        peanut design concept
                    </div>
                    <div id="" class="txt_concept_div03">
                        south beach color
                    </div>
                    <div id="" class="txt_concept_div04">
                        
                        피넛 패턴의 지지대를 자유롭게 이동하는 편리함과 <br>다양한 스타일을 구사 할 수 있는 유니크한 디자인의 소파
                    </div>
                </div>
            </div>
            <div id="" class="fl_right conceptimg">
                <img src="/public_html/imgpro/img_peanut03.jpg" border="0" alt="">
            </div>
        </div>
    </div>
-->

    <div id="" class="box_design">
        <img src="/public_html/imgpro/dim-sofa-peanut-200514.jpg" border="0" alt="">
    </div>

    <!-- delivery ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- delivery ////////////////////////////// -->
</div>