<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<div id="" class="wrap_middle">

    <div class="sub_img">
        <img src="/public_html/imgpro/img_prince-20190219.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_prince.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            Simple, slim minimalism design bed, prince
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/prince.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            coral in color
        </div>
        <div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/prince-1.jpg" border="0" alt="">
        </div>
        <div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/prince-2.jpg" border="0" alt="">
        </div>

        <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_premium.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>



    <div id="" class="" style="width:1080px; margin:0 auto; z-index:30; margin-top:100px; ">
        <!--  <img src="/public_html/imgpro/img_prince01.jpg" border="0" alt=""> -->
        <img src="/public_html/imgpro/dim-bed-prince-210209.jpg" border="0" alt="">
    </div>

    <!-- topmenu ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- topmenu ////////////////////////////// -->

</div>