<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/imgpro/img_arponio.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_arponio.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            Noblesse design focused on details with semi-classical quilting patterns
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/arponio.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            sand gray in color
        </div>
        <div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/arponio_1.jpg" border="0" alt="">
        </div>
        <div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/arponio_2.jpg" border="0" alt="">
        </div>
        <div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/arponio_3.jpg" border="0" alt="">
        </div>
        <div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/arponio_4.jpg" border="0" alt="">
        </div>
        <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_special.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>


    <div id="" class="box_design">
        <img src="/public_html/imgpro/dim-sofa-arponio-200514.jpg" border="0" alt="">
    </div>

    <!-- delivery ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- delivery ////////////////////////////// -->
</div>