<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/imgpro/img_provance.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_provance.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            Plain design creates exotic atmosphere
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/img_provance01.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            sky color
        </div>
        <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_special.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>

    <div id="" class="box_colorfull">
        <div class="box_contents3">
            <div id="" class="fl_left">
                <div id="" class="txt_concept">
                    <div id="" class="txt_concept_div01">
                        <!-- <img src="./img/concept_top_point.png" border="0" alt=""> -->
                    </div>
                    <div id="" class="txt_concept_div02">
                        provance design concept
                    </div>
                    <div id="" class="txt_concept_div03">
                        purple color
                    </div>
                    <div id="" class="txt_concept_div04">
                        부드러운 느낌의 곡선의 미를 강조한 디자인<br>
                        이국적 분위기로 거실분위기를 업그레이드
                    </div>
                </div>
            </div>
            <div id="" class="fl_right conceptimg">
                <img src="/public_html/imgpro/img_provance02.jpg" border="0" alt="">
            </div>
        </div>
    </div>


    <div id="" class="box_design">
        <img src="/public_html/imgpro/img_provance03.jpg" border="0" alt="">
    </div>
    <!-- delivery ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- delivery ////////////////////////////// -->

</div>