<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/imgpro/img_settle201.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_settle2.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            A luxurious design seek like an independant piece of art
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/settle.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            coral in color
        </div>
        <div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/settle_1.jpg" border="0" alt="">
        </div>
	 <div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/settle_2.jpg" border="0" alt="">
        </div>
        <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_special.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>


<!--
    <div id="" class="box_colorfull">
        <div class="box_contents3">
            <div id="" class="fl_left">
                <div id="" class="txt_concept">
                    <div id="" class="txt_concept_div02">
                        settle Ⅱ design concept
                    </div>
                    <div id="" class="txt_concept_div03">
                        coral color
                    </div>
                    <div id="" class="txt_concept_div04">
                        공간 제한없이 다양한 공간 연출을 <br>만들어주는 디자인 소파
                    </div>
                </div>
            </div>
            <div id="" class="fl_right conceptimg">
                <img src="/public_html/imgpro/becky03.jpg" border="0" alt="">
            </div>
        </div>
    </div>
-->

    <div id="" class="box_design">
        <img src="/public_html/imgpro/dim-sofa-settle-200514.jpg" border="0" alt="">
    </div>

    <!-- delivery ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- delivery ////////////////////////////// -->
</div>