<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/imgpro/img_swing.jpg" border="0" alt="">
    </div>
    <div id="" class="" style="width:100%; height:252px; position:absolute; background-color:#fff5f3; display:block; z-index:-10; margin-top:-480px;">

    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_swing.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            Its design combines well with any interior decor
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/img_swing01.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            sky color
        </div>
        <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_special.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>


    <div id="" class="box_design" style="margin-top:180px;">
        <img src="/public_html/imgpro/img_swing02.jpg" border="0" alt="">
    </div>
    <div id="" class="" style="width:100%; height:560px; position:absolute; background-color:#fff5f3; display:block; z-index:-11; margin-top:-990px;">

    </div>

    <!-- delivery ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- delivery ////////////////////////////// -->
</div>