<html><head>
    <title>Management Program</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="stylesheet" type="text/css" href="/public_html/css/admin_style.css">
    <script src="/public_html/js/jquery-1.11.1.js"></script>
    <script src="/public_html/js/admin.js?<?=time()?>"></script>
    <link rel="stylesheet" href="/public_html/d_editor/css/editor.css" type="text/css" charset="utf-8"/>
    <script src="/public_html/d_editor/js/editor_loader.js" type="text/javascript" charset="utf-8"></script>
</head>
<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">
    <table width="100%" border="0" cellpadding="0" cellspacing="0" background="/public_html/images/tn_bg.gif">
        <tbody>
            <tr align="center" valign="top">
                <td width="10%" height="100%" align="left" style="padding:5px 10px;"><a href="#"><img src="/public_html/images/main_logo.png" width="80"></a></td>
                <td width="90%" align="left">
                    <table border="0" align="right" cellpadding="0" cellspacing="0">
                        <tbody><tr>
                            <td width="100" align="center" valign="top" background="/public_html/images/tn_bg.gif"><a href="javascript:admin_mode('admin');" class="tn"><img src="/public_html/images/dec_tn_02.gif" width="74" height="36" border="0"><br>게시판관리</a></td>
                            <td width="100" align="center" valign="top" background="/public_html/images/tn_bg.gif"><a href="javascript:admin_mode('visit');" class="tn"><img src="/public_html/images/dec_tn_01.gif" width="74" height="36" border="0"><br>접속자</a></td>
                        </tr>
                        </tbody></table>
                </td>
            </tr>
        </tbody>
    </table>
    <table width="100%" height="100%" cellpadding="0" cellspacing="0" border="0">
        <tbody>
            <tr valign="top">
                <td width="145" bgcolor="#999999">
                    <table width="100%" cellpadding="0" cellspacing="0" border="0">
                        <tbody>
                            <tr><td width="145" height="48" background="/public_html/images/sn_tlt_bg.gif" valign="bottom" align="center"></td></tr>
                            <tr><td height="14" valign="top"><img src="/public_html/images/spacer.gif" width="145" height="1" border="0"></td></tr>
    <?php if($admin_mode =="admin"){ ?>
                            <tr>
                                <td style="padding-left:7px; padding-right:10px;">
                                    <p><img src="/public_html/images/dec_sn.gif" width="9" height="11" hspace="3" vspace="5" border="0" align="absmiddle"> <a href="/admin/notice_list">헷세드공지</a><br></p>
                                </td>
                            </tr>
                            <tr>
                                <td style="padding-left:7px; padding-right:10px;">
                                    <p><img src="/public_html/images/dec_sn.gif" width="9" height="11" hspace="3" vspace="5" border="0" align="absmiddle"> <a href="/admin/notice_write">헷세드공지 등록</a><br></p>
                                </td>
                            </tr>
                            <tr>
                                <td style="padding-left:7px; padding-right:10px;">
                                    <p><img src="/public_html/images/dec_sn.gif" width="9" height="11" hspace="3" vspace="5" border="0" align="absmiddle"> <a href="/admin/customer_list">고객후기</a><br></p>
                                </td>
                            </tr>
                            <tr>
                                <td style="padding-left:7px; padding-right:10px;">
                                    <p><img src="/public_html/images/dec_sn.gif" width="9" height="11" hspace="3" vspace="5" border="0" align="absmiddle"> <a href="/admin/customer_write">고객후기 등록</a><br></p>
                                </td>
                            </tr>
                            <tr>
                                <td style="padding-left:7px; padding-right:10px;">
                                    <p><img src="/public_html/images/dec_sn.gif" width="9" height="11" hspace="3" vspace="5" border="0" align="absmiddle"> <a href="/admin/magajine_list">H_매거진</a><br></p>
                                </td>
                            </tr>
                            <tr>
                                <td style="padding-left:7px; padding-right:10px;">
                                    <p><img src="/public_html/images/dec_sn.gif" width="9" height="11" hspace="3" vspace="5" border="0" align="absmiddle"> <a href="/admin/magajine_write">H_매거진 등록</a><br></p>
                                </td>
                            </tr>
                            <tr>
                                <td style="padding-left:7px; padding-right:10px;">
                                    <p><img src="/public_html/images/dec_sn.gif" width="9" height="11" hspace="3" vspace="5" border="0" align="absmiddle"> <a href="/admin/qna_list">Q&amp;A</a><br></p>
                                </td>
                            </tr>
                            <tr>
                                <td style="padding-left:7px; padding-right:10px;">
                                    <p><img src="/public_html/images/dec_sn.gif" width="9" height="11" hspace="3" vspace="5" border="0" align="absmiddle"> <a href="/admin/qna_write">Q&amp;A 등록</a><br></p>
                                </td>
                            </tr>
    <?php }else{?>

                            <tr>
                                <td style="padding-left:7px; padding-right:10px;"> <p>
                                        <img src="/public_html/images/dec_sn.gif" width="9" height="11" hspace="3" vspace="5" border="0" align="absmiddle"> <a href="/admin/visit_list?mode=new">NEW 접속자</a><br>
                                </td>
                            </tr>
                            <tr>
                                <td style="padding-left:7px; padding-right:10px;"> <p>
                                        <img src="/public_html/images/dec_sn.gif" width="9" height="11" hspace="3" vspace="5" border="0" align="absmiddle"> <a href="/admin/visit_referer_list">유입 경로</a><br>
                                </td>
                            </tr>
                            <tr>
                                <td style="padding-left:7px; padding-right:10px;"> <p>
                                        <img src="/public_html/images/dec_sn.gif" width="9" height="11" hspace="3" vspace="5" border="0" align="absmiddle"> <a href="/admin/visit_list?mode=old2">접속자<br>(~2016년 1월 16일)</a><br>
                                </td>
                            </tr>
    <?php } ?>
                        </tbody>
                    </table>
                </td>
                <td bgcolor="#666666">
                    <table width="100%" cellpadding="0" cellspacing="0" border="0">
                        <tbody>
                            <tr>
                                <td width="20" height="42" rowspan="2" valign="top">
                                    <img src="/public_html/images/tn_loginbar_bg_left.gif" width="20" height="42" border="0"></td>
                                <td height="22" background="/public_html/images/tn_loginbar_bg_center.gif" align="right">
                                    <img src="/public_html/images/dec_login.png" width="16" height="16" border="0" align="absmiddle">
                                    <font color="#333333"><?php echo $user_id;?>님은 로그인 상태입니다 (<?php echo $user_name;?>)</font>
                                    <img src="/public_html/images/tn_loginbar_etc_line.gif" width="18" height="22" border="0" align="absmiddle">
                                    <img src="/public_html/images/dec_logout.gif" width="13" height="16" border="0" align="absmiddle">
                                    <a href="javascript:log_out();" class="logout">로그아웃</a>
                                    <img src="/public_html/images/tn_loginbar_bg_right.gif" width="20" height="22" border="0" align="absmiddle">
                                </td>
                            </tr>



