        <table width="100%" cellpadding="0" cellspacing="0" border="0">
            <tbody>
                <tr>
                    <td height="22" align="center" background="/public_html/images/tn_loginbar_bg_center.gif" class="fn">
                        COPYRIGHT 2010 BY Hassed Co.,Ltd. ALL RIGHTS RESERVED.
                    </td>
                    <td width="20"><img src="/public_html/images/tn_loginbar_bg_right.gif" width="20" height="22" border="0"></td>
                </tr>
            </tbody>
        </table>
    </body>
</html>