<div class="box_premium_e1">
    <div id="" class="fl_left">
        <div class="box_premium_div01">
            Premium latex and Original Ecsaine are<br>
            responsible for perfect sleep.
        </div>

        <div id="" class="box_premium_div02 txt_just">
            <span class="" style="font-weight:bold;">R.V latex mattress</span><br>

            .HASSED uses R.V latex from the Dutch company, which produces the highest quality of latex in Europe. It has a premium quality in terms of elasticity, durability and tensile strength, and produces eco-friendly latex that has passed all the strong environmental standards of the Netherlands. It is a premium latex produced by the Talaray process which can be produced only in the world's top three companies.
        </div>
    </div>


    <div id="" class="fl_right">
        <div id="" class="box_premium_div03">
            <span class="" style="font-weight:bold;">Features of Talalay method latex bed</span><br>

            <b>01</b>  Supporting human body load most naturally by the interlocking action of tight pinhole.<br>
            <b>02</b>  Air-Cell does not interfere with the sleep of the neighboring person by acting as <br>&nbsp;&nbsp;&nbsp;&nbsp;a natural spring.<br>
            <b>03</b>  Very hygienic because it does not generate dust from the inside even <br>&nbsp;&nbsp;&nbsp;&nbsp;if it rides on a mattress.<br>
            <b>04</b>  Cool in summer and warm in winter due to excellent air permeability by air-cell.<br>
            <b>05</b>  Offering a comfortable sleep with elasticity and durability that boasts <br>&nbsp;&nbsp;&nbsp;&nbsp;the highest quality in Europe.
        </div>
    </div>

</div>