<div class="box_special">
    <div class="box_special_div01">
        Feel unrivalled quality with the numerous advantages of <br>.HASSED
    </div>

    <div class="box_special_div02">
        <a href="/ecsaine/strongpoint">&nbsp;&nbsp;&nbsp;&nbsp;+ &nbsp;&nbsp;Learn more</a>
    </div>

    <div class="box_special_div03">
        <div id="" class="left_num" style="float:left;">
            <ul>
                <li ><b>01</b></li>
                <li ><b>02</b></li>
                <li ><b>03</b></li>
                <li ><b>04</b></li>
                <li ><b>05</b></li>
                <li ><b>06</b></li>
            </ul>
        </div>
        <div class="right_txt">
            <ul>
                <li>Soft and attractive touch like baby skin</li>
                <li>Human body affinity without harmful chemicals and environment hormones</li>
                <li>Durability and superior properties over leather</li>
                <li>Excellent air permeability that is cool in summer and warm in winter</li>
                <li>Structure where no dust mite inhabits</li>
                <li>Prevention of atopy, allergy, rhinitis and asthma from dust spillage</li>
            </ul>
        </div>
    </div>
    <div id="" class="box_special_div04">
        <div id="" class="left_num" style="float:left;">
            <ul>
                <li><b>07</b></li>
                <li><b>08</b></li>
                <li><b>09</b></li>
                <li><b>10</b></li>
                <li><b>11</b></li>
                <li><b>12</b></li>
            </ul>
        </div>
        <div id="" class="right_txt">
            <ul>
                <li>Color development to add a more luxurious appearance to natural light</li>
                <li>Convenient washing resistance for easy management of household contamination </li>
                <li>Strong resilience to scratching of pets</li>
                <li>Unique beauty of high-quality luxury materials </li>
                <li>Excellent light fastness with no color fade under direct sunshine</li>
                <li>Lifestyle-optimized ergonomic design 13, 14 ... </li>
            </ul>
        </div>
    </div>
</div>