<!doctype html>
<html>
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="title" content="친환경 소파&침대 .hassed">
    <meta name="Keywords" content="친환경 소파&침대 전문브랜드, 오리지널 엑센느, 제품소개 및 매장안내, 고객후기">
    <meta name="description" content="친환경 소파&침대 전문브랜드, 오리지널 엑센느, 제품소개 및 매장안내, 고객후기">

    <!-- 연관검색어 시작-->
    <script type="application/ld+json">
 {
  "@context": "http://schema.org",
  "@type": "Person",
  "name": "Hassed",
  "url": "http://www.hassed.co.kr",
  "sameAs": [
    "https://www.instagram.com/hassed_kr",
    "http://blog.naver.com/hassed_kr"
  ]
 }</script>
    <!-- 연관검색어 끝-->

    <link rel="SHORTCUT ICON" href="/public_html/img/hassed.png"/>
    <title>.HASSED</title>
    <link rel="stylesheet" type="text/css" href="/public_html/css_e/reset_style.css" />
    <link rel="stylesheet" type="text/css" href="/public_html/css_e/default_hassed_2017.css" />
    <link rel="stylesheet" type="text/css" href="/public_html/css_e/menuf_2017.css" />
    <link rel="stylesheet" type="text/css" href="/public_html/css_e/main_2017.css" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script type="text/javascript" src="/public_html/js/topmenu_2017.js"></script>

    <script type="text/javascript">
        function layer_open(){
            document.getElementById("youtubeframe").style.display='';
        }

        function layer_close(){
            document.getElementById("youtubeframe").style.display='none';
        }
        function layer_open2()
        {
            document.getElementById("youtubeframe2").style.display='';
        }

        function layer_close2()
        {
            document.getElementById("youtubeframe2").style.display='none';
            stopVideo();
        }

    </script>
    <SCRIPT LANGUAGE="JavaSCRIPT">
        //영문 준비중입니다
        function windOPsorry()
        {
            noticeWindow  =  window.open("sorry.html","ECSAINE",'left=200, top=40, width=360, height=240, resizable=no, scrollbars=no, status=no location=no ');
        }
    </SCRIPT>
</head>
<body ><!-- onload="javascript:windOPrenewal();" -->
<div id="" class="wrap">
    <div id="" class="wrap_top">
        <div id="sns_frame" class="bar_visible">
            <div id="" class="wrap_top_sns">
                <div id="" class="box_sns">
                    <ul>
                        <li><a href="/common/set_lang"><img src="/public_html/img_e/bt_kor.png" border="0" alt="준비중입니다"></a></li>
                        <li><a href="http://cafe.naver.com/hassedhouse" target="_blink"><img src="/public_html/img_e/bt_cafe.png" border="0" alt=""></a></li>
                        <li><a href="https://www.instagram.com/hassed_kr/" target="_blink"><img src="/public_html/img_e/bt_instar.png" border="0" alt=""></a></li>
                        <li><a href="http://blog.naver.com/hassed_kr" target="_blink"><img src="/public_html/img_e/bt_blog.png" border="0" alt=""></a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div id="" class="top_menubar">
            <div id="" class="wrap_menu">
                <div id="" class="box_logo">
                    <a href="/"><img src="/public_html/img_e/logo_hassed.png" border="0" alt=""></a>
                </div>
                <div id="" class="box_menu">
                    <!-- topmenu ////////////////////////////// -->
                    <div id="main_header" class="">
                        <nav id="main_gnb">
                            <ul>
                                <li id="gnb01"><a href="/about">ABOUT US</a></li>
                                <li id="gnb02"><a href="/ecsaine">ECSAINE</a></li>
                                <li id="gnb03"><a href="/product">PRODUCT</a></li>
                                <li id="gnb04"><a href="/gallery">GALLERY</a></li>
                                <li id="gnb05"><a href="/noticep">NOTICE</a></li>
                            </ul>
                        </nav>
                        <!-- //회사소개 매뉴 -->
                        <div id="sub_gnb01">
                            <ul>
                                <li><a href="/about/company">company</a></li>
                                <li><a href="/about/brand">brandstory</a></li>
                                <li><a href="/about/ceo">greeting</a></li>
                                <li><a href="/about/shop_info">store</a></li>
                            </ul>
                        </div>

                        <!-- //소재 매뉴 -->

                        <div id="sub_gnb02">
                            <ul>
                                <li><a href="/ecsaine/material">material </a></li>
                                <li><a href="/ecsaine/strongpoint">Features </a></li>
                                <li><a href="/ecsaine/maintain">management</a></li>

                            </ul>
                        </div>

                        <!-- //제품소개 매뉴 -->
                        <div id="sub_gnb03">
                            <ul>
                                <li><a href="/product/detail_view?code=becky">BECKY</a></li>
                                <li><a href="/product/detail_view?code=arriba">ARRIBA</a></li>
                                <li><a href="/product/detail_view?code=calix">CALIX</a></li>
                                <li><a href="/product/detail_view?code=ailish">AILISH</a></li>
                                <li><a href="/product/detail_view?code=whistle">WHISTLE</a></li>
                                <li><a href="/product/detail_view?code=besso">BESSO</a></li>
                                <li><a href="/product/detail_view?code=floria">FLORIA</a></li>
                                <li><a href="/product/detail_view?code=francis">FRANCIS</a></li>
                                <li><a href="/product/detail_view?code=bambi">BAMBI</a></li>
                                <li><a href="/product/detail_view?code=adela">ADELA</a></li>
                                <li><a href="/product/detail_view?code=esther">ESTHER</a></li>
                                <li><a href="/product/detail_view?code=provence">PROVENCE</a></li>
                                <li><a href="/product/detail_view?code=crane">CRANE</a></li>
                                <li><a href="/product/detail_view?code=amore">AMORE</a></li>
                                <li><a href="/product/detail_view?code=twinsofa">TWINSOFA</a></li>
                                <li><a href="/product/detail_view?code=swingchair">SWINGCHAIR</a></li>
                            </ul>
                        </div>

                        <!-- //갤러리 매뉴 -->
                        <div id="sub_gnb04">
                            <ul>
                                <li><a href="/gallery/customerWrite">Review</a></li>
                                <li><a href="/gallery/hmagajine">H_magazine</a></li>
                                <!-- <li><a href="ehaboard05.asp">영상자료</a></li> -->
                            </ul>
                        </div>

                        <!-- //고객지원 매뉴 -->
                        <div id="sub_gnb05">
                            <ul>
                                <li><a href="#">Notice</a></li>
                                <li><a href="#">F&nbsp;A&nbsp;Q</a></li>
                                <li><a href="#">Q&nbsp;&&nbsp;A</a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- topmenu ////////////////////////////// -->
                </div>
            </div>
        </div>
    </div>
</div>

