
<div id="" class="box_delivery" style="margin-top:110px;">
    <div id="" class="box_delivery_div01">
        <!-- <img src="/public_html/img/delivery01.png" border="0" alt=""> -->
        <div id="" class="text01">
            DELIVERY INFORMATION<br>
            &CAUTION
        </div>
        <div id="" class="text02">
            Shipping Information
        </div>
        <div id="" class="text03">
            Customer Center <br>82-2-401-5073
        </div>

        <!-- <img src="/public_html/img/delivery03.png" border="0" alt=""> -->
    </div>
    <div id="" class="box_delivery_div02">
        <div id="" class="text07">
            01 Delivery time
        </div>

        <div id="" class="text08">
            It takes an average of 2~3 weeks after purchase. <br>
            <span class="textbold">※ If the number of purchasing customers surges, <br>&nbsp;&nbsp;&nbsp;&nbsp;the delivery period may be extended. </span>
        </div>

        <div id="" class="text07">
            02 Shipping instruction
        </div>
        <div id="" class="text08">
            Shipping Schedule: We will guide you <br>within 7 days after purchase of .HASSED <br>
            Shipping time: We will inform you the day before shipping.<br>
            <span class="textbold">※ It will not be proceeded on every Saturday and Sunday. </span>
        </div>

        <div id="" class="text07">
            03 Shipping area
        </div>
        <div id="" class="text08">
            It is free shipping nationwide.<br>
            However, customer shall be responsible for ocean freight charge and airfare.<br>
            ※ The airfare includes the fare to the destination after arrival at the local airport.

        </div>

        <div id="" class="text07">
            04 Shipping service
        </div>
        <div id="" class="text08">
            As for product transfer, .HASSED’s regular staff is in charge of installation.
        </div>

        <div id="" class="text07">
            Precaution
        </div>
        <div id="" class="text08">
            - Please arrange things and furniture before installation prior to shipping.<br>
            - It is the customer's responsibility to pay for the special items that require special equipment <br>&nbsp;&nbsp;such as a ladder and a sky car.<br>
            - We do not collect the furniture the customer uses.
        </div>
        <!-- <img src="/public_html/img/delivery02.png" border="0" alt="">
        <img src="/public_html/img/delivery04.png" border="0" alt=""> -->
        <div id="" class="img_onestop">
            <img src="/public_html/img/img_onestop.png" border="0" alt="">
        </div>
    </div>

</div>

<div id="" class="box_delivery" style="margin-top:13px;">
    <div id="" class="box_delivery_div03">
        <div id="" class="text04">
            AFTER-SALES SERVICE
        </div>
        <div id="" class="text05">
            A/S regulations
        </div>
        <div id="" class="text06">
            Customer Center <br>82-2-401-5073
        </div>
    </div>
    <div id="" class="box_delivery_div04">
        <div id="" class="text07">
            A/S responsibility
        </div>
        <div id="" class="text08" style="width:680px;">
            .HASSED is not a general distribution brand that purchases and sells products from a third party, such as subcontractors, intermediate distributors / importers with only shop. In case of general distribution brand, if there is any defects or return of the product, there is a risk to find the 3rd party vendor who takes responsibility for AS.

        </div>
        <div id="" class="text07" >
            Free AS
        </div>
        <div id="" class="text08" style="width:680px;">
            We are responsible for any fault or defects in the interior materials that cannot be seen directly by our customers and for the outer material, free of charge until our customers think that it is used up.
        </div>

        <div id="" class="text07">
            Fee-paid AS
        </div>
        <div id="" class="text08" style="width:680px;">
            For a fee-paid AS caused by customer’s carelessness, additional material and shipping costs shall be imposed only. (For reference, unlike general distribution brand that collects and claims all expenses for purchase and then sales settlement basis, the maker brand has the structural advantage of handling ordinary expenses such as labor charge and fees at their own fixed costs.)
        </div>
    </div>
</div>
