<!-- video popup open  -->
<script type="text/javascript" src="/public_html/js/open_video.js"></script>
<!-- mySlider script file -->
<script src="/public_html/js/myslider.js"></script>
<script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
<!-- mySlider css file -->
<link rel="stylesheet" type="text/css" href="/public_html/css/myslider.css" />
<input type="hidden" name="<?=$this->security->get_csrf_token_name()?>" value="<?=$this->security->get_csrf_hash()?>"/>
<div id="" class="wrap_middle">
    <div class="main_img">
        <div class="myslider">
            <div id='layerA' class="slider_img01"><img src="/public_html/img_e/main_img01.jpg" border="0" alt=""></div>
            <div class="slider_img02"><img src="/public_html/img_e/main_img02.jpg" border="0" alt=""></div>
            <div class="slider_img03"><img src="/public_html/img_e/main_img03.jpg" border="0" alt=""></div>
        </div>
    </div>
    <div id="bx-point">
        <a href="#a"><div id="bt_point01"><img src="/public_html/img_e/pagepoint.png" /></div></a>
        <a href="#b"><div id="bt_point02"><img src="/public_html/img_e/pagepoint.png" /></div></a>
        <a href="#c"><div id="bt_point03"><img src="/public_html/img_e/pagepoint.png" /></div></a>
    </div>

    <div id="" class="reviewnews">
        <div id="" class="box_news">
            <div id="" class="box_news_inline">
                <div class="mysliderb">
                    <div class="sliderb_img02"><a href="/notice/notice"><img src="public_html/img/news_img180830-2.jpg" border="0" alt=""></a></div>
			<div class="sliderb_img03"><a href="/notice/notice"><img src="public_html/img/news_img180830-3.jpg" border="0" alt=""></a></div>
			<div class="sliderb_img04"><a href="/notice/notice"><img src="public_html/img/news_img180830-4.jpg" border="0" alt=""></a></div>
			<div class="sliderb_img05"><a href="/notice/notice"><img src="public_html/img/news_img190219.jpg" border="0" alt=""></a></div>
			<div class="sliderb_img01"><a href="/notice/notice"><img src="public_html/img/news_img180830-1.jpg" border="0" alt=""></a></div>
                </div>
                <div id="" class="title_news txt_white">
                    news
                </div>
                <div id="bx-point-news">

                    <a href="#d"><div id="bt_pointb01"><img src="/public_html/img_e/pagepoint.png" /></div></a>
                    <a href="#e"><div id="bt_pointb02"><img src="/public_html/img_e/pagepoint.png" /></div></a>
                    <a href="#f"><div id="bt_pointb03"><img src="/public_html/img_e/pagepoint.png" /></div></a>
                    <a href="#g"><div id="bt_pointb04"><img src="/public_html/img_e/pagepoint.png" /></div></a>
                    <a href="#f"><div id="bt_pointb03"><img src="/public_html/img_e/pagepoint.png" /></div></a>
                </div>
            </div>
        </div>
        <div id="" class="box_review bgcolor-ivory">
            <div id="" class="title_sub01 txt_darkgray">
                review
            </div>
            <div id="" class="box_review_2d">
                <div id="" class="mysliderc">
                    <div id="slideA" class="review_slideA">
                        <ul>
                            <li><a href="/gallery/customer"><img src="/public_html/img_e/review_img01.jpg" border="0" alt=""></a></li>
                            <li><a href="/gallery/customer"><img src="/public_html/img_e/review_img02.jpg" border="0" alt=""></a></li>
                        </ul>
                    </div>
                    <div id="slideB" class="review_slideB">
                        <ul>
                            <li><a href="/gallery/customer"><img src="/public_html/img_e/review_img03.jpg" border="0" alt=""></a></li>
                            <li><a href="/gallery/customer"><img src="/public_html/img_e/review_img04.jpg" border="0" alt=""></a></li>
                        </ul>
                    </div>
                    <div id="slideC" class="review_slideC">
                        <ul>
                            <li><a href="/gallery/customer"><img src="/public_html/img_e/review_img05.jpg" border="0" alt=""></a></li>
                            <li><a href="/gallery/customer"><img src="/public_html/img_e/review_img06.jpg" border="0" alt=""></a></li>
                        </ul>
                    </div>

                </div>
            </div>
            <div id="" class="box_7years">
                9 years of customer reviews
            </div>
            <div id="bx-point-review">
                <a href="#g"><div id="bt_pointc01"><img src="/public_html/img_e/pagepoint.png" /></div></a>
                <a href="#h"><div id="bt_pointc02"><img src="/public_html/img_e/pagepoint.png" /></div></a>
                <a href="#i"><div id="bt_pointc03"><img src="/public_html/img_e/pagepoint.png" /></div></a>
            </div>
        </div>

    </div>
    <div id="" class="movie bgcolor-ivory">
        <div id="" class="title_movie">
            <img src="/public_html/img_e/title_movie.png" border="0" alt="">
        </div>
        <div id="wrap_mainvideo" class="mainvideo">
            <ul>
                <a href="javascript:layer_open();"><img src="/public_html/img_e/bt_youtube.jpg" border="0" alt=""></a>
            </ul>
        </div>
    </div>

    <div id="" class="product_store">
        <div id="" class="product_store_left">
            <img src="/public_html/img_e/title_product.jpg" border="0" alt="">
            <div id="" class="box_product">
                <div id="" class="box_product_in01">
                    <a href="/product/detail_view?code=francis"><img src="/public_html/img_e/img_product_sofa.jpg" border="0" alt=""></a>
                </div>
                <div id="" class="box_product_in02">
                    <a href="/product/detail_view?code=ailish"><img src="/public_html/img_e/img_product_bed.jpg" border="0" alt=""></a>
                </div>
            </div>

        </div>
        <div id="" class="product_store_right">
            <img src="/public_html/img_e/title_store.jpg" border="0" alt="">
            <div id="" class="box_store">
                <div id="" class="box_store_in01">
                    <a href="/about/shop_info?location=point_store"><img src="/public_html/img_e/bt_roadshop.jpg" border="0" alt=""></a>
                </div>
                <div id="" class="box_store_in02">
                    <a href="/about/shop_info?location=point_depart"><img src="/public_html/img_e/bt_depart.jpg" border="0" alt=""></a>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="vimeoframe" class="" style="display:none;"><a href="javascript:layer_close();"><div id="" class="popupdivbg"></div></a>
    <div id="" class="popupdiv">
        <iframe id="player" src="https://player.vimeo.com/video/208591714" width="1000" height="560" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
    </div>
</div>