<div class="box_special">
    <div class="box_special_title">
        헷세드의 무수한 장점과 <br>
        따라올 수 없는 퀄리티를 <br>
        직접 느껴보세요!
    </div>  

    <div class="box_special_txt">
        <b>01</b> 아기의 맨살처럼 부드럽고 매혹적인 촉감<br>
        <b>02</b> 유해화학물질과 환경호르몬 걱정 없는 인체친화성<br>
        <b>03</b> 가죽보다 뛰어난 내구성과 우수한 물성<br>
        <b>04</b> 여름엔 시원하고 겨울엔 따스한 느낌의 우수한 통기성<br>
        <b>05</b> 집먼지진드기가 서식할 수 없는 구조<br>
        <b>06</b> 먼지날림이 없어 아토피, 알레르기, 비염, 천식 예방<br>
		<b>07</b> 자연채광에서 더욱 고급스러운 자태를 더하는 색상발현력<br>
        <b>08</b> 생활 오염을 쉽게 관리할 수 있는 편리한 내세척성<br>
        <b>09</b> 반려동물의 스크래치에 강한 형태 복원력<br>
        <b>10</b> 나만이 소유할 수 있는 고품격 명품 소재의 아름다움<br>
        <b>11</b> 직사광선에도 빛 바램이 없는 우수한 일광견뢰도<br>
        <b>12</b> 라이프스타일에 최적화된 인체공학적 디자인   13, 14...
    </div>
	
	 <div class="box_special_link">
        <a href="/ecsaine/strongpoint">&nbsp;&nbsp;&nbsp;&nbsp;+&nbsp;자세히&nbsp;&nbsp;보기</a>
    </div>

</div>