            <div id="" class="wrap_bottom">
                <div id="" class="wrap_bottom_menu">
                    <ul>
                        <li><a href="/" class="bottom_menu01">logo</a></li>
                        <li><a href="/other/b2b" class="bottom_menu02">B2B</a></li>
                        <li><a href="/other/recruit" class="bottom_menu03">Recruit</a></li>
                        <li><a href="/other/law" class="bottom_menu04">law</a></li>
                        <li><a href="/other/privacy" class="bottom_menu05">Privacy</a></li>
                        <li><a href="/notice/faq" class="bottom_menu06">faq</a></li>
                        <li class="wrap_bottom_space"></li>
                        <li><a href="http://cafe.naver.com/hassedhouse" target="_blink" class="bottom_menu07">cafe</a></li>
                        <li><a href="https://www.instagram.com/hassed_kr/" target="_blink" class="bottom_menu08">instar</a></li>
                        <li><a href="http://blog.naver.com/hassed_kr" target="_blink" class="bottom_menu09">blog</a></li>
                    </ul>
                </div>
                <div id="" class="wrap_copyright">
                서울특별시 송파구 중대로 271 헷세드빌딩 (주)헷세드  &nbsp;&nbsp;&nbsp;&nbsp;  대표이사 김기욱 &nbsp;&nbsp;&nbsp;&nbsp; 사업자등록번호 132-86-14687  <br>
		T : <span style="font-weight:bold; display:inline-block;">02 401 5073</span>   &nbsp;&nbsp; F : <span style="font-weight:bold; display:inline-block;">02 401 5074</span>  &nbsp;&nbsp; E :  hassed_kr@naver.com  
		 &nbsp;&nbsp;&nbsp;&nbsp; ⓒ 2010 HASSED all right reserved
                </div>
            </div>
        </div>
            <!-- Password 입력 팝업 -->
            <div id="in_pass" class="popup_pw popup_box" style="display:none;">
                <form name="passwd" id="passwd" method = "post">
                    <input type="hidden" name="ck_lock" id="ck_lock">
                    <input type="hidden" name="pass_uri" id="pass_uri">
                    <input type="hidden" name="pass_mode" id="pass_mode">
                    <img src="/public_html/images/bg/in_pass_01.png" title="Password" style="vertical-align:top;">
                    <div style="margin:0 20px 10px;overflow:hidden;">
                        <div class="box_pw">비밀번호 &gt;</div>
                        <input type="password" size="12" name="pw" id="pw" style="float:left;">
                    </div>
                    <div class="checkbt">
                        <input type="button" class="btn_pw" title="확인" onclick="CheckPW();">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <input type="button" class="btn_cancel" title="취소" onclick="cancel();">
                    </div>
                </form>
            </div>
            <!-- Password 입력 팝업 // -->

            <script>
//            var tmpUser = navigator.userAgent;
//
//            if (tmpUser.indexOf("iPhone") > 0 || tmpUser.indexOf("iPad") > 0 || tmpUser.indexOf("Android ") > 0 || tmpUser.indexOf("BlackBerry ") > 0 || tmpUser.indexOf("Windows CE ") > 0 || tmpUser.indexOf("LG ") > 0 || tmpUser.indexOf("MOT ") > 0 || tmpUser.indexOf("SAMSUNG ") > 0 || tmpUser.indexOf("SonyEricsson ") > 0 ){
//
//                var src="PageLog.asp?mode=m";
//            }else{
//                var src="PageLog.asp?mode=pc";
//            }
//
//            $("#PageLog").prop("src",src);

        </script>
        <!-- 공통 적용 스크립트 , 모든 페이지에 노출되도록 설치. 단 전환페이지 설정값보다 항상 하단에 위치해야함 -->
        <script type="text/javascript" src="http://wcs.naver.net/wcslog.js"></script>
        <script type="text/javascript">
            if (!wcs_add) var wcs_add={};
            wcs_add["wa"] = "s_4629d0560bcd";
            if (!_nasa) var _nasa={};
            wcs.inflow("hassed.kr");
            wcs_do(_nasa);
        </script>
        <!-- AceCounter Log Gathering Script V.7.5.2013010701 -->
        <script language='javascript'>
            var _AceGID=(function(){var Inf=['gtc13.acecounter.com','8080','BS2A40389765512','AW','0','NaPm,Ncisy','ALL','0']; var _CI=(!_AceGID)?[]:_AceGID.val;var _N=0;var _T=new Image(0,0);if(_CI.join('.').indexOf(Inf[3])<0){ _T.src =( location.protocol=="https:"?"https://"+Inf[0]:"http://"+Inf[0]+":"+Inf[1]) +'/?cookie'; _CI.push(Inf);  _N=_CI.length; } return {o: _N,val:_CI}; })();
            var _AceCounter=(function(){var G=_AceGID;if(G.o!=0){var _A=G.val[G.o-1];var _G=( _A[0]).substr(0,_A[0].indexOf('.'));var _C=(_A[7]!='0')?(_A[2]):_A[3];	var _U=( _A[5]).replace(/\,/g,'_');var _S=((['<scr','ipt','type="text/javascr','ipt"></scr','ipt>']).join('')).replace('tt','t src="'+location.protocol+ '//cr.acecounter.com/Web/AceCounter_'+_C+'.js?gc='+_A[2]+'&py='+_A[4]+'&gd='+_G+'&gp='+_A[1]+'&up='+_U+'&rd='+(new Date().getTime())+'" t');document.writeln(_S); return _S;} })();
        </script>
        <noscript><img src='http://gtc13.acecounter.com:8080/?uid=BS2A40389765512&je=n&' border='0' width='0' height='0' alt=''></noscript>
    <!-- AceCounter Log Gathering Script End -->
    </body>
</html>