            <div id="" class="wrap_bottom">
                <div id="" class="wrap_bottom_menu">
                    <ul>
                        <!--<li><a href="/" class="bottom_menu01">logo</a></li>-->
                        <li><a href="/other/b2b" class="bottom_menu02">B2B</a></li>
                        <li><a href="/other/recruit" class="bottom_menu03">채용</a></li>
                        <li><a href="/other/law" class="bottom_menu04">법률성명</a></li>
                        <li><a href="/other/privacy" class="bottom_menu05">개인정보보호정책</a></li>
                        <li><a href="/notice/faq" class="bottom_menu06">faq</a></li>
                    </ul>
                </div>
                <div id="" class="wrap_copyright">
                서울특별시 송파구 중대로 271 헷세드빌딩 <br>
		(주)헷세드  &nbsp;&nbsp;&nbsp;&nbsp;  사업자등록번호 132-86-14687  &nbsp;&nbsp;&nbsp;&nbsp;대표이사 김기욱<br>
		T : <span style="font-weight:bold; display:inline-block;">02 401 5073</span>   &nbsp;&nbsp; F : <span style="font-weight:bold; display:inline-block;">02 401 5074</span>  &nbsp;&nbsp; E :  hassed_kr@naver.com  
		 &nbsp;&nbsp;&nbsp;&nbsp; ⓒ 2010 HASSED all right reserved
                </div>

		<div class="wrap_bottom_sns">
		    <ul>
                        <li><a href="http://cafe.naver.com/hassedhouse" target="_blink"><img src="/public_html/img_n2021/iconbtn/iconx30-navercafe-w.png" border="0" alt=""></a></li>
			<li class="wrap_bottom_space"></li>
                        <li><a href="https://www.instagram.com/hassed_official/" target="_blink"><img src="/public_html/img_n2021/iconbtn/iconx30-instagram-w.png" border="0" alt=""></a></li>
			<li class="wrap_bottom_space"></li>
                        <li><a href="http://blog.naver.com/hassed_kr" target="_blink"><img src="/public_html/img_n2021/iconbtn/iconx30-naverbloge-w.png" border="0" alt=""></a></li>
			<li class="wrap_bottom_space"></li>
			<li><a href="http://pf.kakao.com/_DAxaJT/chat" target="_blink"><img src="/public_html/img_n2021/iconbtn/iconx30-kakaotalk-w.png" border="0" alt=""></a></li>
		    </ul>
		 </div>

            </div>
        </div>
           
    </body>
</html>