<!doctype html>
<html>
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="title" content="친환경 소파&침대 .hassed">
    <meta name="Keywords" content="친환경 소파&침대 전문브랜드, 오리지널 엑센느, 제품소개 및 매장안내, 고객후기">
    <meta name="description" content="친환경 소파&침대 전문브랜드, 오리지널 엑센느, 제품소개 및 매장안내, 고객후기">
        

<!-- 연관검색어 시작-->
<script type="application/ld+json">
 {
  "@context": "http://schema.org",
  "@type": "Person",
  "name": "Hassed",
  "url": "http://www.hassed.co.kr",
  "sameAs": [
    "https://www.instagram.com/hassed_official/",
    "http://blog.naver.com/hassed_kr"
  ]
 }</script>
<!-- 연관검색어 끝-->

	<title>.HASSED</title>

	<!-- ICON -->
	<link rel="SHORTCUT ICON" href="/public_html/img/hassed.png"/>

	<!--css -->
	<link rel="stylesheet" type="text/css" href="<?php echo CSS_DIR; ?>/default_hassed_set_2021.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo CSS_DIR; ?>/menu_2021.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo CSS_DIR; ?>/main_2021.css" />
	<link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
	<script type="text/javascript"  src="<?php echo JS_DIR; ?>/jquery-1.11.1.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
	<script type="text/javascript" src="<?php echo JS_DIR; ?>/topmenu_2021.js"></script>
	<script type="text/javascript" src="<?php echo JS_DIR; ?>/dim-action.js"></script>





    <script type="text/javascript">

        //사이트 리뉴얼 중입니다.
        function windOPrenewal(){
            noticeWindow  =  window.open("renewal.html","ECSAINE",'left=200, top=200, width=300, height=370, resizable=no, scrollbars=no, status=no location=no ');
        }

        function closewin() {
            noticeWindow.close();   // Closes the new window
        }

        function set_lang(){
            $.ajax({
                type : "POST",
                url : "/ajax/member/set_lang",
                data: {
                    csrf_token: $('input[name=csrf_token]').val(),
                },
                cache : false,
                success : function(result) {
                    if(result == "OK"){
                        location.reload();
                    }else{
                        alert("다시 시도해 주세요.");
                    }
                },
                error : function() {
                    alert("다시 시도해 주세요.");
                }
            });
        }
    </script>



</head>
<body ><!-- onload="javascript:windOPrenewal();" -->
<input type="hidden" name="<?=$this->security->get_csrf_token_name()?>" value="<?=$this->security->get_csrf_hash()?>"/>
<div id="blind"></div>
<div id="" class="wrap">
    <div id="" class="wrap_top">
        <div id="sns_frame" class="">
            <div id="" class="wrap_top_sns">
                <div id="" class="box_sns">
                    <ul>
                        <li><a href="http://cafe.naver.com/hassedhouse" target="_blink"><img src="/public_html/img_n2021/iconbtn/iconx30-navercafe.png" border="0" alt=""></a></li>
                        <li><a href="https://www.instagram.com/hassed_official/" target="_blink"><img src="/public_html/img_n2021/iconbtn/iconx30-instagram.png" border="0" alt=""></a></li>
                        <li><a href="http://blog.naver.com/hassed_kr" target="_blink"><img src="/public_html/img_n2021/iconbtn/iconx30-naverbloge.png" border="0" alt=""></a></li>
			<li><a href="http://pf.kakao.com/_DAxaJT/chat" target="_blink"><img src="/public_html/img_n2021/iconbtn/iconx30-kakaotalk.png" border="0" alt=""></a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div id="" class="top_menubar">
            <div id="" class="wrap_menu">
                <div id="" class="box_logo">
                    <a href="/"><img src="/public_html/img_n2021/logo-hassed-7000bx.png" border="0" alt=""></a>
                </div>

                <div id="" class="box_menu">
                    <!-- topmenu ////////////////////////////// -->
                    <div id="main_header" class="">
                        <nav id="main_gnb">
                            <ul>
                                <li id="gnb01"><a href="/about/company">ABOUT US</a></li>
				<li id="gnb02"><a href="#">WHY SENSATION</a></li>
                                <li id="gnb03"><a href="/ecsaine/material">ECSAINE</a></li>
                                <li id="gnb04"><a href="/product">PRODUCT</a></li>
                                <li id="gnb05"><a href="/gallery/customer">GALLERY</a></li>
                                <li id="gnb06"><a href="/notice/notice">NOTICE</a></li>
                            </ul>
                        </nav>
                        <!-- //회사소개 매뉴 -->
                        <div id="sub_gnb01">
                            <ul>
                                <li><a href="/about/company">회사소개</a></li>
                                <li><a href="/about/brand">브랜드스토리</a></li>
                                <li><a href="/about/ceo">CEO 인사말</a></li>
                                <li><a href="/about/shop_info">매장정보</a></li>
                            </ul>
                        </div>
			<!-- //센세이션 -->
                        <div id="sub_gnb02">
                        </div>
                        <!-- //소재 매뉴 -->
                        <div id="sub_gnb03">
                            <ul>
                                <li><a href="/ecsaine/material">엑센느 소재</a></li>
                                <li><a href="/ecsaine/strongpoint">엑센느 특장점</a></li>
                                <li><a href="/ecsaine/maintain">엑센느 관리</a></li>
                            </ul>
                        </div>
                        <!-- //제품소개 매뉴 -->
                        <div id="sub_gnb04">
                            <ul>
                                <li><a href="/product">SOFA / 소파</a></li>
                                <li><a href="/product/detail_view?code=arriba">BED / 침대</a></li>
                            </ul>
                        </div>
                        <!-- //갤러리 매뉴 -->
                        <div id="sub_gnb05">
                            <ul>
                                <li><a href="/gallery/customer">고객후기</a></li>
                                <li><a href="/gallery/hmagajine">H_매거진</a></li>
                                <!-- <li><a href="haboard05.asp">영상자료</a></li> -->
                            </ul>
                        </div>
                        <!-- //고객지원 매뉴 -->
                        <div id="sub_gnb06">
                            <ul>
                                <li><a href="/notice/notice">공지사항</a></li>
                                <li><a href="/notice/faq">F&nbsp;A&nbsp;Q</a></li>
                                <li><a href="/notice/qna">Q&nbsp;&&nbsp;A</a></li>
                            </ul>
                        </div>
                    </div>
                    <!-- topmenu ////////////////////////////// -->
                </div>
            </div>
        </div>
    </div>

