
<div class="mainmovie">
<video d="video" width="100%" autoplay muted loop>
  <source src="/public_html/movie/site-main-20210427-2.mp4" type="video/mp4">
  Your browser does not support the video tag.
</video> 
</div>

<div  style="width:100%; height:640px; padding:0px 28px; margin-top: 100px; display:block; /*background-image:url('/public_html/img_n2021/index_page/logo-mask-bottom.png');
    background-repeat:no-repeat;
    background-position:-1px 428px;*/">
	<ul>
		<li style="width:602px; height:370px; float:left; display:block;">
			<a href="#" ><div id="toraybook" onmouseover="changeOpacity8()" onmouseout="changeOpacity7()">
				<ul>
					<li style="width:602px; height:100px; text-align: center; margin-top:0px;"><img src="/public_html/img_n2021/index_page/line-height.jpg"></li>
				</ul>
				<ul>
					<li style="width:602px; height:40px; text-align: center; font-size:16px; color:#535353;">campany</li>
				</ul>
				<ul style="">
					<li><div class="" style="width:602px; height:310px; overflow:hidden; border:solid 1px #777;">
						<a href="#" ><div class="" id="rand_pos1" style="width:602px; height:310px;  position:relative;  ">
						<img src="/public_html/img_n2021/index_page/book-bic.jpg" border="0" alt=""></div>
						<div id="test111" style="width:602px; height:300px; position:relative; left:0px; top:-310px; opacity:0.85;" ><img src="/public_html/img_n2021/index_page/logo-mask-white.png" border="0" alt=""></div></a>
					</div></li>
				</ul>
				<ul>
					<li style="width:602px; height:6px; text-align: center; border-bottom:solid 1px #777;"></li>
				</ul>
			</div></a>
		</li>
		<li style="width:602px; height:370px; float:left; display:block; margin:0 18px;">
			<a href="#" ><div id="inchun" style="" onmouseover="changeOpacity10()" onmouseout="changeOpacity9()">
				<ul>
					<li style="width:602px; height:100px; text-align: center; margin-top:0px;"><img src="/public_html/img_n2021/index_page/line-height.jpg"></li>
				</ul>
				<ul>
					<li style="width:602px; height:40px; text-align: center; color:#777777;">brand</li>
				</ul>
				<ul style="" >
					<li><div class="" style="width:602px; height:310px; overflow:hidden; border:solid 1px #777;">
						<div class="" id="rand_pos2" style="width:602px; height:310px;  position:relative;">
						<img src="/public_html/img_n2021/index_page/inchun-bic.jpg" border="0" alt=""></div>
						<div id="test222" style="width:602px; height:300px; position:relative; left:0px; top:-310px; opacity:0.85;"><img src="/public_html/img_n2021/index_page/logo-mask-white.png" border="0" alt=""></div>
					</div></li>
				</ul>
				<ul>
					<li style="width:602px; height:6px; text-align: center; border-bottom:solid 1px #777;"></li>
				</ul>
			</div></a>
		</li>
		<li style="width:602px; height:370px; float:left; display:block;">
			<a href="#" ><div id="family" onmouseover="changeOpacity12()" onmouseout="changeOpacity11()">
				<ul>
					<li style="width:602px; height:100px; text-align: center; margin-top:0px;"><img src="/public_html/img_n2021/index_page/line-height.jpg"></li>
				</ul>
				<ul>
					<li style="width:602px; height:40px; text-align: center; color:#535353;">mission</li>
				</ul>
				<ul style="">
					<li><div style="width:602px; height:310px; overflow:hidden; border:solid 1px #777;">
						<a href="#" ><div class="" id="rand_pos3" style="width:602px; height:310px;  position:relative;">
						<img src="/public_html/img_n2021/index_page/family-bic.jpg" border="0" alt=""></div>
						<div id="test333" style="width:602px; height:300px; position:relative; left:0px; top:-310px;  opacity:0.85;"><img src="/public_html/img_n2021/index_page/logo-mask-white.png" border="0" alt=""></div></a>
					</div></li>
				</ul>
				<ul>
					<li style="width:602px; height:6px; text-align: center; border-bottom:solid 1px #777;"></li>
				</ul>
			</div></a>
		</li>
	</ul>
</div>
