<!doctype html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />  <!-- dnamooM_20160328 content="IE=edge"-->
    <meta name="format-detection" content="telephone=no, address=no, email=no" />
    <meta name="viewport" content="width=device-width"/>
    <link rel="SHORTCUT ICON" href="/public_html/m/images/hassed.png"/>
    <link rel="apple-touch-icon" href="/public_html/m/images/hassed.png">
    <title>.HASSED</title>
    <link rel="stylesheet" type="text/css" href="<?php echo CSS_MOBILE_DIR;?>/reset_style.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo CSS_MOBILE_DIR;?>/default_hassed.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo CSS_MOBILE_DIR;?>/default_hassed_2017.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo CSS_MOBILE_DIR;?>/menuf.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo CSS_MOBILE_DIR;?>/delivery.css" />
    <link rel="stylesheet" type="text/css" href="<?php echo CSS_MOBILE_DIR;?>/h_product.css" />


    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
    <script src="<?php echo JS_MOBILE_DIR;?>/topmenu.js"></script>

</head>
<body onload="">
<input type="hidden" name="<?=$this->security->get_csrf_token_name()?>" value="<?=$this->security->get_csrf_hash()?>"/>
<div id="" class="wrap">
    <div id="wrap_top">
        <div id="main_header" class="">
            <a href="#"><div id="back_toggle" class="back_transe">black_back</div></a>
            <div id="main_gnb">
                <ul>
                    <li id="gnb00"></li>
                    <li id="gnb01">
                        <a href="#1">
                            <div id="" class="category">COMPANY
                                <div id="pl01" class="togglepluse">+ </div>
                                <div id="mi01" class="toggleminuse">- </div>
                            </div>
                        </a>
                        <!-- //회사소개 매뉴 -->
                        <div id="sub_gnb01">
                            <ul>
                                <li><a href="/about/company">회사소개</a></li>
                                <li><a href="/about/brand">브랜드스토리</a></li>
                                <li><a href="/about/ceo">CEO 인사말</a></li>
                                <li><a href="/about/shop_info">매장정보</a></li>
                            </ul>
                        </div>
                    </li>
                    <li id="gnb02">
                        <a href="#2">
                            <div id="" class="category">
                                ECSAINE
                                <div id="pl02" class="togglepluse">+ </div>
                                <div id="mi02" class="toggleminuse">- </div>
                            </div>
                        </a>
                        <!-- //소재 매뉴 -->
                        <div id="sub_gnb02">
                            <ul>
                                <li><a href="/ecsaine/material">엑센느 소재</a></li>
                                <li><a href="/ecsaine/strongpoint">엑센느 특장점</a></li>
                                <li><a href="/ecsaine/maintain">엑센느 관리</a></li>

                            </ul>
                        </div>
                    </li>
                    <li id="gnb03">
                        <a href="#3">
                            <div id="" class="category">
                                PRODUCT
                                <div id="pl03" class="togglepluse">+ </div>
                                <div id="mi03" class="toggleminuse">- </div>
                            </div>
                        </a>
                        <!-- //제품소개 매뉴 -->
                        <div id="sub_gnb03">
                            <ul><li><a href="/product/detail_view?code=becky"><div class="div_emenu">BECKY</div><div class="div_kmenu">베키</div></a></li>
                                <li><a href="/product/detail_view?code=arriba"><div class="div_emenu">ARRIBA</div><div class="div_kmenu">아리바</div></a></li>
                                <li><a href="/product/detail_view?code=calix"><div class="div_emenu">CALIX</div><div class="div_kmenu">칼릭스</div></a></li>
                                <li><a href="/product/detail_view?code=ailish"><div class="div_emenu">AILISH</div><div class="div_kmenu">엘리쉬</div></a></li>
                                <li><a href="/product/detail_view?code=whistle"><div class="div_emenu">WHISTLE</div><div class="div_kmenu">휘슬</div></a></li>
                                <li><a href="/product/detail_view?code=besso"><div class="div_emenu">BESSO</div><div class="div_kmenu">베쏘</div></a></li>
                                <li><a href="/product/detail_view?code=floria"><div class="div_emenu">FLORIA</div><div class="div_kmenu">플로리아</div></a></li>
                                <li><a href="/product/detail_view?code=francis"><div class="div_emenu">FRANCIS</div><div class="div_kmenu">프란시스</div></a></li>
                                <li><a href="/product/detail_view?code=bambi"><div class="div_emenu">BAMBI</div><div class="div_kmenu">밤비</div></a></li>
                                <li><a href="/product/detail_view?code=adela"><div class="div_emenu">ADELA</div><div class="div_kmenu">아델라</div></a></li>
                                <li><a href="/product/detail_view?code=esther"><div class="div_emenu">ESTHER</div><div class="div_kmenu">에스더</div></a></li>
                                <li><a href="/product/detail_view?code=provence"><div class="div_emenu">PROVENCE</div><div class="div_kmenu">프로방스</div></a></li>
                                <li><a href="/product/detail_view?code=crane"><div class="div_emenu">CRANE</div><div class="div_kmenu">크레인</div></a></li>
                                <li><a href="/product/detail_view?code=amore"><div class="div_emenu">AMORE</div><div class="div_kmenu">아모르</div></a></li>
                                <li><a href="/product/detail_view?code=twinsofa"><div class="div_emenu">TWIN</div><div class="div_kmenu">트윈소파</div></a></li>
                                <li><a href="/product/detail_view?code=swingchair"><div class="div_emenu">SWING</div><div class="div_kmenu">스윙체어</div></a></li>
                            </ul>
                        </div>
                    </li><!-- dnamoo 20160425 hapro01.asp -->
                    <li id="gnb04"><a href="#4"><div id="" class="category">
                                GALLERY
                                <div id="pl04" class="togglepluse">+ </div>
                                <div id="mi04" class="toggleminuse">- </div>
                            </div></a>
                        <!-- //갤러리 매뉴 -->
                        <div id="sub_gnb04">
                            <ul>
                                <li><a href="/gallery/customer">고객후기</a></li>
                                <li><a href="/gallery/hmagajine">H_매거진</a></li>
                                <!-- <li><a href="haboard05.asp">영상자료</a></li> -->
                            </ul>
                        </div>
                    </li>
                    <li id="gnb05"><a href="#5"><div id="" class="category">
                                NOTICE
                                <div id="pl05" class="togglepluse">+ </div>
                                <div id="mi05" class="toggleminuse">- </div>
                            </div></a>
                        <!-- //고객지원 매뉴 -->
                        <div id="sub_gnb05">
                            <ul>
                                <li><a href="/notice/notice">공지사항</a></li>
                                <li><a href="/notice/faq">F&nbsp;A&nbsp;Q</a></li>
                                <li><a href="/notice/qna">Q&nbsp;&&nbsp;A</a></li>
                            </ul>
                        </div>
                    </li>
                    <li id="gnb06">
                        <div class="snslink">
                            <table width="700" height="80" border="0" cellpadding="0" cellspacing="0">
                                <tr>
                                    <td><img src="/public_html/m/images/btsns_05.png" width="400" height="80" alt=""></td>
                                    <td><a href="http://cafe.naver.com/hassedhouse"><img src="/public_html/m/images/btsns_02.png" width="100" height="80" alt=""></a></td>
                                    <td><a href="https://www.instagram.com/hassed_kr/"><img src="/public_html/m/images/btsns_03.png" width="100" height="80" alt=""></a></td>
                                    <td><a href="http://blog.naver.com/hassed_kr"><img src="/public_html/m/images/btsns_04.png" width="100" height="80" alt=""></a></td>
                                </tr>
                            </table>
                        </div>
                    </li>
                </ul>
            </div>
            <!-- <div id="logo_link" class="">
                <a href="index.asp"><img src="img/logo_area.png" width="180" height="60" border="0" alt=".HASSED"></a>
            </div> -->

            <div id="bt_menu" class="mobile_menu">menu</div>
            <div id="logo_link" class=""><a href="/"><img src="/public_html/m/images/logo_area.png" width="300" height="200" border="0" alt=".HASSED"></a></div>

            <!-- <div class="bt_mobile_eng">
                <a href="eindex.asp">ENG</a>
            </div> -->

        </div>
    </div>
