            <div id="" class="mobile_bottom">
                <div id="" class="mo_bo_01">
                    <ul>
                        <li>CONTACT US</li>
                        <li>02 401 5073</li>
                        <li>hassed_kr@naver.com</li>
                    </ul>
                </div>
                <div id="" class="mo_bo_02">
                    <ul>
                        <li><a href="/other/b2b">B2B</a></li>
                        <li><a href="/other/recruit">채용</a></li>
                        <li><a href="/other/law">법률성명</a></li>
                        <li><a href="/other/privacy">개인정보보호정책</a></li>
                        <li><a href="/notice/faq">FAQ</a></li>
                    </ul>
                </div>
                <div id="" class="mo_bo_03">
                    (주)헷세드   서울시 송파구 오금동 33-6번지 헷세드빌딩   대표이사 김기욱  <br>
                    사업자등록번호 132-86-14687&nbsp;&nbsp;&nbsp;&nbsp;ⓒ 2010 HASSED all right reserved
                </div>
            </div>
        </div>

        <!-- Password 입력 팝업 -->
        <div id="in_pass" class="popup_pw popup_box" style="display:none;">
            <form name="passwd" id="passwd" method = "post">
                <input type="hidden" name="ck_lock" id="ck_lock">
                <input type="hidden" name="pass_uri" id="pass_uri">
                <input type="hidden" name="pass_mode" id="pass_mode">
                <img src="/public_html/images/bg/in_pass_01.png" title="Password" style="vertical-align:top;">
                <div style="margin:0 23px 10px;overflow:hidden;">
                    <div class="box_pw">비밀번호 &gt;</div>
                    <input type="password" size="12" name="pw" id="pw" style="float:left;">
                </div>
                <div class="checkbt">
                    <input type="button" class="btn_pw" title="확인" onclick="CheckPW();">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <input type="button" class="btn_cancel" title="취소" onclick="cancel();">
                </div>
            </form>
        </div>
        <!-- Password 입력 팝업 // -->
    </body>
</html>
