<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/img_e/img_b2b.jpg" border="0" alt="">
    </div>
    <div id="" class="box_outline_b" style="height:530px;">
        <div id="" class="box_b2btitle">
            <img src="/public_html/img_e/title_b2b.png" border="0" alt="">
        </div>
        <div id="" class="" style="margin-top:50px; overflow:hidden;">
            <div id="" class="fl_left" style="width:460px;">
                <img src="/public_html/img_e/img_b2b01.jpg" border="0" alt="">
            </div>
            <div id="" class="fl_right">
                <img src="/public_html/img_e/img_b2b02.jpg" border="0" alt="">
            </div>
        </div>
    </div>
</div>