<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/img_e/img_b2b.jpg" border="0" alt="">
    </div>
    <div id="" class="box_outline_b" style="padding:76px 50px;">
        <div id="" class="box_b2btitle">
            <img src="/public_html/img_e/title_law.png" border="0" alt="">
        </div>
        <div id="" class="txt_just" style="margin-top:60px; color:#666;">
            <span class="">If you use .HASSED web site accessible through www.HASSED.kr (.HASSED's other website or web page accessible via the .HASSED website or a mini site or page hosted or sponsored by .HASSED's third-party social networking service) (collectively, the "Sites") (including access, browsing and / or interactive features), the following terms and conditions (the "Terms and Conditions") shall apply. Please read these terms and conditions carefully.</span>
            <br>
            <span class="">By using this site, you agree that these legally binding terms and conditions apply and you agree to act in accordance with these terms and conditions. .HASSED may change these terms and conditions from time to time. All changes will be posted on this site and you agree to be bound by such changes.</span>
        </div>
        <div id="" class="" style="margin-top:50px; overflow:hidden; color:#666;">
            <div id="" class="fl_left txt_just" style="width:468px;">
                <span class="" style="font-weight:bold;">Article 1 Protection of Personal Information</span><br>
                For information on how .HASSED handles the personal information you provide to .HASSED, please refer to .HASSED's Privacy Policy.
                <br><br>
                <span class="" style="font-weight:bold;">Article 2 Use of ownership / site materials</span><br>
                <span class="">.HASSED owns all rights, title and interest in this site and owns content and applications on this site (including content and applications on social network websites). </span>
                <br>
                <span class="">.HASSED owns all copyrights for all material on this site, or has acquired a valid right to use the materials on this site from a third party. In addition, .HASSED owns all the trademarks, service marks, trade names, logos and domain names used on or associated with this site or has acquired valid rights to use such materials from third parties. Any change or use of material on this site for any purpose not expressly permitted is a violation of .HASSED's copyright and other proprietary rights. </span>
                <br>
                <span class="" style="color:#de5f2d; display: inline-block;" >No part of this site may be copied, reproduced, republished, uploaded, posted, transmitted or distributed in any manner for any purpose other than for viewing without the prior written consent of .HASSED.</span> <span class="" style="display: inline-block;">Framing or unauthorized linking any content on this site is also included in the prohibited act.</span>
                <br><br>
                <span class="" style="font-weight:bold;">Article 3 Disclaimer / Limitation of Liability</span><br>
                <span class="">You are at your own risk as you use and browse the site. .HASSED, or anyone else affiliated with .HASSED in connection with the development or provision of this site, is not liable for any direct, indirect, special, punitive, incidental or punitive damages or for consequential damages. Except to the extent permitted by law and without limiting the foregoing, all in this site are expressed or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, non- without warranty of any kind, either express or implied. Some countries do not allow limitations on implied warranties or limitations of liability for consequential or incidental damages, so the above limitation may not apply to you. Please check local laws that apply to you. </span>
                <br>
                <span class="">.HASSED's privacy policy applies to any request information you provide via registration or subscription, and / or via email to ask questions on this site. .HASSED will not treat reviews, comments or other submissions that are not requested by .HASSED, including ideas, concepts, techniques and know-how, as confidential, and .HASSED may use such materials in any way .HASSED deems appropriate. For more information on this, please refer to .HASSED's Privacy Policy.</span>
            </div>

            <div id="" class="fl_right txt_just" style="width:468px;">
                <span class="" style="font-weight:bold;">Article 4 Links</span><br>
                <span class="" style="color:#de5f2d; display: inline-block;">.HASSED assumes no responsibility for third-party websites linked to or linked from this site.</span><span class="" style="display: inline-block;">.HASSED makes no warranty whatsoever with respect to any of the above Third Party Sites or any goods or services offered on such sites. .HASSED disclaims all liability for the accuracy of the information provided on the sites linked above and for the goods or services provided or purchased from such sites. .HASSED assumes no responsibility for the content of sites linked to or linked from this site. </span>
                <br><br>
                <span class="" style="font-weight:bold;">Article 5 Accuracy of Information</span><br>
                <span class="">.HASSED takes reasonable steps to ensure the accuracy of the information contained on this site. However, .HASSED assumes no responsibility for any errors or omissions in the content of this site and does not guarantee the accuracy, completeness or timeliness of the information provided on this site. The information provided on this site is subject to change at any time without prior notice. </span><br>
                <br>
                <span class="" style="font-weight:bold;">Article 6 Non-waiver</span><br>
                <span class="">Failure by .HASSED to perform any part of these terms and conditions does not constitute a waiver of any of .HASSED's rights under these terms and conditions for past or future actions. </span><br>
                <br>
                <span class="" style="font-weight:bold;">Article 7 Jurisdiction</span><br>
                <span class="">All disputes relating to the content on this site or the use of this site shall be governed by the substantive laws of the Republic of Korea, and the jurisdiction and venue of such proceedings shall be governed by the jurisdiction of the courts of Korea.</span><br>
                <br>
                <span class="" style="font-weight:bold;">Article 8 Miscellaneous</span><br>
                <span class="">You acknowledge and agree that these terms and conditions and .HASSED's Privacy Policy constitute the entire agreement between you and .HASSED regarding the use of this Site. </span><br>
                <br>
                <span class="" style="color:#de5f2d;">.HASSED may change these terms at any time by posting changes on this site. All changes will take effect as soon as they are posted. Your continued use of this site constitutes your acceptance of the modified terms.</span><br>
                <br>
                <span class="">This site is not intended to provide medical information about skin, etc</span><br>
                <br>
                <span class="">Your use of this site constitutes your acceptance of these terms and conditions and your agreement to abide by them.</span>



                <br><br><br><br>

                <span class="" style="text-align:right;">Last updated on: December 2015 <br>
ⓒ HASSED, 2015 All rights are reserved by .HASSED.</span>
            </div>
        </div>
    </div>
</div>