<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/img_e/img_b2b.jpg" border="0" alt="">
    </div>
    <div id="" class="box_outline_b">
        <div id="" class="box_b2btitle">
            <img src="/public_html/img_e/title_recruit.png" border="0" alt="">
        </div>
        <div id="" class="" style="margin-top:60px;">
            <img src="/public_html/img_e/img_recruit.jpg" border="0" alt="">
        </div>
    </div>
</div>