            <tr>
                <td height="40" align="left" style="padding-right:20px;"><font color="#E2FDFF">:: ADIMN + 게시판 관리 > <?=$menu_title?></font><br></td>
            </tr>
            </table>
            <table width="100%" cellpadding="0" cellspacing="0" border="0">
                <tr>
                    <td width="20">&nbsp;</td>
                    <td width="40" height="40" background="/public_html/images/cn_bg_dot.gif" align="right">
                        <img src="/public_html/images/spacer.gif" width="1" height="40" border="0"></td>
                    <td width="129" align="center"><span class="cntlt"><?=$menu_title?></span></td>
                    <td width="493" background="/public_html/images/cn_bg_dot.gif">
                        <img src="/public_html/images/spacer.gif" width="1" height="40" border="0"></td>
                </tr>
            </table>
            <br><br>
            <?php echo form_open_multipart('/admin/bbs_store/',array('name'=>"frm01", 'id'=>"frm01")); ?>
            <table width="100%" cellpadding="0" cellspacing="0" border="0" align="center">
                    <input type="hidden" id="proc_type" name="proc_type" value="M">
                    <input type="hidden" id="b_special" value="<?=$b_special?>">
                    <input type="hidden" id="b_code" name="b_code" value="<?php echo($b_code);?>" />
                    <input type="hidden" id="page" name="page" value="<?php echo($page);?>" />
                    <input type=hidden id="search_type" name="search_type" value='<?=$search_type?>'>
                    <input type=hidden id="search_value" name="search_value" value='<?=$search_value?>'>
                    <input type="hidden" name="b_board_type" id="b_board_type" value="1">
                    <input type="hidden" id="b_index" name="b_index" value="<?php echo(!empty($b_index))?$b_index:'';?>">
                    <input type="hidden" name="select_img" id="select_img">
                    <tr valign="top">
                        <td align="center" style="padding-left:20px; padding-right:20px;">
                            <table width="100%" cellpadding="0" cellspacing="5" border="0" bgcolor="#999999">
                                <tr>
                                    <td>
                                        <table width="100%" cellpadding="5" cellspacing="1" border="0" bgcolor="#999999">
                                    <?php
                                    switch ($b_code) {
                                        case "FREEBOARD0" : // 헷세드공지
                                        case "CEPILOGUE0" : // 고객후기
                                        case "SEPILOGUE0" : // H_매거진
                                            ?>
                                            <tr bgcolor="#FFFFFF">
                                                <td width="120" valign="top"><font color="#999999"><b>| 햇세드추천</b></font></td>
                                                <td><input type="text" name="b_special" size="3" value="<?=$b_special?>" style="ime-mode:disabled" onKeyPress="return onlyNum()"> <font color="blue">※ <b>추천 사용 방법</b></font> 1 ~ 999 까지의 정수 입력, 강조를 취소할 경우 0 입력.(큰숫자가 제일 상단에 위치)</td>
                                            </tr>

                                            <?php
                                            break;
                                        case "QANDA0" : // Q&A
                                            ?>
                                            <tr bgcolor="#eeeeee">
                                                <td width="120" valign="top"><font color="#666666"><b>| 공지사항</b></font></td>
                                                <td><input type="text" name="B_Special" size="3" value="<?=$b_special?>" style="ime-mode:disabled" onKeyPress="return onlyNum()"> <font color="blue">※ <b>추천 사용 방법</b></font> 1 ~ 999 까지의 정수 입력, 강조를 취소할 경우 0 입력.(큰숫자가 제일 상단에 위치)</td>
                                            </tr>
                                            <?php
                                            break;
                                        default:
                                    }
                                    ?>
                                            <tr bgcolor="#FFFFFF">
                                                <td width="120" valign="top"><font color="#999999"><b>|</b></font> 글쓴이</td>
                                                <td><input type="text" id="b_writer" name="b_writer" size="30" maxlength="30" value=""></td>
                                            </tr>
                                            <tr bgcolor="#FFFFFF">
                                                <td width="120" valign="top"><font color="#999999"><b>|</b></font> 이메일</td>
                                                <td><input type="text" name="b_email1" id="b_email1" size="10" class="textbox" value=""> @ <input type="text" id="b_email2"  name="b_email2" size="20" class="textbox" value="">
                                                    <select name="u_email" class="textbox" onChange="if(this.value==''){with(document.frm01){b_email2.readOnly=false;b_email2.value='';b_email2.focus();}}else{with(document.frm01){b_email2.readOnly=true;b_email2.value=this.value;}}">
                                                        <option value="">직접입력</option>
                                                        <option value="naver.com">naver.com</option>
                                                        <option value="nate.com">nate.com</option>
                                                        <option value="daum.net">daum.net</option>
                                                        <option value="hanmail.net">hanmail.net</option>
                                                        <option value="lycos.co.kr">lycos.co.kr</option>
                                                        <option value="empal.com">empal.com</option>
                                                        <option value="dreamwiz.com">dreamwiz.com</option>
                                                        <option value="hanmir.com">hanmir.com</option>
                                                        <option value="hanafos.com">hanafos.com</option>
                                                        <option value="hotmail.com">hotmail.com</option>
                                                        <option value="paran.com">paran.com</option>
                                                    </select></td>
                                            </tr>
                                            <tr bgcolor="#FFFFFF">
                                                <td width="120" valign="top"><font color="#999999"><b>|</b></font> 제목</td>
                                                <td><input type="text" name="b_title" id="b_title" size="50" maxlength="100" value=""></td>
                                            </tr>
                                            <tr bgcolor="#FFFFFF">
                                                <td width="120" valign="top"><font color="#999999"><b>|</b></font> 내용</td>
                                                <td><?php $this->load->view('editor.phtml');?></td>
                                            </tr>
                                            <tr bgcolor="#FFFFFF">
                                                <td width="120" valign="top"><font color="#999999"><b>|</b></font> 기존파일</td>
                                                <td>
                                                    <table width="100%">
                                                        <tr align="center">
                                                            <td width="80">이미지</td>
                                                            <td width="60">위치</td>
                                                            <td width="70">목록노출</td>
                                                            <td align="left">삭제</td>
                                                        </tr>
                                            <?php
                                            if(!empty($file_data)) {
                                                foreach ($file_data as $key => $value) {
                                                    $temp_fname = explode('.', $value->f_name);
                                                    $mType = explode("/",$value->f_type);
                                                    if($b_board_type == "0") {

                                                        ?>
                                                        <tr align="center" class="<?php echo $value->f_index; ?>">
                                                        <?php if($mType[0] == "image") {?>
                                                            <td rowspan="2"><img src="<?= $value->file_path.'_145x90.'.$temp_fname[1] ?>" width="72" height="45" style="vertical-align:middle;"></td>
                                                        <?php }else{?>
                                                            <td rowspan="2"></td>
                                                        <?php }?>
                                                            <td><select name="f_position">
                                                                    <option value="T" <?php if ($value->f_position == "T"){echo "selected"; }?>>상단</option>
                                                                    <option value="B" <?php if ($value->f_position == "B"){echo "selected"; }?>>하단</option>
                                                                </select>
                                                            </td>
                                                            <td><input type="radio" name="b_show" value="<?php echo $value->f_index; ?>" <?php if ($value->f_show == '1'){ echo "checked"; }?> style="cursor:pointer;"></td>
                                                            <td style="text-align:left;padding-left:7px;">
                                                                <img src='/public_html/images/ico_del.gif' onclick="try{ b_file[<?= $key?>].value='삭제';f_index[<?= $key?>].value=''; }catch(e){ b_file.value='삭제';f_index.value=''; delFile(<?php echo $value->f_index; ?>);}this.style.display='none';" alt="삭제" style="cursor:pointer;">
                                                            </td>
                                                        </tr>
                                                        <tr class="<?php echo $value->f_index; ?>">
                                                            <td colspan="3">
                                                                <input type="hidden" name="f_Index" value="<?php echo $value->f_index; ?>">
                                                                <input type='text' name='b_file' size='20' value='<?php echo $value->f_name; ?>' readonly style='border:0;'></td>
                                                        </tr>
                                                        <?php
                                                    }else{
                                                        If($mType[0] != "image") {
                                                            ?>
                                                            <tr align="center" class="<?php echo $value->f_index; ?>">
                                                                <td rowspan="2"></td>
                                                                <td><select name="f_position">
                                                                        <option value="T" <?php if ($value->f_position == "T"){ echo "selected";} ?>>상단</option>
                                                                        <option value="B" <?php if ($value->f_position == "B"){ echo "selected";} ?>>하단</option>
                                                                    </select>
                                                                </td>
                                                                <td></td>
                                                                <td style="text-align:left;padding-left:7px;">
                                                                    <img src='/public_html/images/ico_del.gif' onclick="delFile(<?php echo $value->f_index; ?>);" alt="삭제" style="cursor:pointer;">
                                                                </td>
                                                            </tr>
                                                            <tr class="<?php echo $value->f_index; ?>">
                                                                <td colspan="3">
                                                                    <input type="hidden" name="f_Index" value="<?php echo $value->f_index; ?>">
                                                                    <input type='text' name='b_file' size='20' value='<?php echo $value->f_name; ?>' readonly style='border:0;'></td>
                                                            </tr>

                                                            <?php
                                                        }
                                                    }
                                                }
                                            }
                                            ?>
                                                    </table>
                                                </td>
                                            </tr>
                                            <tr bgcolor="#FFFFFF">
                                                <td width="120" valign="top"><font color="#999999"><b>|</b></font> 파일</td>
                                                <td><font color="blue">※ <b>파일 사용 방법</b></font><br />
                                                    업로드 하고자 하는 파일 갯수대로 파일 등록 창을 추가/삭제가 가능하며, 상단, 하단 선택을 할수 있으며,<br/>
                                                    보여질 경우에는 순서에 맞게 상단, 하단에 위치하여 보여지게 됩니다.<br/><br/>
                                                    <font color="red">이미지 파일 ('jpg', 'jpeg', 'png', 'bmp', 'gif')의 경우 에디터에서 업로드해주세요</font><br/><br/>
                                                    <font color="red">동영상 파일은 확장자가 MP4만 올릴수 있으며 위치를 상단에 맞추어 주시고,<br />
                                                        하나 이상 등록시에는 자동 재생되어 동시에 재생되는 상황이 발생할 수 있습니다.</font>
                                                    <ul id="FileDiv">
                                                        <li><input type="file" name="files[]" size="50" onchange="checking_file();"> ||| 위치 : <select name="position[]"><option value=T>상단</option> <option value=B>하단</option></select> <a href="javascript:void(0);" name="btn" class="btn">추가</a></li>
                                                    </ul>
                                                </td>
                                            </tr>
                                            <!--
                                            <tr bgcolor="#FFFFFF">
                                                <td width="120" valign="top"><font color="#999999"><b>|</b></font> HTML(TAG)</td>
                                                <td>사용 <input type="checkbox" name="B_TAG" value="Y" <% If Rs("B_Encode") = "Y" Then Response.write "checked" End If %>></td>
                                            </tr>
                                            -->
                                            <tr bgcolor="#FFFFFF">
                                                <td width="120" valign="top"><font color="#999999"><b>|</b></font> 잠금기능</td>
                                                <td>사용 <input type="checkbox" name="b_locked" class="textbox" value="Y"></td>
                                            </tr>
                                            <tr bgcolor="#FFFFFF">
                                                <td width="120" valign="top"><font color="#999999"><b>|</b></font> 비밀번호</td>
                                                <td><input type="password" id="b_password" name="b_password" size="30" maxlength="30" value=""></td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                                <tr align="center">
                                    <td bgcolor="#dddddd" height="30">
                                        <input type="button" value="저장" onClick="saveContent();">
                                        <input type="button" value="목록" onClick="frmList('<?=$list_uri?>');">
                                    </td>
                                </tr>
                            </table>
                            <br>
                        </td>
                    </tr>
                </table>
            </form>
            <br><br>
        </td>
    </tr>
</table>
<script type="text/javascript">
    $(document).on('click','a',(function() {
        if($(this).html() == "삭제"){
            $(this).parent().remove(); //li 삭제
        }

        if($(this).html() == "추가"){
            html = "";
            html += "<li>";
            html += "<input type=\"file\" name=\"files[]\" size=\"50\"> ||| 위치 : ";
            html += "<select name=\"position[]\">";
            html += "   <option value=\"T\">상단</option>";
            html += "   <option value=\"B\">하단</option>";
            html += "</select>";
            html += " <a href=\"javascript:void(0);\" name=\"btn\" class=\"btn\">삭제</a>";
            html += "</li>";

            $("#FileDiv").append(html); //.append(html);
        }
    }));
</script>
<script type="text/javascript">
    var config = {
        txHost: '', /* 런타임 시 리소스들을 로딩할 때 필요한 부분으로, 경로가 변경되면 이 부분 수정이 필요. ex) http://xxx.xxx.com */
        txPath: '', /* 런타임 시 리소스들을 로딩할 때 필요한 부분으로, 경로가 변경되면 이 부분 수정이 필요. ex) /xxx/xxx/ */
        txService: 'sample', /* 수정필요없음. */
        txProject: 'sample', /* 수정필요없음. 프로젝트가 여러개일 경우만 수정한다. */
        initializedId: "", /* 대부분의 경우에 빈문자열 */
        wrapper: "tx_trex_container", /* 에디터를 둘러싸고 있는 레이어 이름(에디터 컨테이너) */
        form: 'frm01'+"", /* 등록하기 위한 Form 이름 */
        txIconPath: "images/icon/editor/", /*에디터에 사용되는 이미지 디렉터리, 필요에 따라 수정한다. */
        txDecoPath: "images/deco/contents/", /*본문에 사용되는 이미지 디렉터리, 서비스에서 사용할 때는 완성된 컨텐츠로 배포되기 위해 절대경로로 수정한다. */
        canvas: {
            styles: {
                color: "#123456", /* 기본 글자색 */
                fontFamily: "굴림", /* 기본 글자체 */
                fontSize: "10pt", /* 기본 글자크기 */
                backgroundColor: "#fff", /*기본 배경색 */
                lineHeight: "1.5", /*기본 줄간격 */
                padding: "8px" /* 위지윅 영역의 여백 */
            },
            showGuideArea: false
        },
        events: {
            preventUnload: false
        },
        sidebar: {
            attachbox: {
                show: true,
                confirmForDeleteAll: true

            },
            attacher:{
                image: {
                    features:{left:250, top:250, width:500, height:188},
                    checksize: false
                }
            },
            capacity:{maximum: 1014572800 }
        },

        size: {
            contentWidth: 700 /* 지정된 본문영역의 넓이가 있을 경우에 설정 */
        }


    };

    EditorJSLoader.ready(function(Editor) {
        var editor = new Editor(config);
    });

    /* 예제용 함수 */
    function saveContent() {
        Editor.save(); // 이 함수를 호출하여 글을 등록하면 된다.

    }

    function validForm(editor) {
        var validator = new Trex.Validator();
        var content = editor.getContent();


        if($('#b_writer').val() == "") {
            alert('고객명을 입력해 주세요.');
            b_writer.focus();
            return;
        }
        if($('#b_password').val() == "") {
            alert('비밀번호를 입력해 주세요.');
            b_password.focus();
            return;
        }
        if($('#b_title').val() == "") {
            alert('제목을 입력해 주세요.');
            b_title.focus();
            return;
        }
//        if($('#b_email1').val() == "" || $('#b_email2').val() == "") {
//            alert('이메일을 입력해 주세요.');
//            B_Email1.focus();
//            return;
//        }
//        if (!validator.exists(content)) {
//            alert('내용을 입력하세요');
//            return false;
//        }
        $('#b_board_type').val('1');
        if($('#tx_switchertoggle').attr('class') == 'tx-switchtoggle-pushed') { // html 사용안함
            $('#b_board_type').val('0');
        }

        return true;
    }

    function setForm(editor) {
        var i, input;
        var form = editor.getForm();
        var content = editor.getContent();

        var textarea = document.createElement('textarea');

        textarea.name = 'b_content';
        $(textarea).css('display','none');
        textarea.value = content;
        form.createField(textarea);
        //var images = editor.getAttachments('image');
        var images = Editor.getSidebar().getAttachments("image");
        for (i = 0; i < images.length; i++) {
            // existStage는 현재 본문에 존재하는지 여부
            // if (images[i].existStage) {
            var entry = images[i];
            if( entry.deletedMark == false ){
                // data는 팝업에서 execAttach 등을 통해 넘긴 데이터
                //alert('attachment information - image[' + i + '] \r\n' + JSON.stringify(images[i].data));
                input = document.createElement('input');
                input.type = 'hidden';
                input.name = 'attach_image[]';
                //input.value = images[i].data.filename;  // 예에서는 이미지경로만 받아서 사용
                input.value =  images[i].data.f_rename + '|' +images[i].data.filename + '|'+  images[i].data.mimeType + '|'+  images[i].data.imageWidth + '|'+  images[i].data.filesize;  // 예에서는 이미지경로만 받아서 사용
                form.createField(input);
            }
        }

        var files = editor.getAttachments('file');
        for (i = 0; i < files.length; i++) {
            input = document.createElement('input');
            input.type = 'hidden';
            input.name = 'attach_file';
            //input.value = files[i].data.attachurl;
            //input.value = files[i].data.filename;
            //  alert('attachment information - image[' + i + '] \r\n' + JSON.stringify(files[i].data));
            input.value =  files[i].data.f_rename + '|' +images[i].data.filename + '|'+  files[i].data.mimeType + '|'+  files[i].data.imageWidth + '|'+  files[i].data.filesize+ '|'+  files[i].data.attachurl ;  // 예에서는 이미지경로만 받아서 사용
            form.createField(input);
        }
        return true;
    }
</script>
<script type="text/javascript">
    <!--
    // 폼 초기화
    $('#clear').click(function(){
        if (confirm("작성하던 내용을 모두 삭제 하시겠습니까?") == true){    //확인
            $('#b_writer').val("");
            $('#b_password').val("");
            $('#b_title').val("") ;
            $('#b_email1').val("") ;
            $('#b_email2').val("");
            $('#s_email').val("");
        }
        //window.location.reload();
    });

    $(function(){
        <?php if(!empty($b_index)) { ?>
        getContents();
        <?php }?>
    });

    function getContents() {

        $.ajax({
            type: "POST",
            url: "/ajax/board/get_view",
            dataType: 'json',
            data: {
                csrf_token: $('input[name=csrf_token]').val(),
                b_index : $("#b_index").val(),
                mode : 'admin'
            } ,
            beforeSubmit: function (data, frm, opt) {
                console.log('데이타를 불러오는 중입니다.');
            },
            success: function(result) {
                //console.log(result);
                if(result.result == 'success') {
                    if(result.view.b_board_type == 1) {
                        if(result.view.file_cnt > 0) {
                            // 첨부 있을때
                            loadContents(result.view,result.file);
                        } else {
                            // 첨부 없을때
                            loadContents(result.view);
                        }
                    } else{
                        loadContents(result.view);
                    }
                } else {
                    // TODO 실패에 따른 처리
                    alert( result.msg);
                    history.back();
                }
            }
        });
    }


    function loadContents(reDate, files) {

        var attachments = {};
        attachments['image'] = [];
        attachments['file'] = [];

        if(typeof(files) != "undefined") {
            console.log(files);
            $.each(files, function(i, obj) {
                if(obj.f_index != null && obj.f_position == null) {
                    tmp_type = obj.f_type.split('/');
                    if(tmp_type[0] == "image") {

                        attachments['image'].push({
                            'attacher': 'image',
                            'data': {
                                'imageurl': obj.file_path,
                                'filename': obj.f_name,
                                'f_rename': obj.f_rename,
                                'filesize': obj.f_size,
                                'originalurl': obj.file_path,
                                'thumburl': obj.thumburl
                            }
                        });
                    } else {
                        attachments['file'].push({
                            'attacher': 'file',
                            'data': {
                                'attachurl': obj.file_path,
                                'filemime': obj.f_type,
                                'filename': obj.f_name,
                                'f_rename': obj.f_rename,
                                'filesize': obj.f_size
                            }
                        });
                    }
                }
            });
        }

        //console.log(attachments);
        $('#b_writer').val(reDate.b_writer);
        $('#b_title').val(reDate.b_title);
        var _Email = reDate.b_email.split('@');
        $('#b_email1').val(_Email[0]);
        $('#b_email2').val(_Email[1]);
        $('#proc_type').val("M");
        $('#b_password').val(reDate.b_password);

        if(reDate.b_locked == "Y") {
            $('#b_locked').attr("checked", true);
        }


        /* 저장된 컨텐츠를 불러오기 위한 함수 호출 */
        Editor.modify({
            "attachments": function () { /* 저장된 첨부가 있을 경우 배열로 넘김, 위의 부분을 수정하고 아래 부분은 수정없이 사용 */
                var allattachments = [];
                for (var i in attachments) {
                    allattachments = allattachments.concat(attachments[i]);
                }
                return allattachments;
            }(),
            "content": reDate.b_content	/* 내용 문자열, 주어진 필드(textarea) 엘리먼트 */
        });
    }

    //-->
    $(document).ready(function(){
        $(document).on('click',".tx-name",function(){

            alert("현재 이미지를 대표이미지로 선택합니다.");
            var index = $( ".tx-name" ).index( this );
            $("#select_img").val(index);
        });

    });
</script>