<HTML>
<HEAD>
    <title>Management Program</title>
    <META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=utf-8">
    <script language="javascript">
        <!--
        function form_submit(){
            objForm = document.form1;
            if(objForm.id.value == ""){
                alert("아이디를 입력해 주세요.");
                objForm.id.focus();
                return false;
            }
            if(objForm.password.value == ""){
                alert("비밀번호를 입력해 주세요.");
                objForm.password.focus();
                return false;
            }
            objForm.submit();
        }
        -->
    </script>
</HEAD>

<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" bgcolor="#696969">
<div style="width:100%;height:100%;overflow:auto;">
    <div style="position:absolute;top:50%;left:50%;margin:-230px 0 0 -300px;padding:30px 100px;width:400px;height:400px;background:#eee;">
        <div style="text-align:center;">
            <img src="/public_html/img/main_logo.png">
        </div>
        <p style="text-align:center;font-weight:bold;color:#666;">
            <img src="/public_html/img/dec_login.png" style="vertical-align:middle;"> HASSED 관리자 페이지 입니다.
        </p>
        <div style="width:314px;padding:20px 50px;border:1px solid #ddd;background:#fff;">
            <p style="margin:20px auto;font-weight:bold;color:#666;">
                관리자 아이디와 비밀번호를 입력하세요.
            </p>
            <form name="form1" method="post" action="login.asp">
                <div style="overflow:hidden;">
                    <label style="float:left;padding-top:5px;margin-right:30px;color:#999;font-weight:bold;">아이디</label>
                    <input name="id" type="text" size="16" maxlength="20" tabindex="1" style="float:left;width:180px;padding:5px 10px;background:#fff;border:1px solid #ddd;">
                </div>
                <div style="margin:10px 0;overflow:hidden;">
                    <label style="float:left;padding-top:5px;margin-right:14px;color:#999;font-weight:bold;">비밀번호</label>
                    <input name="password" type="password" size="20" maxlength="20" onKeyDown="javascript:if(event.keyCode==13){form_submit(); return false;}" tabindex="2" style="float:left;width:180px;padding:5px 10px;background:#fff;border:1px solid #ddd;">
                </div>
                <div style="margin:20px 0;">
                    <input type="button" value="로그인" onClick="return form_submit();" tabindex=3 style="width:284px;height:50px;line-height:50px;text-align:center;border:none;background:#1598ab;color:#fff;font-weight:bold;">
                </div>
            </form>
        </div>
    </div>
</div>
</body>
</HTML>