<link rel="stylesheet" type="text/css" href="/public_html/css_e/h_product.css" />
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/imgpro/img_settle201.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro_e/title_settle2.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            A gesture of love
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/settle.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            coral in color
        </div>
        <div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/settle_1.jpg" border="0" alt="">
        </div>
	 <div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/settle_2.jpg" border="0" alt="">
        </div>
        <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('e_frame_special.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>

    <div id="" class="box_design">
        <img src="/public_html/imgpro_e/img-settle204.png" border="0" alt="">
    </div>

<br><br><br><br><br><br><br>
    <div class="sub_img">
        <img src="/public_html/imgpro/img_settle301.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro_e/title_settle3.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            A place whispering love
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/settle3.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            coral in color
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/settle3_1.jpg" border="0" alt="">
        </div>
	 <div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/settle3_2.jpg" border="0" alt="">
        </div>
        <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('e_frame_special.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>

        <!-- delivery ////////////////////////////// -->
    <?php $this->load->view('e_frame_delivery.phtml');?>
    <!-- delivery ////////////////////////////// -->
</div>