<link rel="stylesheet" type="text/css" href="<?php echo CSS_MOBILE_DIR;?>/board_hassed_mobile-cb<?php echo CACHE_VERSION;?>.css" />
<link href='http://fonts.googleapis.com/css?family=Libre+Baskerville' rel='stylesheet' type='text/css'>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="<?php echo JS_DIR; ?>/bbs-cb<?php echo CACHE_VERSION;?>.js"></script>
<script src="<?php echo JS_DIR; ?>/slider/jquery.bxslider.min.js"></script>

<link href="<?php echo JS_DIR; ?>/slider/jquery.bxslider.css" rel="stylesheet" />

<?php echo form_open(); ?>
<input type="hidden" id="page" value="<?php echo($page);?>">
<input type="hidden" id="b_code" value="<?php echo($b_code);?>">
<input type="hidden" id="b_index" name="b_index">
</form>
<div id="wrap_middle" class="" style="">
    <div id="" class="box_full">
        <div class="sub_img">
            <img src="/public_html/img/img_board_main.png" border="0" alt="">
        </div>
        <div id="" class="" style="width:100%; height:308px; position:absolute; background-color:#faf8f6; display:block; z-index:-10; margin-top:-570px;">
        </div>
    </div>
    <div id="" class="box_full_in_center">
        <!--contents_info-->
        <div id="">

            <div class="wrap_board" id="tj_content">
                <div class="board_area">
                    <div id="" class="">
                        <img src="/public_html/m/images/title_popular_review-2020.png" width="1080" height="80" border="0" alt="">
                    </div>
                    <div class="gallery_pop_out">
                        <div class="imglist">
                            <div class="setbox">
                                <div id="slider-prev"></div>
                                <div class="centerlist">
                                    <div class="bx-wrapper" style="max-width: 1030px; margin: 0px auto;">
                                        <div class="bx-viewport" style="width: 100%; overflow: hidden; position: relative; height: 193px;">
                                            <ul class="bxslider" style="width: 1415%; position: relative; transition-duration: 0.7s; transform: translate3d(-1800px, 0px, 0px);"></ul>
                                        </div>
                                    </div>
                                </div>
                                <div id="slider-next"></div>
                            </div><!-- setbox end -->
                        </div><!-- imglist end -->
                    </div>
                    <div id="" class="gallery_copyright">
                        헷세드는 지난 9년간 상업적인 광고없이 고객님의  감동으로 성장하였습니다.<br>
                        가정의 멋진 아름다움과 행복을 후기로 공유해주세요!
                    </div>
                    <!-- 고객후기 list -->
                    <div id="" class="gallery_title">
                         <img src="/public_html/m/images/title_customer_review-2020.png" width="1080" height="80" border="0" alt="">
                    </div>
                    <!-- 글쓰기 버튼 // -->
                    <div id="" class="gallery_write">
                        <div class="bt_write">
                            <a href="javascript:write();"><img src="/public_html/m/images/bg/btn-write.png" border="0" alt="글쓰기"></a>
                        </div>
                    </div>
                    <div class="gallery_out"></div>
                    <br>
		 
                    <!-- <span class="under_line">밑선</span> -->
                    <!-- Default List // -->
                    <div id="" class="" style="width:1080px; height:10px; margin-top:60px; margin-bottom:70px; border-top:solid 1px #666;"></div>
                    
                    <!-- Pagination -->
                    <div class="bbs_page paging"></div>
                    <!-- Pagination // -->
                   
                    <!-- BBS_find //-->
                    <div class="find_div"> <!-- style="height:22px;text-align:center;"-->
                        <select name="search_type" id="search_type" class="find_sel">
                            <option value="b_title" <?php if($search_type == "b_title") echo "selected";?>>제목</option>
                            <option value="b_content" <?php if($search_type == "b_content") echo "selected";?>>내용</option>
                            <option value="b_writer" <?php if($search_type == "b_writer") echo "selected";?>>글쓴이</option>
                        </select>
                        <input type="text" name="search_value" id="search_value" class="input_find" style="width:130px;" value="<?php echo $search_value;?>">
                        <input type="button" class="btn_find" title="찾아보기" onclick="page_move(1);" style="vertical-align: bottom">
                    </div>
                    <!-- BBS_find // -->
		     <div id="" class="gallery_write" style="height:100px;">
                        <div class="bt_writebot"><a href="javascript:write();"><img src="/public_html/m/images/bg/btn-write.png" border="0" alt="글쓰기" onclick="write();"></a></div>
                    </div>
                </div>
            </div>
            <!--//contents_info-->
        </div>
    </div>
</div>

<script type="text/javascript">
    if($("#page").val() == "") {
        get_list(1);
    }else{
        get_list($("#page").val());
    }
    $(document).ready(function(){
        var html ='';

        $.ajax({
            type : "POST",
            url : "/ajax/board/get_porpula_list",
            data: {
                csrf_token: $('input[name=csrf_token]').val(),

            },
            async : true,
            cache : false,
            success : function(result) {
                var data   = $.parseJSON(result);
                $.each( data, function( key, value ) {
                    html += '<li style="width: 310px; height: 193px; float: left; background-color: rgb(255, 255, 255); border-bottom: 1px solid rgb(214, 210, 206); overflow: hidden; display: block; list-style: none; position: relative; margin-right: 50px;" class="bx-clone">';
                    html += '<div class="bimg" onclick="javascript:page_view(' + value.b_index + ')"><img src="' + value.f_rename + '" width="310" height="193" valign="center" alt=""></div>';
                    html += '<div class="btxt">' + value.b_title + '</div>';
                    html += '</li>';

                });

                $(".bxslider").append(html);
                var slider = $('.bxslider').bxSlider({
                    mode: 'horizontal',
                    speed: 700,
                    pause: 4000,
                    auto : true,
                    autoStart : true,
                    pager: false,
                    captions: true,  //캡션
                    controls:false, //전 후 콘트롤 보이기 안보이기
                    minSlides: 1,
                    maxSlides: 3,
                    moveSlides: 1,
                    slideWidth: 310,
                    slideMargin: 50,
                    nextSelector: '#slider-next',
                    prevSelector: '#slider-prev',
                    nextText: '<div class="bt_next"></div>',
                    prevText: '<div class="bt_pre"></div>'
                });

            },
            error : function() {
                alert("다시 시도해 주세요.");
            }
        });

        $('.bt_next, .bt_pre').click(function(){
            // time to wait (in ms)
            var wait = 3000;
            setTimeout(function(){
                slider.startAuto();
            }, wait);
        });


    });

    function write(){
        location.href = '/gallery/customer_write/?page='+$("#page").val()+'&b_code='+$("#b_code").val()+'&search_type='+$("#search_type option:selected").val()+'&search_value'+$("#search_value").val()
    }


    function page_move(page){
        location.href = '/gallery/customer/?page='+page+'&search_type='+$("#search_type option:selected").val()+'&search_value='+$("#search_value").val();
    }

    function get_list(page){
        var html_list ='';
        var timestamp = + new Date();
        $(".gallery_out").empty();
        $.ajax({

            type : "POST",
            url : "/ajax/board/get_gallery_list",
            data: {
                csrf_token: $('input[name=csrf_token]').val(),
                search_type: $("#search_type option:selected").val(),
                search_value: $("#search_value").val(),
                page : page,
                mode : 'site'
            },
            cache : false,
            success : function(result) {
                var data   = $.parseJSON(result);
                var list_cnt = 0;
                html_list += '<div class="gallery_set">';
                $.each( data.list, function( key, value ) {
                    html_list += '   <div class="gallery_list" onclick="page_view(' + value.b_index + ');">';
                    if(value.f_rename == "no_image" ) {

                        html_list += '       <div class="thumb"><img src="/public_html/images/icon/icon_noimage.png" width="145" height="90" valign="center"></div>';
                    }else{
                        html_list += '       <div class="thumb"><img src="' + value.f_rename + '?'+ timestamp +'" width="145" height="90" valign="center"></div>';
                    }
                    html_list += '      <div class="title ellipsis">' + value.b_title + '</div>';
                    html_list += '      <div class="info" style="margin-top:10px;">';
                    html_list += '          <span class="name ellipsis" >' + value.b_writer + '</span>';
                    if(value.reply != '0') {
                        html_list += '          <span style="vertical-align:text-top; position: inline-block;"><img src="/public_html/images/icon/icon_re.png" title="reply"></span>';
                    }
                    html_list += '      </div>';
                    html_list += '      <div class="info" style="position:relative;"><span class="date" >' + value.show_date + '</span><span class="viewcount">view ' + value.b_hit + '</span></div>';
                    html_list += '   </div>';
                    list_cnt++;
                });
                html_list += '</div>';

                if(list_cnt == 0 && data.page_navi.total == 0){
                    html_list = '<div style="padding:15px;padding-left:45%;"><b>검색된 게시물이 없습니다.</b></div>'
                }

                $(".gallery_out").append(html_list);

                /* 현재 페이지, 마지막 페이지, 보여주는 데이터 수, 전체 데이터 수, 한 페이지에 보여주는 페이징 수 */
                pagination(data.page_navi.current_page, data.page_navi.last_page, data.page_navi.per_page, data.page_navi.total, 10);
                var msg ="Total " + data.page_navi.total + " 건 " +data.page_navi.current_page+ " 페이지";
                $("#total_page").text(msg);
                $("#page").val(page);
            },
            error : function() {
                alert("다시 시도해 주세요.");
            }
        });
    }

    function page_view(id){
        $.ajax({
            type : "POST",
            url : "/ajax/board/get_permission_check",
            data: {
                csrf_token: $('input[name=csrf_token]').val(),
                b_index : id
            },
            cache : false,
            success : function(result) {
                var data   = $.parseJSON(result);
                if(data.lock == 'Y'){
                    $("#b_index").val(id);
                    send('/gallery/customer_view?b_index='+id+'&page='+$("#page").val()+'&search_type='+$("#search_type option:selected").val()+'&search_value='+$("#search_value").val(),'view');
                }else{
                    location.href = '/gallery/customer_view?b_index='+id+'&page='+$("#page").val()+'&search_type='+$("#search_type option:selected").val()+'&search_value='+$("#search_value").val();
                }

            },
            error : function() {
                alert("다시 시도해 주세요.");
            }
        });

    }

</script>
