<link rel="stylesheet" type="text/css" href="<?php echo CSS_DIR; ?>/board_hassed_2017-cb<?php echo CACHE_VERSION;?>.css" />
<link href='http://fonts.googleapis.com/css?family=Libre+Baskerville' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="/public_html/d_editor/css/editor.css" type="text/css" charset="utf-8"/>
<script src="/public_html/d_editor/js/editor_loader.js" type="text/javascript" charset="utf-8"></script>

<div id="wrap_middle" class="" style="margin-top:140px;">
    <div id="" class="box_full">
        <div class="sub_img">
            <img src="/public_html/img/img_board_main.png" border="0" alt="">
        </div>
        <div id="" class="" style="width:100%; height:308px; position:absolute; background-color:#faf8f6; display:block; z-index:-10; margin-top:-570px;">
        </div>
    </div>

    <div id="" class="box_full_in_center">
        <!--contents_info-->
        <div id="" style="width:1080px;height:879px">
            <div class="wrap_board">
                <div class="board_area">
                    <?php echo form_open_multipart('/gallery/customer_store/',array('name'=>"tx_editor_form", 'id'=>"tx_editor_form")); ?>
                    <input type="hidden" id="b_code" name="b_code" value="<?php echo($b_code);?>" />
                    <input type="hidden" id="page" name="page" value="<?php echo($page);?>" />
                    <input type="hidden" name="proc_type" id="proc_type" value="NW">
                    <input type="hidden" name="b_depth" value="0">
                    <input type="hidden" name="b_parentindex" value="">
                    <input type="hidden" name="b_board_type" id="b_board_type" value="1">
                    <input type="hidden" id="b_index" name="b_index" value="<?php echo($b_index);?>">
                    <input type="hidden" name="select_img" id="select_img">
                    <div style="margin:0 0 14px;">
                        <label class="input_tit">고객명</label>
                        <input type="text" attr="1" name="b_writer" id="b_writer"  class="input_txt" style="width:200px;margin-right:206px;" value=""/>
                        <label class="input_tit">비밀번호</label>
                        <input type="password" attr="1" name="b_password" id="b_password" class="input_txt" style="width:200px;">
                    </div>
                    <div style="margin-bottom:14px;">
                        <label class="input_tit" style="margin-right:13px;" >제목</label>
                        <input type="text" attr="1" id="b_title" name="b_title" class="input_txt" style="width:365px;margin-right:50px;" placeholder="제목을 입력해주세요"  value="" />
                        <label class="input_tit">E-mail</label>
                        <input type="text" attr="1"  name="b_email1" id="b_email1"  class="input_txt" style="width:66px;"   value="" />
                        @
                        <input type="text" attr="1" id="b_email2" name="b_email2" class="input_txt" style="width:138px;" value="" />
                        <select id="s_email" attr="1" title="E-Mail 선택" class="input_sel" style="width:80px;height:26px;" onChange="if(this.value==''){with(document.tx_editor_form){b_email2.readOnly=false;b_email2.value='';b_email2.focus();}}else{with(document.tx_editor_form){b_email2.readOnly=true;b_email2.value=this.value;}}">
                            <option value="">직접입력</option>
                            <option value="gmail.com">G메일</option>
                            <option value="naver.com">네이버</option>
                            <option value="nate.com">네이트</option>
                            <option value="daum.net">다음</option>
                            <option value="hanmail.net">한메일</option>
                            <option value="empal.com" >엠팔</option>
                            <option value="hotmail.com">핫메일</option>
                            <option value="msn.com">MSN</option>
                        </select>
                    </div>
                    <div style="margin-bottom:20px;">
                        <input type="checkbox" name="b_locked" class="textbox" value="Y" <?php ($b_code = "QANDA0")?"checked" : ""?>>
                        <font color="blue">※ 답변을 확인하실때 입력하신 비밀번호로 확인이 가능합니다.</font></br>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="blue">※ 사진을 첨부하신 뒤, 하단 파일첨부 영역에서 이미지 이름을 클릭하여, 메인이미지를 설정해주세요.</font>
                    </div>
                    <?php $this->load->view('editor.phtml');?>
                    <div style="height:25px;overflow:hidden;">
                            <span style="float:right;">
                                <input type="button" class="btn_gray" id="clear" value="다시작성">
                                <input type="button" class="btn_blue" onclick="saveContent()" value="등록">
                                <input type="button" class="btn_white" value="취소" onclick="javascript:history.back();">
                            </span>
                    </div>
                </div>
                </form>
            </div>
            <div style="height:200px;background:white;"></div>
        </div>
        <!--//contents_info-->
    </div>
</div>
<!-- 에디터 끝 -->

