<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/img_e/img_ecsaine.jpg" border="0" alt="">
    </div>
    <div id="" class="box_title3">
        <img src="/public_html/img_e/title_ecsaine01.jpg" border="0" alt="">
    </div>
    <div id="" class="box_full bgcolor-ivory4" style="height:987px;">
        <div id="" class="box_full_in_center" style="padding-top: 70px;">
            <div id="" class="fl_left bgcolor-white" style="padding-top: 77px;">
                <div id="" class="" style="padding-bottom: 60px;">
                    <img src="/public_html/img_e/titleimg_mat01.png" border="0" alt="">
                </div>
                <div id="" class="txt_just" style="width:523px; padding: 0 37px; padding-bottom:40px; line-height:28px;">
                    Original ECSAINE is a dream material that can enjoy all the advantages by turning disadvantages of conventional materials into advantages, which is neither leather nor fabric and nor artificial leather. The mystery of Original ECSAINE in all-in-one 3 dimensional net-shaped structure is made possible by the cutting-edge science that goes beyond the limits of existing material and that has excellent a property of matter. Until now, there is no product that reproduced Original ECSAINE as it stands throughout the world.
                </div>
                <div id="" class="" style="width:523px; padding: 0 37px; padding-bottom: 70px">
                    <img src="/public_html/img_e/mat01img_01.jpg" border="0" alt="">
                </div>
            </div>
            <div id="" class="fl_right bgcolor-white" style="padding-top: 77px;">
                <div id="" class="" style="padding-bottom: 60px;">
                    <img src="/public_html/img_e/titleimg_mat02.png" border="0" alt="">
                </div>
                <div id="" class="txt_just" style="width:523px; padding: 0 37px; padding-bottom:40px; line-height:28px;">
                    Original ECSAINE, a new genre material that is completely different from conventional materials, was developed by TORAY for the first time in the world. <br><br>
                    TORAY leads the global textile market and is in the best position to create original authority and first / highest / maximum value with original technical skills of Original ECSAINE. In addition, it has a system that binds the whole world in one quality and one operation system and that leads premium value development.

                </div>
                <div id="" class="" style="width:523px; padding: 0 37px; padding-bottom: 70px">
                    <img src="/public_html/img_e/mat01img_02.jpg" border="0" alt="">
                </div>
            </div>
        </div>
    </div>

    <div id="" class="box_full_in_center" style="padding-top:98px; overflow:hidden;">
        <div id="" class="fl_left">
            <img src="/public_html/img_e/mat01img_03.jpg" border="0" alt="">
        </div>
        <div id="" class="fl_right">
            <img src="/public_html/img_e/mat01img_04.jpg" border="0" alt="">
        </div>
    </div>

    <div id="" class="box_full_in_center" style="padding-top:98px;">
        <img src="/public_html/img_e/mat01img_05.jpg" border="0" alt="">
    </div>

    <div id="" class="box_full_in_center" style="padding-top:98px;">
        <img src="/public_html/img_e/mat01img_06.jpg" border="0" alt="">
    </div>

</div>