<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/img_e/img_manage01.jpg" border="0" alt="">
    </div>

    <div id="" class="box_full_in_center bgcolor-ivory4" style="height:1100px; margin-top:53px;">
        <div id="" class="" style="padding-top:58px;">
            <img src="/public_html/img_e/titleimg_mat09.png" border="0" alt="">
        </div>
        <div id="" class="box_w1040">
            <div id="" class="fl_left">
                <img src="/public_html/img_e/img_ecsaine11.jpg" border="0" alt="">
            </div>
            <div id="" class="fl_right">
                <img src="/public_html/img_e/img_ecsaine12.jpg" border="0" alt="">
            </div>
        </div>
    </div>
    <div id="" class="box_full_in_center" style="margin-top:110px;">
        <img src="/public_html/img_e/img_ecsaine19.jpg" border="0" alt="">
    </div>

    <div id="" class="box_full_in_center" style="margin-top:73px; height:290px; ">
        <div id="" class="fl_left" style="width:402px;">
            <img src="/public_html/img_e/img_ecsaine20.jpg" border="0" alt="">
        </div>
        <div id="" class="fl_right" style="width:600px; line-height:26px; text-align:justify; padding-right:40px;">
            <span class="" style="font-weight:bold;">Routine management </span>
            While using a sofa, gently wipe it with a soft wet towel that removes moist <br>along the direction of the Ecsaine texture at intervals of 1 to 2 weeks.
            <br><span class="" style="font-size:13px;">* Then, fine dust is removed and it can be managed in clean and healthy way.</span>
            <br>
            <span class="" style="font-weight:bold;">Regular management</span>
            While it can be regularly cared with wet towel, .HASSED has zipper structure to allow cushions, mattress covers and pillows for washing, if wanted. It is recommended to wash lightly with your hand, using a neutral detergent with lukewarm water of 30 degrees or less. When using a washing machine, please avoid strong dehydration or hot water and dry in a well-ventilated shade. Please avoid dry cleaning using chemicals.
        </div>
    </div>

    <div id="" class="box_full_in_center" style="margin-top:70px;">
        <img src="/public_html/img_e/img_ecsaine21.jpg" border="0" alt="">
    </div>


</div>