<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/img/img_manage01.jpg" border="0" alt="">
    </div>

    <div id="" class="box_full_in_center bgcolor-ivory4" style="height:1100px; margin-top:53px;">
        <div id="" class="" style="padding-top:58px;">
            <img src="/public_html/img/titleimg_mat09.png" border="0" alt="">
        </div>
        <div id="" class="box_w1040">
            <div id="" class="fl_left">
                <img src="/public_html/img/img_ecsaine11.jpg" border="0" alt="">
            </div>
            <div id="" class="fl_right">
                <img src="/public_html/img/img_ecsaine12-20181102.jpg" border="0" alt="">
            </div>
        </div>
    </div>
    <div id="" class="box_full_in_center" style="margin-top:110px;">
        <img src="/public_html/img/img_ecsaine19.jpg" border="0" alt="">
    </div>

    <div id="" class="box_full_in_center" style="margin-top:73px; height:290px; ">
        <div id="" class="fl_left" style="width:402px;">
            <img src="/public_html/img/img_ecsaine20.jpg" border="0" alt="">
        </div>
        <div id="" class="fl_right" style="width:640px; line-height:26px; text-align:justify; padding-right:40px;">
            <span class="" style="font-weight:bold;">일상적인 관리 </span>
            한 달에 1-2회 부드러운 천으로 따뜻한 물을 적셔 꼭 짠 다음 엑센느 결 방향에 따라 가볍게 닦아주면 외관상 보이지 않던 미세한 먼지까지 제거되어 깨끗하게 관리할 수 있습니다.
            <br><span class="" style="font-size:13px;">*단 부분적인 오염이 발생했을 경우, 즉각적으로 오염관리 지침에 따라 오염을 제거해주세요.</span>
            <br>
            <span class="" style="font-weight:bold;">정기적인 관리</span>
            일상적인 물수건 관리로 케어 가능하나, 정기적인 관리로 세탁을 원하실 경우 헷세드 쿠션, 매트리스 커버, 베게 등은 물세탁 할 수 있게 지퍼 처리가 되어있습니다. 30도 이하의 미온수로 중성 세제를 사용하여 가볍게 손세탁하는 것이 좋습니다. 세탁기를 사용할 경우, 강한 탈수나 온수는 피해주시고, 통풍이 잘 되는 그늘에 말려주세요. 화학제를 사용하는 드라이클리닝은 삼가주세요.
        </div>
    </div>

    <div id="" class="box_full_in_center" style="margin-top:70px;">
        <img src="/public_html/img/img_ecsaine21.jpg" border="0" alt="">
    </div>


</div>