<link rel="stylesheet" type="text/css" href="<?php echo CSS_MOBILE_DIR;?>/set_text.css" />
<link rel="stylesheet" type="text/css" href="<?php echo CSS_MOBILE_DIR;?>/brand_style.css" />
<script type="text/javascript" src="/public_html/js/br_sliderN.js"></script>
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/img/img_brand.jpg" border="0" alt="">
    </div>
    <div class="box_center" style="margin-top:90px;">
        <img src="/public_html/img/title_brand01.jpg" border="0" alt="">
    </div>
    <div id="" class="slide_mask">
        <div class="brand_slideN">
            <div id="bs01" class="">
                <img src="/public_html/img/br_slide01.jpg" border="0" alt="">
            </div>
            <div id="bs02" class="">
                <img src="/public_html/img/br_slide02.jpg" border="0" alt="">
            </div>
            <div id="bs03" class="">
                <img src="/public_html/img/br_slide03.jpg" border="0" alt="">
            </div>
            <div id="bs04" class="">
                <img src="/public_html/img/br_slide04.jpg" border="0" alt="">
            </div>
            <div id="bs05" class="">
                <img src="/public_html/img/br_slide05.jpg" border="0" alt="">
            </div>

        </div>
        <div id="" class="brand_slide_mask">
            <img src="/public_html/img/br_slide_mask.png" border="0" alt="">
        </div>
        <div id="bt_br_left" class="brand_slide_bt_leftN">
            <a href="#1"><img src="/public_html/img/br_slide_bt_l.png" border="0" alt=""></a>
        </div>
        <div id="bt_br_right" class="brand_slide_bt_rightN">
            <a href="#2"><img src="/public_html/img/br_slide_bt_l.png" border="0" alt=""></a>
        </div>
    </div>
    <div id="" class="box_center" style="border-top:1px solid #000;">
        <img src="/public_html/img/title_brand04-200605.jpg" border="0" alt="">
    </div>
    <div class="box_center" style="display:block;">
        <div id="" class="fl_left pad-left">
            <img src="/public_html/img/img_brand12.jpg" border="0" alt="">
        </div>
        <div id="" class="fl_right">
            <div id="" class="txtform01 txt_just pad-right">
                <span class="txtintitle">일상생활 패턴</span> 서양의 거실과 호텔 로비, 카페 등 입식공간에서는 일시 오가며 신발을 신고 생활합니다. 때문에 일시적 오가며 앉을 수 있는 의자형태를 추구합니다.  반면, 가정의 좌식 공간에서는 오랜 시간 편안히 앉고, 눕고, 기대며 자유로운 자세를 마음껏 취할 수 있는 소파형태를 추구합니다.
            </div>
            <div id="" class="txtform01 txt_just pad-right" style="margin-top:16px;">
                <span class="txtintitle">일상 피부 접촉</span> 서양의 주택 및 상업시설의 입식 공간과는 달리, 오늘날 그리고 미래의 가정은 4계절 내내 입실 하자마자 샤워 후 가벼운 옷차림으로 생활을 합니다. 따라서 소파와 침대는 장시간 피부와의 접촉이 불가피합니다. 때문에 헷세드는 전 공정에서 친환경 시스템과 엄선된 친환경 소재를 사용합니다.
            </div>
            <div id="" class="txtform01 txt_just pad-right" style="margin-top:16px;">
                <span class="txtintitle">헷세드 공학(工學)</span> .HASSED는 어떤 자세에서도 행복한 생활리듬과 건강한 인체 균형을 편안하게 유지하는 것을 기본으로 하며, 체형이나 각기 다른 거실 형태에 맞출 수 있는 생산체계를 갖춤으로써 누구에게나 일상생활에서의 만족을 전하는 것을 사전 전제 조건으로 설계합니다.
            </div>

        </div>
    </div>
    <div id="" class="box_center" style="border-top:1px solid #000; margin-top:87px;">
        <img src="/public_html/img/title_brand05-200605.jpg" border="0" alt="">
    </div>
    <div class="box_center">
        <div id="" class="fl_left pad-left">
            <img src="/public_html/img/img_brand13.jpg" border="0" alt="">
        </div>
        <div id="" class="fl_right">
            <div id="" class="txtform01 txt_just pad-right">
                <span class="txtintitle">가정의 정서</span> 순간의 각인과 구매 충동을 일으키는 상업적 음영의 멋이 아닌, 온 가족이 일상 속에서 멋진 아름다움으로 화목이 넘치는 헷세드가정의 모습을 기본 전제하에 디자인합니다. 또한 시각적인 형태와 색감, 질감은 사람의 생각과 마음, 태도까지 매우 큰 영향을 끼칩니다. 헷세드는 가정의 행복과 건강을 전할 수 있는 아름다운 정서를 기본 전제합니다.
            </div>
            <div id="" class="txtform01 txt_just pad-right" style="margin-top:16px;">
                <span class="txtintitle">비전과 감동</span> 오늘날의 주택은 첨단 건축기술로 고층을 지향하며 실내의 환한 전체 채광을 중요시합니다. 자연채광에서는 모든 사실이 드러나기에  헷세드는 아름다운 컬러와 섬세한 촉감을 가정에 더 큰 비전과 감동으로 전제합니다.
            </div>
            <div id="" class="txtform01 txt_just pad-right" style="margin-top:16px;">
                <span class="txtintitle">헷세드 미학(美學)</span> .HASSED는 가정마다 각기 다른 환경에서도 모든이가 감동하는 라이프스타일에 최적화된 디자인을 전제합니다. 또한 멋진 아름다움으로 사람 본연에 자리 잡은 소망을 충족시키는 것을 사전 전제하에 디자인 합니다.
            </div>

        </div>
    </div>
    <div class="sub_img_m">
	<img src="/public_html/m/images/bg/mobile-top.png" width="1080px" border="0" alt="">
        <img src="/public_html/m/images/hassed_smart-brand3.jpg" width="1080px" border="0" alt="">
	<img src="/public_html/m/images/hassed_smart-brand4.jpg" width="1080px" border="0" alt="">
    </div>
</div>
