<link rel="stylesheet" type="text/css" href="<?php echo CSS_MOBILE_DIR;?>/brand_style.css" />
<div id="" class="wrap_middle">
    <div id="" class="box_full bgcolor-ivory5">
        <div class="sub_img">
            <img src="/public_html/img/img_greeting03.png" border="0" alt="">
        </div>
    </div>

    <div id="" class="box_white_ceo">
        <ul>
            <li>
                <img src="/public_html/img/ceo_photo.png" border="0" alt="">
            </li>
            <li>
                <div id="" class="box_white_ceo_txt" style="line-height:24px;">
                    <img src="/public_html/img/title_greeting.png" border="0" alt=""><br>

                    안녕하세요!<br>
                    대표이사 김기욱입니다. <br><br>

                    헷세드를 사랑해 주시는 많은 고객님들께
                    진심으로 감사드립니다. <br><br>

                    2010년 세계최고 및 국내 유일하게<br>
                    Original ECSAINE 전문 메이커브랜드로써 설립된 헷세드는 <br>
                    소중한 가족들과 함께<br>
                    가정의 멋진 아름다움과 화목, 행복과 건강을 바라보며<br>
                    감동을 만들어왔습니다. <br><br>

                    헷세드는 고객님과 함께<br>
                    감동에 감동을 이루어 갈 것을 약속합니다.<br><br>

                    감사합니다.
                </div>
            </li>
        </ul>
    </div>

    <div id="" class="box_full" style="height:407px;">
        <div id="" class="box_center" style="border-top:1px solid #000;">
            <div id="" class="box_color6_div01 pad-left">
					<span class="title_middle">
					오직, 가정을 위한 가구로 <br>
					헷세드의 감동은 시작됩니다</span>

                <div id="" class="txt_base01">

                    오늘날 그리고 미래의 라이프스타일은 4계절 내내 최적의 온도를 유지하며, 실내에서 가벼운 옷차림으로 생활하기 때문에 소파, 침대와 같은 가구는 우리의 피부와 장시간 스킨십하게 됩니다.  또한 주거환경은 과거 서양의 어둡고 침침한  입식주택과는 달리, 환한 전망과 밝은 채광을 선호합니다. 때문에 실내의 미세먼지와 흠집, 소재의 질감과 색감 등 생활 속 모든 단점들이 그대로 드러납니다. <br>
                    라이프스타일의 변화에 따라 가구의 선택도 밝은 채광에서 그대로 드러나는 아름다운 색감과 질감, 그리고 피부와 인체친화성을 고려하지 않을 수 없습니다. 헷세드의 감동은 온 가족의 화목과 행복, 건강을 바라봄에 있습니다.

                </div>
            </div>
            <div id="" class="box_color6_div02 pad-right">
					<span class="title_middle">
					행복한 가정을 생각하는<br>
					진정성이 헷세드의 가치입니다</span>

                <div id="" class="txt_base01">

                    세계 섬유시장을 리드하고 있는 TORAY社의 Original ECSAINE를 독점 계약한 헷세드는 2010년 국내 최초로 Original ECSAINE 제품을 출시하게 되었으며, 자체 공장 운영 시스템하에 그동안 볼 수 없었던 프리미엄 제품으로써 거실 문화의 새로운 비전을 제시하였습니다. 가정은 온 가족이 정서적 교류를 하는 공간입니다. 따라서 연출된 지식적 멋으로 꾸미는 상업공간과 다릅니다. <br>
                    가정의 정서를 고려한 헷세드는 매일같이 소중한 가족들과 함께 어우러지는 멋진 아름다움, 화목, 행복, 건강을 바라보며 그것을 향한 열정을 전제합니다.
                </div>
            </div>

        </div>
    </div>
</div>