    <div id="" class="wrap_middle">
        <div class="sub_img">
            <img src="/public_html/img/img_about.jpg" border="0" alt="">
        </div>
        <div id="" class="box_color bgcolor-pink">
            <div id="" class="imgtitle" style="padding-top:50px; height:150px;">
                <img src="/public_html/img/copy_com02_01.png" border="0" alt="">
            </div>
            <div id="" class="comtext01" style="text-align:center;">
                .HASSED는<br>
                <span class="" style="color:#94282d; font-weight:bold; margin-top:20px;">1970′ </span>
                세계최초개발 / 세계최대규모 / 세계최고의 원천기술로써 <br>
                전 세계 섬유시장을 리드하고 있는 TORAY 社의 Original ECSAINE를 국내 최초 도입과 동시 국내에 단독 공식 파트너 회사로서 설립되었습니다. <br><br>


                <span class="" style="color:#94282d; font-weight:bold;">2010′</span>
                헷세드는 세계 섬유시장의 베스트 위치에 있는 Original ECSAINE를 통한 품격 있는 디자인과 최상의 품질로써 <br> 세계최초 소파&침대 전문 브랜드를 런칭하여
                각 가정에 멋진 아름다움과 화목, 행복과 건강을 <br>감동으로 전하는 새로운 문화를 창출하고 있습니다.  <br><br><br>
            </div>
        </div>
        <div id="" class="div1danp20 bgcolor-pink">
            <div id="" class="div_brand">
                <div id="" class="fl_left bgcolor-white" style="height:744px; border: 1px solid #b86f73;">
                    <img src="/public_html/img/brand_img02.jpg" border="0" alt="">
                    <div class="comtext02" style="font-size:16px; font-weight:500">
                        .HASSED는 소중한 가족들과 함께 호흡하는 건강하고 편안한 제품으로 가정의 멋진 아름다움과 화목, 행복과 건강을 바라 봅니다.<br>

                        <div id="" class="" style="margin-top:10px; font-size:15px; font-weight:400">
                            또한, 단순 매입 후 판매하는 이분법 시스템으로 운영되는 일반 유통 브랜드가 아닌, <span class="" style="font-weight:bold; display:inline-block; color:#91242a;">[연구개발 / 디자인 / 생산 / 판매 / 배송 / 서비스]</span>가 원스탑 시스템으로 자체적으로 운영되는 메이커 브랜드로서 고객님께 감동을 지속적으로 제공하는 정체성을 지녔습니다.
                        </div>
                    </div>
                </div>
                <div id="" class="fl_right bgcolor-gray" style="width:506px; height:744px;">
                    <img src="/public_html/img/brand_img03_0.jpg" border="0" alt="">
                    <div id="" class="box_since">
                        <div id="" class="bt_pluse">
                            <a href="javascript:windOPE3();"><img src="/public_html/img/bt_since.jpg" border="0" alt=""></a>
                        </div>
                        <div id="" class="box_since_txt">
                            Since its founding in 1926, Toray has kept expanding through business development in wide-range of areas. Starting from rayon filament production, Toray has developed various products such as polyester, nylon and acrylic fibers as well as high-performance films, engineering plastic resins, carbon fiber composite materials, electronics and information related products, high-performance membranes, pharmaceuticals and medical products.
                        </div>

                    </div>
                    <div id="" class="comtext03" style="margin-top:70px;">
                        <span class="" style="font-weight:bold;">TORAY에 의해 세계최초개발</span>
                        [아담과 이브 이후 최대의 혁신적 소재]로 뉴욕타임스 등 토픽으로 이슈 된 이후 소중한 가정에 최고급 시트로 사용하면서 [기존 소재의 한계점과 불편했던 단점을 해결한 꿈의 소재]로 전 세계에 센세이션을 불러일으켰습니다. 오늘날까지 세계최초개발을 이어 세계최대규모, 세계 최고기술력까지 보유함으로써 세계적 명품으로 인정받고 있습니다.
                    </div>
                </div>
            </div>
        </div>
        <div id="" class="div1dan" style="padding-top:90px;">
            <img src="/public_html/img/oekotex20180626.jpg" border="0" alt="">
        </div>
        <div id="" class="div1dan bgcolor-pink" style="margin-top:80px; height:1655px;">
            <img src="/public_html/img/history-20200822.jpg" border="0" alt="">
            <div id="" class="" style="position:relative; width:658px; height:389px; margin-top:-955px; left:367px;">
               <iframe id="player" type="text/html" width="658" height="374" src="https://player.vimeo.com/video/286002501" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
            </div>

            <div id="" class="" style="position:relative; width:658px; height:374px; margin-top:55px; left:367px;">
                 <iframe id="player" type="text/html" width="658" height="374" src="https://player.vimeo.com/video/215112333" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
            </div>
        </div>
    </div>
</div>


