<div id="" class="wrap_middle">
    <div id="" class="box_full bgcolor-ivory5">
        <div class="sub_img">
            <img src="/public_html/img_e/img_greeting03.png" border="0" alt="">
        </div>
    </div>

    <div id="" class="box_white_ceo">
        <ul>
            <li>
                <img src="/public_html/img_e/ceo_photo.png" border="0" alt="">
            </li>
            <li>
                <div id="" class="box_white_ceo_txt" style="line-height:24px;">
                    <img src="/public_html/img_e/title_greeting.png" border="0" alt=""><br>

                    Hello!<br>This is KIM KI UG, CEO of .HASSED. <br><br>

                    I deeply appreciate to our valuable customers <br>who love .HASSED. <br><br>

                    Founded in 2010 as the world's best and <br>the only Original ECAINE brand in Korea, <br>.HASSED has created impression, <br>pursuing wonderful beauty, harmony, <br>happiness and health of our family <br>with our loved ones. <br><br>

                    We promise to create a lasting impression with our customers.<br><br>

                    Thank you.
                </div>
            </li>
        </ul>
    </div>

    <div id="" class="box_full" style="height:480px;">
        <div id="" class="box_center" style="border-top:1px solid #000;">
            <div id="" class="box_color6_div01">
					<span class="title_middle">
					Impression of .HASSED begins with <br>furniture only for house</span>

                <div id="" class="txt_base01">

                    Today and future lifestyles keep optimal temperature throughout all four seasons and people wear light clothes inside the house. Thus, it is inevitable to make a skin contact with sofa and beds for a long time. Unlike dark and dull standing style space in the west, people prefer to clear view and bright lighting. Therefore, all the disadvantages in life such as fine dust and scratches in interior, texture and color of material are revealed. As for the selection of furniture that depends on the lifestyle change, people have to consider natural and beautiful color, texture, skin and ergonomics, which reveal itself in bright light. Impression of .HASSED focuses on harmony, happiness and health of all families.

                </div>
            </div>
            <div id="" class="box_color6_div02">
					<span class="title_middle">
					Authenticity for happy family is <br>the real value of .HASSED</span>

                <div id="" class="txt_base01">

                    With exclusive contract with Original ECSAINE of TORAY which is leading the global textile market, .HASSED launched the original ECSAINE product in Korea for the first time in 2010 and presented a new vision of living room culture as a premium product that was not available under its own factory operation system. Home is a place where the whole family makes an emotional exchange. Therefore, it differs from commercial space decorated with knowledge and fashion. Considering emotion of the family, .HASSED presupposes a passion for it by pursuing the wonderful beauty, harmony, happiness and health with the precious family every day.

                </div>
            </div>

        </div>
    </div>
</div>