<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<div id="" class="wrap_middle">

    <div class="sub_img">
        <img src="/public_html/imgpro/img_ailish.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_ailish.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            This bed puts worries to sleep
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/img_alish02-2.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            red color
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/img_alish02-3.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/img_alish02-4.jpg" border="0" alt="">
        </div>
        <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_premium.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>


<!--
    <div id="" class="box_colorfull">
        <div class="box_contents3">
            <div id="" class="fl_left">
                <div id="" class="txt_concept">
                    <div id="" class="txt_concept_div02">
                        ailish design concept
                    </div>
                    <div id="" class="txt_concept_div03">
                        purple color
                    </div>
                    <div id="" class="txt_concept_div04">
                        아기의 맨살처럼 부드러운 촉감, 프리미엄 친환경 침대<br>
                        사선으로 떨어지는 모던한 라인으로 감각적인 디자인
                    </div>
                </div>
            </div>
            <div id="" class="fl_right conceptimg">
                <img src="/public_html/imgpro/img_ailish02.jpg" border="0" alt="">
            </div>
        </div>
    </div>
-->

    <div id="" class="box_design">
        <img src="/public_html/imgpro/img_ailish03.jpg" border="0" alt="">
    </div>

    <div id="" class="box_colorfull" style="height:320px;" style="z-index:-100;">
        &nbsp;&nbsp;
    </div>
    <div id="" class="title_prince" style="">
        <img src="/public_html/imgpro/title_prince.png" border="0" alt="">
    </div>

    <div id="" class="box_prince">
        <img src="/public_html/imgpro/img_prince.jpg" border="0" alt="">
    </div>

    <div id="" class="" style="width:1080px; margin:0 auto; z-index:30; margin-top:460px; ">
        <img src="/public_html/imgpro/img_prince01.jpg" border="0" alt="">
    </div>

    <!-- topmenu ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- topmenu ////////////////////////////// -->

</div>