<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<div id="" class="wrap_middle">

    <div class="sub_img">
        <img src="/public_html/imgpro/img_ailish.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_ailish.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            This bed puts worries to sleep
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/ailish.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            red in color
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/ailish_1.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/ailish_2.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/ailish_3.jpg" border="0" alt="">
        </div>
        <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_premium.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>

	<div id="" class="box_design">
	<img src="/public_html/imgpro/dem_ailish04.png" border="0" alt="">
	</div>



<br><br><br><br><br><br>
<div class="sub_img">
        <img src="/public_html/imgpro/img_prince-20190219.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_prince.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            Simple, slim minimalism design bed, prince
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/prince.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            coral in color
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/prince-1.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/prince-2.jpg" border="0" alt="">
        </div>

</div>


    <div id="" class="" style="width:1080px; margin:0 auto; z-index:30; margin-top:100px; ">
        <!--  <img src="/public_html/imgpro/img_prince01.jpg" border="0" alt=""> -->
	<img src="/public_html/imgpro/dem_prince04.png" border="0" alt="">
    </div>

    <!-- topmenu ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- topmenu ////////////////////////////// -->

</div>