<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<link rel="stylesheet" type="text/css" href="/public_html/css/promain-m.css" />
<div id="" class="wrap_middle">

    <div class="sub_img">
        <img src="/public_html/imgpro/img_amore.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_amore.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            Stable design with soft frame
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/amore.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            green in color
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/amore_1.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/amore_2.jpg" border="0" alt="">
        </div>
        <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_premium.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>
	
		<div class="box_detail">
	<h1>Amore</h1>

    <img src="/public_html/vr360/img-amore/001.jpg" width="1000" height="700"
      class="reel"
      id="image"
      data-images="/public_html/vr360/img-amore/###.jpg"
      data-frames="144"
      data-frame="14"
      data-rows="3"
      data-row="3"
      data-speed="0.1">
		</div>


<div id="" class="box_design" style="border:0px solid #ddd; margin-top:0px; padding-top:50px;">
        <!--<img src="/public_html/imgpro/img_amore03.jpg" border="0" alt="">-->
	<img src="/public_html/imgpro/dim-bed-amore-211026.jpg" border="0" alt="">
    </div>

    <div class="menuprolist">
 <a href="/product" ><img src="/public_html/m/images/menu-prolist.png"></a>
</div>


    <!-- topmenu ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- topmenu ////////////////////////////// -->

</div>