<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/imgpro/img_calix.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_calix.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            plain and sensible minimalist design
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/calix.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            purple color
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/calix_1.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/calix_2.jpg" border="0" alt="">
        </div>
        <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_special.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>



<!--
    <div id="" class="box_colorfull">
        <div class="box_contents3">
            <div id="" class="fl_left">
                <div id="" class="txt_concept">
                    <div id="" class="txt_concept_div02">
                        calix design concept
                    </div>
                    <div id="" class="txt_concept_div03">
                        blue color
                    </div>
                    <div id="" class="txt_concept_div04">
                        모던함을 강조한 세련된 디자인<br>
                        시크한 느낌에 섬세한 라인을 살린 디자인
                    </div>
                </div>
            </div>
            <div id="" class="fl_right conceptimg">
                <img src="/public_html/imgpro/img_calix02.jpg" border="0" alt="">
            </div>
        </div>
    </div>
-->


    <div id="" class="box_design">
        <img src="/public_html/imgpro/img-calix04.png" border="0" alt="">
    </div>
    <!-- delivery ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- delivery ////////////////////////////// -->
</div>