<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<link rel="stylesheet" type="text/css" href="/public_html/css/promain-m.css" />
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/imgpro/img_crane.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_crane.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            The young European sensibility is reflected on the sofa
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/crane.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            coral in color
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/crane_1.jpg" border="0" alt="">
        </div>
	 <div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/crane_2.jpg" border="0" alt="">
        </div>
        <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_special.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>


<!--
    <div id="" class="box_colorfull">
        <div class="box_contents3">
            <div id="" class="fl_left">
                <div id="" class="txt_concept">
                    <div id="" class="txt_concept_div02">
                        crane design concept
                    </div>
                    <div id="" class="txt_concept_div03">
                        sky color
                    </div>
                    <div id="" class="txt_concept_div04">
                        넓고 편리한 좌석과 등받이의 안락함<br>
                        젊고 세련된 도시 감각적인 디자인
                    </div>
                </div>
            </div>
            <div id="" class="fl_right ">
                <img src="/public_html/imgpro/img_crane02.jpg" border="0" alt="">
            </div>
        </div>
    </div>
-->

    <div id="" class="box_design">
        <img src="/public_html/imgpro-2022/dim-sofa-crane-20220308.jpg" border="0" alt="">
    </div>

<div class="menuprolist">
 <a href="/product" ><img src="/public_html/m/images/menu-prolist.png"></a>
</div>


    <!-- delivery ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- delivery ////////////////////////////// -->
</div>