<link rel="stylesheet" type="text/css" href="/public_html/css_e/h_product.css" />
<div id="" class="wrap_middle">

    <div class="sub_img">
        <img src="/public_html/imgpro_e/img_whistle.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro_e/title_whistle.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            It attracts attention with its unique design
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/img_whistle02-2.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            grey color
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/img_whistle02-3.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/img_whistle02-4.jpg" border="0" alt="">
        </div>
        <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('e_frame_special.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>


<!--
    <div id="" class="box_colorfull">
        <div class="box_contents3">
            <div id="" class="fl_left">
                <div id="" class="txt_concept">
                    <div id="" class="txt_concept_div02">
                        whistle design concept
                    </div>
                    <div id="" class="txt_concept_div03">
                        south beach color
                    </div>
                    <div id="" class="txt_concept_div04">
                        Recliner sofa with mechanical design and solidity<br>
                        Completed interior with unique design
                    </div>
                </div>
            </div>
            <div id="" class="fl_right conceptimg">
                <img src="/public_html/imgpro_e/img_whistle02.jpg" border="0" alt="">
            </div>
        </div>
    </div>
-->



    <div id="" class="box_design">
        <img src="/public_html/imgpro_e/img_whistle03.jpg" border="0" alt="">
    </div>
    <!-- delivery ////////////////////////////// -->
    <?php $this->load->view('e_frame_delivery.phtml');?>
    <!-- delivery ////////////////////////////// -->

</div>