<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<link rel="stylesheet" type="text/css" href="/public_html/css/promain-m.css" />
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/imgpro/img_floria.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_floria.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            It reflects dignity and elegance beyond the living room
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/floria.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            southbeach in color
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/floria_1.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/floria_2.jpg" border="0" alt="">
        </div>
        <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_special.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>


<!--
    <div id="" class="box_colorfull">
        <div class="box_contents3">
            <div id="" class="fl_left">
                <div id="" class="txt_concept">
                    <div id="" class="txt_concept_div02">
                        floria design concept
                    </div>
                    <div id="" class="txt_concept_div03">
                        red color
                    </div>
                    <div id="" class="txt_concept_div04">
                        거실의 품격을 높이는 세미클래식 디자인<br>
                        안락함과 편안함을 생각한  높은 등쿠션
                    </div>
                </div>
            </div>
            <div id="" class="fl_right conceptimg">
                <img src="/public_html/imgpro/img_floria02.jpg" border="0" alt="">
            </div>
        </div>
    </div>
-->

    <div id="" class="box_design">
        <img src="/public_html/imgpro-2022/dim-sofa-floria-20220308.jpg" border="0" alt="">
    </div>

<div class="menuprolist">
 <a href="/product" ><img src="/public_html/m/images/menu-prolist.png"></a>
</div>


    <!-- delivery ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- delivery ////////////////////////////// -->
</div>