<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/imgpro/img_mobilian.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_mobilian.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            simple design combined with rich story and superb functionality
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/mobilian.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            green in color
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/mobilian_1.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/mobilian_2.jpg" border="0" alt="">
        </div>
         <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_premium.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>


<!--
    <div id="" class="box_colorfull">
        <div class="box_contents3">
            <div id="" class="fl_left">
                <div id="" class="txt_concept">
                    <div id="" class="txt_concept_div02">
                        mobilian design concept
                    </div>
                    <div id="" class="txt_concept_div03">
                        green color
                    </div>
                    <div id="" class="txt_concept_div04">
                        우리 가족만의 시크릿한 공간 연출
                    </div>
                </div>
            </div>
            <div id="" class="fl_right conceptimg">
                <img src="/public_html/imgpro/img_mobilian03.jpg" border="0" alt="">
            </div>
        </div>
    </div>
-->

    <div id="" class="box_design">
        <img src="/public_html/imgpro/dim-bed-mobilian-200514.jpg" border="0" alt="">
    </div>

    <!-- delivery ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- delivery ////////////////////////////// -->
</div>