<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<link rel="stylesheet" type="text/css" href="/public_html/css/promain-m.css" />
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/m/images/hassed_smart-company1.jpg" width="1080" border="0" alt="">
	<img src="/public_html/m/images/hassed_smart-company2.jpg" width="1080" border="0" alt="">
    </div>
</div>