<link rel="stylesheet" type="text/css" href="<?php echo CSS_DIR; ?>/board_hassed_mobile.css" />
<link href='http://fonts.googleapis.com/css?family=Libre+Baskerville' rel='stylesheet' type='text/css'>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="<?php echo JS_DIR; ?>/bbs.js"></script>
<script src="<?php echo JS_DIR; ?>/slider/jquery.bxslider.min.js"></script>


<link href="<?php echo JS_DIR; ?>/slider/jquery.bxslider.css" rel="stylesheet" />

<div id="wrap_middle" class="" style="">
    <div id="" class="box_full">
        <div class="sub_img">
            <img src="/public_html/img/img_board_main.png" border="0" alt="">
        </div>
        <div id="" class="" style="width:100%; height:308px; position:absolute; background-color:#faf8f6; display:block; z-index:-10; margin-top:-570px;">
        </div>
    </div>
    <div id="" class="box_full_in_center">
        <!--contents_info-->
        <div id="">

            <div class="wrap_board" id="tj_content">
                <div class="board_area">
                    <div id="" class="">
                        <img src="/public_html/m/images/title_popular_review-2020.png" width="1080" height="80" border="0" alt="">
                    </div>
                    <div class="gallery_pop_out">
                        <div class="imglist">
                            <div class="setbox">
                                <div id="slider-prev"></div>
                                <div class="centerlist">
                                    <div class="bx-wrapper" style="max-width: 1030px; margin: 0px auto;">
                                        <div class="bx-viewport" style="width: 100%; overflow: hidden; position: relative; height: 193px;">
                                            <ul class="bxslider" style="width: 1415%; position: relative; transition-duration: 0.7s; transform: translate3d(-1800px, 0px, 0px);"></ul>
                                        </div>
                                    </div>
                                </div>
                                <div id="slider-next"></div>
                            </div><!-- setbox end -->
                        </div><!-- imglist end -->
                    </div>
                    <div id="" class="gallery_copyright">
                        헷세드는 지난 10년간 상업적인 광고없이 고객님의  감동으로 성장하였습니다.<br>
                        가정의 멋진 아름다움과 행복을 후기로 공유해주세요!
                    </div>


                    <!-- 고객후기 list -->
		   
                    <div id="" class="gallery_title">
                        <img src="/public_html/m/images/title_customer_review-2020.png" width="1080" height="80" border="0" alt="">
                    </div>
			



                    <!-- 글쓰기 버튼 // -->
                    <div id="" class="gallery_write">
                        <div class="bt_write">
                            <a href="javascript:write();"><img src="/public_html/m/images/bg/btn-write.png" border="0" alt="글쓰기"></a>
                        </div>
                    </div>


                    <div class="gallery_out">
		    
		    <div class="gallery_set">
			<div class="gallery_list">
				<div class="thumb"></div>
			</div>
			<div class="gallery_list">
				<div class="thumb"></div>
			</div>
			<div class="gallery_list">
				<div class="thumb"></div>
			</div>
			<div class="gallery_list">
				<div class="thumb"></div>
			</div>
			<div class="gallery_list">
				<div class="thumb"></div>
			</div>
			<div class="gallery_list">
				<div class="thumb"></div>
			</div>
			<div class="gallery_list">
				<div class="thumb"></div>
			</div>
			<div class="gallery_list">
				<div class="thumb"></div>
			</div>
			<div class="gallery_list">
				<div class="thumb"></div>
			</div>
			<div class="gallery_list">
				<div class="thumb"></div>
			</div>
			<div class="gallery_list">
				<div class="thumb"></div>
			</div>
			<div class="gallery_list">
				<div class="thumb"></div>
			</div>
			<div class="gallery_list">
				<div class="thumb"></div>
			</div>
			<div class="gallery_list">
				<div class="thumb"></div>
			</div>
			<div class="gallery_list">
				<div class="thumb"></div>
			</div>
		    </div>

		    
		    </div>
                    <br>
                    <!-- <span class="under_line">밑선</span> -->
                    <!-- Default List // -->
                    <div id="" class="" style="width:1080px; height:10px; margin-top:20px; border-top:solid 1px #666;"></div>
                    <div id="total_page" style="margin:10px 0 20px; float:left; "></div>
                    <!-- Pagination -->
                    <div class="bbs_page paging"></div>
                    <!-- Pagination // -->
                    <div id="" class="gallery_write" style="height:0px;">
                        <div class="bt_writebot">
				<a href="javascript:write();"><img src="/public_html/m/images/bg/btn-write.png" border="0" alt="글쓰기"></a>
			</div>
                    </div>
                    
                </div>
            </div>
            <!--//contents_info-->
        </div>
    </div>
</div>

