<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<link rel="stylesheet" type="text/css" href="/public_html/css/promain-m.css" />
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/imgpro/img_mors01.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_mors.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            Modern and beautifully restrained styled design
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/mors.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/mors_1.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/mors_2.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            green in color
        </div>
        <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_special.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>

    <div id="" class="box_design">
        <img src="/public_html/imgpro/dim-sofa-mors-200514.jpg" border="0" alt="">
    </div>

<div class="menuprolist">
 <a href="/product" ><img src="/public_html/m/images/menu-prolist.png"></a>
</div>


    <!-- delivery ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- delivery ////////////////////////////// -->
</div>