<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<link rel="stylesheet" type="text/css" href="/public_html/css/promain-m.css" />
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/imgpro/img_offe.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_offe.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            Unique design sofa, simple & modern lines with asymmetrical design
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/offe.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            sky blue in color
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/offe_1.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/offe_2.jpg" border="0" alt="">
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/offe_3.jpg" border="0" alt="">
        </div>
        <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_special.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>


<!--
    <div id="" class="box_colorfull">
        <div class="box_contents3">
            <div id="" class="fl_left">
                <div id="" class="txt_concept">
                    <div id="" class="txt_concept_div02">
                        offe design concept
                    </div>
                    <div id="" class="txt_concept_div03">
                        sweet violet color
                    </div>
                    <div id="" class="txt_concept_div04">
                        모던하고 간결한 라인과 팔걸이의 좌우 비대칭이 <br>특징인 독창적 디자인

                    </div>
                </div>
            </div>
            <div id="" class="fl_right conceptimg">
                <img src="/public_html/imgpro/img_offe03.jpg" border="0" alt="">
            </div>
        </div>
    </div>
-->

    <div id="" class="box_design">
        <img src="/public_html/imgpro/dim-sofa-offe-211130.jpg" border="0" alt="">
    </div>


<div class="menuprolist">
 <a href="/product" ><img src="/public_html/m/images/menu-prolist.png"></a>
</div>


    <!-- delivery ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- delivery ////////////////////////////// -->
</div>