<link rel="stylesheet" type="text/css" href="/public_html/css/h_product.css" />
<link rel="stylesheet" type="text/css" href="/public_html/css/promain-m.css" />
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/imgpro/img_settle201.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_settle2.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
            A luxurious design seek like an independant piece of art
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/settle.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            coral in color
        </div>
        <div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/settle_1.jpg" border="0" alt="">
        </div>
	 <div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/settle_2.jpg" border="0" alt="">
        </div>
        <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_special.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>

<div class="menuprolist">
 <a href="/product" ><img src="/public_html/m/images/menu-prolist.png"></a>
</div>

    <div id="" class="box_design">
        <img src="/public_html/imgpro/dim-sofa-settle-200514.jpg" border="0" alt="">
    </div>


<br><br><br><br><br><br>
<!-- settle 3333333333333333 ////////////////////////////// -->


    <div class="sub_img">
        <img src="/public_html/imgpro/img_settle301.jpg" border="0" alt="">
    </div>
    <div class="box_title">
        <img src="/public_html/imgpro/title_settle3.png" border="0" alt="">
    </div>
    <div class="box_outline">
        <div class="div_img_left_txt div90do1">
           A lovely design sofa which can be placed in various purposes
        </div>
        <div id="" class="div_proimg_center">
            <img src="/public_html/imgpro/settle3.jpg" border="0" alt="">
        </div>
        <div class="div_img_right_txt div90do1">
            coral in color
        </div>
	<div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/settle3_1.jpg" border="0" alt="">
        </div>
	 <div id="" class="div_proimg_center-2">
            <img src="/public_html/imgpro/settle3_2.jpg" border="0" alt="">
        </div>
        <!-- frame_special ////////////////////////////// -->
        <?php $this->load->view('frame_special.phtml');?>
        <!-- frame_special ////////////////////////////// -->
    </div>

	<div id="" class="box_design">
        <img src="/public_html/imgpro/dim-sofa-settle3-200514.jpg" border="0" alt="">
    </div>


    <!-- delivery ////////////////////////////// -->
    <?php $this->load->view('frame_delivery.phtml');?>
    <!-- delivery ////////////////////////////// -->
</div>