<link rel="stylesheet" type="text/css" href="<?php echo CSS_DIR; ?>/board_hassed_2017.css" />
<link href='http://fonts.googleapis.com/css?family=Libre+Baskerville' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="/public_html/d_editor/css/editor.css" type="text/css" charset="utf-8"/>
<script src="/public_html/d_editor/js/editor_loader.js" type="text/javascript" charset="utf-8"></script>

<!-- 전환페이지 설정 -->
<script type="text/javascript" src="//wcs.naver.net/wcslog.js"></script> 
<script type="text/javascript"> 
var _nasa={};
_nasa["cnv"] = wcs.cnv("4","1"); // 전환유형, 전환가치 설정해야함. 설치매뉴얼 참고
</script> 

<div id="wrap_middle" class="" style="margin-top:140px;">
    <div id="" class="box_full">
        <div class="sub_img">
            <img src="/public_html/img/img_qanda.jpg" border="0" alt="">
        </div>
    </div>

    <div class="box_full_in_center" style="margin-top:50px; postion:relative;">
        <!--contents_info-->
        <div id="" style="width:1080px;height:879px">
            <div class="wrap_board">
                <div class="board_area">
                    <?php echo form_open_multipart('/notice/qna_store/',array('name'=>"tx_editor_form", 'id'=>"tx_editor_form")); ?>
                    <input type="hidden" id="b_code" name="b_code" value="<?php echo($b_code);?>" />
                    <input type="hidden" id="page" name="page" value="<?php echo($page);?>" />
                    <input type="hidden" name="proc_type" id="proc_type" value="NW">
                    <input type="hidden" name="b_depth" value="0">
                    <input type="hidden" name="b_parentindex" value="">
                    <input type="hidden" name="b_board_type" id="b_board_type" value="1">
                    <input type="hidden" id="b_index" name="b_index" value="<?php echo($b_index);?>">
                    <input type="hidden" name="select_img" id="select_img">
                    <div style="margin:0 0 14px;">
                        <label class="input_tit">고객명</label>
                        <input type="text" attr="1" name="b_writer" id="b_writer"  class="input_txt" style="width:200px;margin-right:206px;" value=""/>
                        <label class="input_tit">비밀번호</label>
                        <input type="password" attr="1" name="b_password" id="b_password" class="input_txt" style="width:200px;">
                    </div>
                    <div style="margin-bottom:14px;">
                        <label class="input_tit" style="margin-right:13px;" >제목</label>
                        <input type="text" attr="1" id="b_title" name="b_title" class="input_txt" style="width:365px;margin-right:50px;" placeholder="제목을 입력해주세요"  value="" />
                        <label class="input_tit">E-mail</label>
                        <input type="text" attr="1"  name="b_email1" id="b_email1"  class="input_txt" style="width:66px;"   value="" />
                        @
                        <input type="text" attr="1" id="b_email2" name="b_email2" class="input_txt" style="width:138px;" value="" />
                        <select id="s_email" attr="1" title="E-Mail 선택" class="input_sel" style="width:80px;height:26px;" onChange="if(this.value==''){with(document.tx_editor_form){b_email2.readOnly=false;b_email2.value='';b_email2.focus();}}else{with(document.tx_editor_form){b_email2.readOnly=true;b_email2.value=this.value;}}">
                            <option value="">직접입력</option>
                            <option value="gmail.com">G메일</option>
                            <option value="naver.com">네이버</option>
                            <option value="nate.com">네이트</option>
                            <option value="daum.net">다음</option>
                            <option value="hanmail.net">한메일</option>
                            <option value="empal.com" >엠팔</option>
                            <option value="hotmail.com">핫메일</option>
                            <option value="msn.com">MSN</option>
                        </select>
                    </div>
                    <div style="margin-bottom:20px;">
                        <input type="checkbox" name="b_locked" class="textbox" value="Y" <?php echo ($b_code == "QANDA0")?"checked" : ""?>>
                        <font color="blue">※ 질문글 공개를 원하시는 고객님께서는 체크를 풀어주시기 바랍니다.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;※ 답변을 확인하실때 입력하신 비밀번호로 확인이 가능합니다.</br>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color="blue">※ 사진을 첨부하신 뒤, 하단 파일첨부 영역에서 이미지 이름을 클릭하여, 메인이미지를 설정해주세요.</font>
                    </div>
                    <?php $this->load->view('editor.phtml');?>
                    <div style="height:25px;overflow:hidden;">
                            <span style="float:right;">
                                <input type="button" class="btn_gray" id="clear" value="다시작성">
                                <input type="button" class="btn_blue" onclick="saveContent()" value="등록">
                                <input type="button" class="btn_white" value="취소" onclick="javascript:history.back();">
                            </span>
                    </div>
                </div>
                </form>
            </div>
            <div style="height:200px;background:white;"></div>
        </div>
        <!--//contents_info-->
    </div>
</div>
<!-- 에디터 끝 -->
<script type="text/javascript">
    var config = {
        txHost: '', /* 런타임 시 리소스들을 로딩할 때 필요한 부분으로, 경로가 변경되면 이 부분 수정이 필요. ex) http://xxx.xxx.com */
        txPath: '', /* 런타임 시 리소스들을 로딩할 때 필요한 부분으로, 경로가 변경되면 이 부분 수정이 필요. ex) /xxx/xxx/ */
        txService: 'sample', /* 수정필요없음. */
        txProject: 'sample', /* 수정필요없음. 프로젝트가 여러개일 경우만 수정한다. */
        initializedId: "", /* 대부분의 경우에 빈문자열 */
        wrapper: "tx_trex_container", /* 에디터를 둘러싸고 있는 레이어 이름(에디터 컨테이너) */
        form: 'tx_editor_form'+"", /* 등록하기 위한 Form 이름 */
        txIconPath: "images/icon/editor/", /*에디터에 사용되는 이미지 디렉터리, 필요에 따라 수정한다. */
        txDecoPath: "images/deco/contents/", /*본문에 사용되는 이미지 디렉터리, 서비스에서 사용할 때는 완성된 컨텐츠로 배포되기 위해 절대경로로 수정한다. */
        canvas: {
            styles: {
                color: "#123456", /* 기본 글자색 */
                fontFamily: "굴림", /* 기본 글자체 */
                fontSize: "10pt", /* 기본 글자크기 */
                backgroundColor: "#fff", /*기본 배경색 */
                lineHeight: "1.5", /*기본 줄간격 */
                padding: "8px" /* 위지윅 영역의 여백 */
            },
            showGuideArea: false
        },
        events: {
            preventUnload: false
        },
        sidebar: {
            attachbox: {
                show: true,
                confirmForDeleteAll: true

            },
            attacher:{
                image: {
                    features:{left:250, top:250, width:500, height:188},
                    checksize: false
                }
            },
            capacity:{maximum: 1014572800 }
        },

        size: {
            contentWidth: 700 /* 지정된 본문영역의 넓이가 있을 경우에 설정 */
        }


    };

    EditorJSLoader.ready(function(Editor) {
        var editor = new Editor(config);
    });

</script>
<script type="text/javascript">
    /* 예제용 함수 */
    function saveContent() {
        if($('#b_index').val()){
            if($('#b_password').val() == "") {
                alert('비밀번호를 입력해 주세요.');
                b_password.focus();
                return;
            }
            $.ajax({
                type : "POST",
                url : "/ajax/board/check_pass",
                dataType: 'json',
                data: {
                    csrf_token: $('input[name=csrf_token]').val(),
                    b_index : $('#b_index').val() ,
                    pass :$('#b_password').val()
                },
                success: function(result) {
                    if(result == "fail"){
                        alert('비밀번호가 틀렸습니다.');
                        b_password.focus();
                        return;
                    }else if(result == "success"){
                        Editor.save(); // 이 함수를 호출하여 글을 등록하면 된다.
                    }

                }
            });
        }else{
            Editor.save(); // 이 함수를 호출하여 글을 등록하면 된다.
        }

    }

    function validForm(editor) {
        var validator = new Trex.Validator();
        var content = editor.getContent();


        if($('#b_writer').val() == "") {
            alert('고객명을 입력해 주세요.');
            b_writer.focus();
            return;
        }
        if($('#b_password').val() == "") {
            alert('비밀번호를 입력해 주세요.');
            b_password.focus();
            return;
        }
        if($('#b_title').val() == "") {
            alert('제목을 입력해 주세요.');
            b_title.focus();
            return;
        }
        if($('#b_email1').val() == "" || $('#b_email2').val() == "") {
            alert('이메일을 입력해 주세요.');
            b_email1.focus();
            return;
        }
        if (!validator.exists(content)) {
            alert('내용을 입력하세요');
            return false;
        }
        $('#b_board_type').val('1');
        if($('#tx_switchertoggle').attr('class') == 'tx-switchtoggle-pushed') { // html 사용안함
            $('#b_board_type').val('0');
        }

        return true;
    }

    function setForm(editor) {
        var i, input;
        var form = editor.getForm();
        var content = editor.getContent();

        var textarea = document.createElement('textarea');

        textarea.name = 'b_content';
        $(textarea).css('display','none');
        textarea.value = content;
        form.createField(textarea);
        //var images = editor.getAttachments('image');
        var images = Editor.getSidebar().getAttachments("image");
        for (i = 0; i < images.length; i++) {
            // existStage는 현재 본문에 존재하는지 여부
            // if (images[i].existStage) {
            var entry = images[i];
            if( entry.deletedMark == false ){
                // data는 팝업에서 execAttach 등을 통해 넘긴 데이터
                //alert('attachment information - image[' + i + '] \r\n' + JSON.stringify(images[i].data));
                input = document.createElement('input');
                input.type = 'hidden';
                input.name = 'attach_image[]';
                //input.value = images[i].data.filename;  // 예에서는 이미지경로만 받아서 사용
                input.value =  images[i].data.f_rename + '|' +images[i].data.filename + '|'+  images[i].data.mimeType + '|'+  images[i].data.imageWidth + '|'+  images[i].data.filesize;  // 예에서는 이미지경로만 받아서 사용
                form.createField(input);
            }
        }

        var files = editor.getAttachments('file');
        for (i = 0; i < files.length; i++) {
            input = document.createElement('input');
            input.type = 'hidden';
            input.name = 'attach_file';
            //input.value = files[i].data.attachurl;
            //input.value = files[i].data.filename;
            //  alert('attachment information - image[' + i + '] \r\n' + JSON.stringify(files[i].data));
            input.value =  files[i].data.f_rename + '|' +images[i].data.filename + '|'+  files[i].data.mimeType + '|'+  files[i].data.imageWidth + '|'+  files[i].data.filesize+ '|'+  files[i].data.attachurl ;  // 예에서는 이미지경로만 받아서 사용
            form.createField(input);
        }
        return true;
    }
</script>
<script type="text/javascript">
    <!--
    // 폼 초기화
    $('#clear').click(function(){
        if (confirm("작성하던 내용을 모두 삭제 하시겠습니까?") == true){    //확인
            $('#b_writer').val("");
            $('#b_password').val("");
            $('#b_title').val("") ;
            $('#b_email1').val("") ;
            $('#b_email2').val("");
            $('#s_email').val("");
            Editor.modify({
                "attachments": function () { /* 저장된 첨부가 있을 경우 배열로 넘김, 위의 부분을 수정하고 아래 부분은 수정없이 사용 */
                    var allattachments = [];
                    return allattachments;
                }(),
                "content": function(){
                    var temp ='<p></p>';
                    return temp;
                }()	/* 내용 문자열, 주어진 필드(textarea) 엘리먼트 */
            });
        }
        //window.location.reload();
    });

    $(function(){

        //	$('#tx_canvas_text').text(B_Contents);
        <?php if(!empty($b_index)) { ?>
        getContents();
        <?php }?>

    });

    function getContents() {

        $.ajax({
            type: "POST",
            url: "/ajax/board/get_view",
            dataType: 'json',
            data: {
                csrf_token: $('input[name=csrf_token]').val(),
                b_index : $("#b_index").val(),
                mode : 'site'
            } ,
            beforeSubmit: function (data, frm, opt) {
                console.log('데이타를 불러오는 중입니다.');
            },
            success: function(result) {
                //console.log(result);
                if(result.result == 'success') {
                    if(result.view.b_board_type == 1) {
                        if(result.view.file_cnt > 0) {
                            // 첨부 있을때
                            loadContents(result.view,result.file);
                        } else {
                            // 첨부 없을때
                            loadContents(result.view);
                        }
                    } else{
                        loadContents(result.view);
                    }
                } else {
                    // TODO 실패에 따른 처리
                    alert( result.msg);
                    history.back();
                }
            }
        });
    }


    function loadContents(reDate, files) {

        var attachments = {};
        attachments['image'] = [];
        attachments['file'] = [];

        if(typeof(reDate) != "undefined") {
            console.log(files);
            $.each(files, function(i, obj) {
                if(obj.f_index != null ) {
                    tmp_type = obj.f_type.split('/');
                    if(tmp_type[0] == "image") {
                        //console.log(obj[8]);  f_index,b_code,b_index,f_name ,f_type,f_position,f_width ,f_show ,f_size,f_rename,list_img ,file_path,reg_date
                        attachments['image'].push({
                            'attacher': 'image',
                            'data': {
                                'imageurl': obj.file_path,
                                'filename': obj.f_name,
                                'f_rename': obj.f_rename,
                                'filesize': obj.f_size,
                                'originalurl': obj.file_path,
                                'thumburl': obj.thumburl
                            }
                        });
                    } else {
                        attachments['file'].push({
                            'attacher': 'file',
                            'data': {
                                'attachurl': obj.file_path,
                                'filemime': obj.f_type,
                                'filename': obj.f_name,
                                'f_rename': obj.f_rename,
                                'filesize': obj.f_size
                            }
                        });
                    }
                }
            });
        }

        //console.log(attachments);
        $('#b_writer').val(reDate.b_writer);
        $('#b_title').val(reDate.b_title);
        var _Email = reDate.b_email.split('@');
        $('#b_email1').val(_Email[0]);
        $('#b_email2').val(_Email[1]);
        $('#proc_type').val("M");
        /* 저장된 컨텐츠를 불러오기 위한 함수 호출 */
        Editor.modify({
            "attachments": function () { /* 저장된 첨부가 있을 경우 배열로 넘김, 위의 부분을 수정하고 아래 부분은 수정없이 사용 */
                var allattachments = [];
                for (var i in attachments) {
                    allattachments = allattachments.concat(attachments[i]);
                }
                return allattachments;
            }(),
            "content": reDate.b_content	/* 내용 문자열, 주어진 필드(textarea) 엘리먼트 */
        });
    }

    //-->
    $(document).ready(function(){
        $(document).on('click',".tx-name",function(){

            alert("현재 이미지를 대표이미지로 선택합니다.");
            var index = $( ".tx-name" ).index( this );
            $("#select_img").val(index);
        });

    });
</script>