<link rel="stylesheet" type="text/css" href="/public_html/css/set_text.css" />
<link rel="stylesheet" type="text/css" href="/public_html/css/brand_style.css" />
<script type="text/javascript" src="/public_html/js/br_sliderN.js"></script>
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/newimg/company-top2.jpg" border="0" alt="">
    </div>
    <div class="bgcolor-ki border-base border-width-lr">
	    <div class="box_title" style="height:200px; padding-top:90px;">
		<div>
			brand identity
		</div>
	    </div>
	    <div class="box-identity">
		<div class="box-identity-img fl_left"><img src="/public_html/newimg/br-img01.jpg"/></div>
		<div class="box-brandtxt bgcolor-white">
			<ul>
				<li><div class="txt-m-title">Life style</div></li>
				<li><div class="txt-s-title">가정을 위한 리빙브랜드</div></li>
				<li><div class="txt-contents">헷세드는 기존의 가죽과 패브릭 소재의 단점[여름의 끈적임, 겨울의 차가움,  화학냄새, 유해 중금속 물질, 색상 선택의 한계, 비닐스러운 질감, 스크래치, 먼지 날림, 집먼지진드기 서식,  오염관리 ]과 상업적인 매장의 모순에서 벗어나, 소중한 가족과 가정을 위한 건강하고 아름다운 감동을 만듭니다.</div></li>
			</ul>
		</div>
	    </div>

	    <div class="box-identity">
		<div class="box-identity-img fl_right"><img src="/public_html/newimg/br-img02.jpg"/></div>
		<div class="box-brandtxt bgcolor-white">
			<ul>
				<li><div class="txt-m-title">touch&feel</div></li>
				<li><div class="txt-s-title">아기의 맨살처럼 부드러운 촉감</div></li>
				<li><div class="txt-contents">365일, 4계절 내내 소중한 가족과 함께 피부와 접촉하며 호흡하는 헷세드는 아기의 맨살처럼 부드러운 촉감과 여름에는 시원하고 겨울에는 따스함을 선사하는 우수한 통기성으로 쾌적하고 위생적인 로하스를 제공합니다. 또한 먼지 날림이 없으며 집먼지 진드기가 서식할 수 없는 구조로 건강하고 편안한 휴식을 공간을 만들어줍니다.</div></li>
			</ul>
		</div>
	    </div>

	    <div class="box-identity">
		<div class="box-identity-img fl_left"><img src="/public_html/newimg/br-img03.jpg"/></div>
		<div class="box-brandtxt bgcolor-white">
			<ul>
				<li><div class="txt-m-title">light</div></li>
				<li><div class="txt-s-title">밝은 채광에서 더욱 아름다운 헷세드</div></li>
				<li><div class="txt-contents">환한 빛 가운데선 미세먼지, 탁한 색감과 질감, 작은 흠집이 그대로 드러납니다. 미세 입모장으로 빛을 머금는 헷세드의 감성적인 고감도 컬러는 밝은 자연 채광에서 더욱 아름답습니다. 
	또한 헷세드는 3차원 망상구조로 먼지 날림이 없으며, 놀라운 내구성으로 오랜 시간 변함없는 아름다운을 즐길 수 있습니다.</div></li>
			</ul>
		</div>
	    </div>

	    <div class="box-identity">
		<div class="box-identity-img fl_right"><img src="/public_html/newimg/br-img05.jpg"/></div>
		<div class="box-brandtxt bgcolor-white">
			<ul>
				<li><div class="txt-m-title">premium</div></li>
				<li><div class="txt-s-title">프리미엄에 감동을 더하다</div></li>
				<li><div class="txt-contents">세계최초개발/세계최대규모/세계최고기술력으로 전세계 섬유시장을 리드하고있는 TORAY사의 오리지널 ECSAINE를 사용함으로써 오리지널의 명품적 가치를 그대로 느낄 수 있습니다. 도레이사 최고의 명성과 함께, 헷세드의 철저한 운영체제는 최고급 내장재 선택, 인체공학적 설계, 미학적인 디자인, 책임을 다하는 고객 서비스로 감동에 감동을 더하여 가정에 건강한 아름다움을 전합니다.</div></li>
			</ul>
		</div>
	    </div>

	    <div class="box-identity">
		<div class="box-identity-img fl_left"><img src="/public_html/newimg/br-img04.jpg"/></div>
		<div class="box-brandtxt bgcolor-white">
			<ul>
				<li><div class="txt-m-title">smart</div></li>
				<li><div class="txt-s-title">후가공 화학처리 없이 건강하고 편리한 관리</div></li>
				<li><div class="txt-contents">망상구조의 표면 입모 형태는 고도로 채광을 흡수하는 구조로 자연적 살균 효과를 유지함으로써 소중한 가족의 건강을 지켜줍니다. 또한 생활 속 일반 오염을 간편하게 닦을 수 있는 편리함과 오래 사용할 수 있는 내구성을 갖추어 가정의 일상 생활에서 보다 쾌적하고 편안한 휴식을 선사합니다.</div></li>
			</ul>
		</div>
	    </div>


	    <div class="box_title" style="margin-top:90px; border-width: 1px 1px 0px 0px; border-color:#333;">
		<div>
			brand story
		</div>
	    </div>
	     <div class="box_center" style="min-height:80px;">
		<div class="txt_center" style="padding:20px;">
			engineering, 工學
		</div>
		<div  class="txt-myungjoo txt_center" style="font-size:28px;">
			가장 편안하고 건강한 가정을 설계합니다
		</div>
	    </div>


	    <div class="box-identity" style="display:block; margin-top:40px;">
		<div id="" class="fl_left">
		    <img src="/public_html/img/img_brand12.jpg" border="0" alt="">
		</div>
		<div id="" class="fl_right">
		    <div id="" class="txtform01 txt_just">
			<span class="txtintitle">일상생활 패턴</span> 서양의 거실과 호텔 로비, 카페 등 입식공간에서는 일시 오가며 신발을 신고 생활합니다. 때문에 일시적 오가며 앉을 수 있는 의자형태를 추구합니다.  반면, 가정의 좌식 공간에서는 오랜 시간 편안히 앉고, 눕고, 기대며 자유로운 자세를 마음껏 취할 수 있는 소파형태를 추구합니다.
		    </div>
		    <div id="" class="txtform01 txt_just" style="margin-top:16px;">
			<span class="txtintitle">일상 피부 접촉</span> 서양의 주택 및 상업시설의 입식 공간과는 달리, 오늘날 그리고 미래의 가정은 4계절 내내 입실 하자마자 샤워 후 가벼운 옷차림으로 생활을 합니다. 따라서 소파와 침대는 장시간 피부와의 접촉이 불가피합니다. 때문에 헷세드는 전 공정에서 친환경 시스템과 엄선된 친환경 소재를 사용합니다.
		    </div>
		    <div id="" class="txtform01 txt_just" style="margin-top:16px;">
			<span class="txtintitle">헷세드 공학(工學)</span> .HASSED는 어떤 자세에서도 행복한 생활리듬과 건강한 인체 균형을 편안하게 유지하는 것을 기본으로 하며, 체형이나 각기 다른 거실 형태에 맞출 수 있는 생산체계를 갖춤으로써 누구에게나 일상생활에서의 만족을 전하는 것을 사전 전제 조건으로 설계합니다.
		    </div>
		</div>
	    </div>
	    
	<div class="box_center" style="height:80px;"></div>
	<div>
		<div class="box_center" style="min-height:140px;">
		<div class="txt_center" style="padding:20px;">
			aesthetics, 美學
		</div>
		<div  class="txt-myungjoo txt_center" style="font-size:28px;">
			가장 화목하고 행복한 가정을 디자인합니다
		</div>
	    </div>
	    <div class="box-identity">
		<div id="" class="fl_left">
		    <img src="/public_html/img/img_brand13.jpg" border="0" alt="">
		</div>
		<div id="" class="fl_right">
		    <div id="" class="txtform01 txt_just">
			<span class="txtintitle">가정의 정서</span> 순간의 각인과 구매 충동을 일으키는 상업적 음영의 멋이 아닌, 온 가족이 일상 속에서 멋진 아름다움으로 화목이 넘치는 헷세드가정의 모습을 기본 전제하에 디자인합니다. 또한 시각적인 형태와 색감, 질감은 사람의 생각과 마음, 태도까지 매우 큰 영향을 끼칩니다. 헷세드는 가정의 행복과 건강을 전할 수 있는 아름다운 정서를 기본 전제합니다.
		    </div>
		    <div id="" class="txtform01 txt_just" style="margin-top:16px;">
			<span class="txtintitle">비전과 감동</span> 오늘날의 주택은 첨단 건축기술로 고층을 지향하며 실내의 환한 전체 채광을 중요시합니다. 자연채광에서는 모든 사실이 드러나기에  헷세드는 아름다운 컬러와 섬세한 촉감을 가정에 더 큰 비전과 감동으로 전제합니다.
		    </div>
		    <div id="" class="txtform01 txt_just" style="margin-top:16px;">
			<span class="txtintitle">헷세드 미학(美學)</span> .HASSED는 가정마다 각기 다른 환경에서도 모든이가 감동하는 라이프스타일에 최적화된 디자인을 전제합니다. 또한 멋진 아름다움으로 사람 본연에 자리 잡은 소망을 충족시키는 것을 사전 전제하에 디자인 합니다.
		    </div>

		</div>
	    </div>
	</div>



    </div>
    

<div class="box_center bgcolor-ki border-base border-width-lr" style="height:80px;"></div>
