    <div id="" class="wrap_middle">
        <div class="main_img_new">
            <img src="/public_html/newimg/company-top.jpg" width="1080">
        </div>
        <div id="" class="box_color bgcolor-white">
            <div id="" class="imgtitle" style="padding-top:50px; height:150px;">
                <img src="/public_html/img/copy_com02_01.png" border="0" alt="">
            </div>
            <div id="" class="comtext01" style="text-align:center;">
                .HASSED는<br><br>
                <span class="" style="color:#94282d; font-weight:bold; margin-top:20px;">1970′ </span><br>
                세계최초개발 / 세계최대규모 / 세계최고의 원천기술로써 <br>
                전 세계 섬유시장을 리드하고 있는 TORAY 社의 Original ECSAINE를 국내 최초 도입과 동시 국내에 단독 공식 파트너 회사로서 <br>설립되었습니다. <br><br>


                <span class="" style="color:#94282d; font-weight:bold;">2010′</span>
                헷세드는 세계 섬유시장의 베스트 위치에 있는 Original ECSAINE를 통한 품격 있는 디자인과 최상의 품질로써 <br> 세계최초 소파&침대 전문 브랜드를 런칭하여
                각 가정에 멋진 아름다움과 화목, 행복과 건강을 <br>감동으로 전하는 새로운 문화를 창출하고 있습니다.  <br><br><br>
            </div>
        </div>
        <div id="" class="div1danp20 bgcolor-whitegray">
            <div id="" class="div_brand">
                <div id="" class="fl_left bgcolor-white" style="height:744px; border: 1px solid #b86f73;">
                    <img src="/public_html/img/brand_img02.jpg" border="0" alt="">
                    <div class="comtext02" style="font-size:16px; font-weight:500">
                        .HASSED는 소중한 가족들과 함께 호흡하는 건강하고 편안한 제품으로 가정의 멋진 아름다움과 화목, 행복과 건강을 바라 봅니다.<br>

                        <div id="" class="" style="margin-top:10px; font-size:15px; font-weight:400">
                            또한, 단순 매입 후 판매하는 이분법 시스템으로 운영되는 일반 유통 브랜드가 아닌, <span class="" style="font-weight:bold; display:inline-block; color:#91242a;">[연구개발 / 디자인 / 생산 / 판매 / 배송 / 서비스]</span>가 원스탑 시스템으로 자체적으로 운영되는 메이커 브랜드로서 고객님께 감동을 지속적으로 제공하는 정체성을 지녔습니다.
                        </div>
                    </div>
                </div>
                <div id="" class="fl_right bgcolor-gray" style="width:506px; height:744px;">
                    <img src="/public_html/img/brand_img03_0.jpg" border="0" alt="">
                    <div id="" class="box_since">
                        <div id="" class="bt_pluse">
                            <a href="javascript:windOPE3();"><img src="/public_html/img/bt_since.jpg" border="0" alt=""></a>
                        </div>
                        <div id="" class="box_since_txt">
                            Since its founding in 1926, Toray has kept expanding through business development in wide-range of areas. Starting from rayon filament production, Toray has developed various products such as polyester, nylon and acrylic fibers as well as high-performance films, engineering plastic resins, carbon fiber composite materials, electronics and information related products, high-performance membranes, pharmaceuticals and medical products.
                        </div>

                    </div>
                    <div id="" class="comtext03" style="margin-top:70px;">
                        <span class="" style="font-weight:bold;">TORAY에 의해 세계최초개발</span>
                        [아담과 이브 이후 최대의 혁신적 소재]로 뉴욕타임스 등 토픽으로 이슈 된 이후 소중한 가정에 최고급 시트로 사용하면서 [기존 소재의 한계점과 불편했던 단점을 해결한 꿈의 소재]로 전 세계에 센세이션을 불러일으켰습니다. 오늘날까지 세계최초개발을 이어 세계최대규모, 세계 최고기술력까지 보유함으로써 세계적 명품으로 인정받고 있습니다.
                    </div>
                </div>
            </div>
        </div>
	
        <div id="" class="div1dan" style="padding-top:90px;">
            <img src="/public_html/img/oekotex20180626.jpg" border="0" alt="">
        </div>

	<div class="txt_title">
	brand history
	</div>
	<div class="div-3dan">
		<ul>
			<li><div class="div-3dan-inbox"><span class="div-year">2010~2013</span><br>세계최초·국내유일<br>새로운 장르 출시
				<div class="history-contents">
				2005.10<br>
				Frenzen 브랜드 런칭<br>
				국내유일 세계적 명성의 TORAY社의<br>
				Original ECSAINE  독점 계약 체결<br><br>

				2010.06<br>
				.HASSED 브랜드 런칭<br>
				오늘날 새로운 거실 문화 창출 및 리딩<br><br>

				2010.11<br>
				.HASSED 서울 송파본점 오픈<br><br>

				2013.03<br>
				주식회사 헷세드 법인승계
				</div>
			</div>
			
			</li>
			<li><div class="div-3dan-inbox"><span class="div-year">2013~2015</span><br>꿈과 신비의 제품으로<br>고객님 검증
			
				<div class="history-contents">
				2013.07<br>
				.HASSED 제2공장 증설<br><br>

				2014.03<br>
				.HASSED 부산 해운대점 오픈<br><br>

				2015.06<br>
				.HASSED 중부 대전점 오픈<br><br>

				2015.09<br>
				.HASSED 롯데백화점 광복점 오픈
				</div>
			
			</div>
			
			</li>
			<li><div class="div-3dan-inbox"><span class="div-year">~2016</span><br>고객감동으로<br>동반성장
			
				<div class="history-contents">
				2016.03<br>
				.HASSED 롯데백화점 명동점/잠실점 오픈<br>
				.HASSED 롯데백화점 대전점 오픈<br><br>

				2016.06<br>
				.HASSED 롯데백화점 강남점<br><br>

				2016.08<br>
				.HASSED 대구 수성점 오픈<br>
				</div>
			
			</div></li>
		</ul>
	</div>

	<div class="div-3dan">
		<ul>
			<li><div class="div-3dan-inbox"><span class="div-year">2017</span><br><span class="div-year" style="font-size:14px;">세계최초개발 세계최대규모 세계최고기술의</span><br>베스트-프리미엄의 <br>가치창출
				<div class="history-contents">
				2017.02<br>
				.HASSED 롯데백화점 영등포점 오픈<br><br>

				2017.05<br>
				.HASSED 신세계백화점 대구점 오픈<br><br>

				2017.09<br>
				.HASSED 신세계백화점 부산센텀시티점 오픈<br><br>

				2017.09<br>
				.HASSED 세계최초 및 국내유일<br>
				오코텍스(Oeko-tex) 각 1등급 5종 획득
				</div>
			</div>
			</li>
			<li>
				<div id="" class="" style="position:relative; width:658px; height:389px; margin-top:5px; left:50px;">
				<a href="javascript:layer_open();"><img src="/public_html/img/vimeo01-20180821.jpg" border="0" alt=""></a>
				</div>
			</li>
		</ul>
	</div>


	<div class="div-3dan">
		<ul>
			<li><div class="div-3dan-inbox"><span class="div-year">2018~</span><br>헷세드 거실문화<br>부밍(BOOMing)
				<div class="history-contents">
				2018.05<br>
				.HASSED 부산 해운대점 준공 및 오픈<br><br>

				2018.08<br>
				.HASSED 현대백화점 충청점<br>
				.HASSED 현대백화점 목동점 / 대구점 오픈<br><br>

				2019.04<br>
				.HASSED 현대백화점 미아점 오픈<br><br>
				</div>
			</div>
			
			</li>
			<li>
				<div id="" class="" style="position:relative; width:658px; height:374px; margin-top:0px; left:50px;">
				<a href="javascript:layer_open2();"><img src="/public_html/img/vimeo02-20180521.jpg" border="0" alt=""></a>
				</div>
			</li>
		</ul>
	</div>

    </div>
    <div id="youtubeframe2" class="" style="display:none;">
        <a href="javascript:layer_close2();"><div id="" class="popupdivbg"></div></a>
        <div id="" class="popupdiv">
            <iframe id="player" type="text/html" width="1000" height="560" src="https://player.vimeo.com/video/215112333" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
        </div>
    </div>
    <div id="youtubeframe" class="" style="display:none;">
        <a href="javascript:layer_close();"><div id="" class="popupdivbg"></div></a>
        <div id="" class="popupdiv">
            <iframe id="player" type="text/html" width="1000" height="560" src="https://player.vimeo.com/video/286002501" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
        </div>
    </div>
</div>
<script>
    // 2. This code loads the IFrame Player API code asynchronously.
    var tag = document.createElement('script');

    tag.src = "https://www.youtube.com/iframe_api";
    var firstScriptTag = document.getElementsByTagName('script')[0];
    firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

    // 3. This function creates an <iframe> (and YouTube player)
    //    after the API code downloads.
    var player;
    function onYouTubeIframeAPIReady() {
        player = new YT.Player('player', {
            // height: '560',
            //  width: '1000',
            // videoId: 'h-emsmP-WE0',
            events: {
                'onReady': onPlayerReady,
                'onStateChange': onPlayerStateChange
            }
        });
    }

    // 4. The API will call this function when the video player is ready.
    function onPlayerReady(event) {
        //event.target.playVideo();  플레이어 자동실행 (주의: 모바일에서는 자동실행되지 않음)
    }

    // 5. The API calls this function when the player's state changes.
    //    The function indicates that when playing a video (state=1),
    //    the player should play for six seconds and then stop.
    var done = false;
    function onPlayerStateChange(event) {
        if (event.data == YT.PlayerState.PLAYING && !done) {
            //setTimeout(stopVideo, 6000);
            done = true;
        }
    }
    function stopVideo() {
        player.stopVideo();
    }
</script>

