<link rel="stylesheet" type="text/css" href="<?php echo CSS_DIR; ?>/main_20190827.css" />
<link rel="stylesheet" type="text/css" href="<?php echo CSS_DIR; ?>/new-default-hassed.css" />
<input type="hidden" name="<?=$this->security->get_csrf_token_name()?>" value="<?=$this->security->get_csrf_hash()?>"/>

<script>
	$(window).ready(function(){
		function fnMove(seq){
		var offset = $("#block-div" + seq).offset();
		var winH = $(window).height();
		$('html, body').animate({scrollTop : (offset.top - winH/2 + 250)}, 400);
		}


		$("#bt_point01").click(function(){
			fnMove(1);
		});
		$("#bt_point02").click(function(){
			fnMove(2);
		});
		$("#bt_point03").click(function(){
			fnMove(3);
		});
		$("#bt_point04").click(function(){
			fnMove(4);
		});
		$("#bt_point05").click(function(){
			fnMove(5);
		});
		$("#bt_point06").click(function(){
			fnMove(6);
		});
		$("#bt_point07").click(function(){
			fnMove(7);
		});
	});		
</script>

<div id="rh-nav">
	<div id="bt_point01" class="bt_point"><a>1</a></div>
	<div id="bt_point02" class="bt_point"><a>2</a></div>
	<div id="bt_point03" class="bt_point"><a>3</a></div>
	<div id="bt_point04" class="bt_point"><a>4</a></div>
	<div id="bt_point05" class="bt_point"><a>5</a></div>
	<div id="bt_point06" class="bt_point"><a>6</a></div>
	<div id="bt_point07" class="bt_point"><a>7</a></div>
</div>

<div class="wrap">

<div id="wrap-left">
abcd
</div>
<div id="wrap-right">
	<div id="" class="wrap_middle"> 
		<div id="block-div1"  class="box-img-frame">
			<img src="../public_html/newimg/oekotex.jpg" />
		</div>
		<div class="space-height"></div>

		<div id="block-div2" class="frame-year">
			<div class="box-year fl_left">1970</div>
			<div class="box-text01 fl_right txt_right" style="font-family: 'Times New Roman', Times, serif; font-size:34px; line-height:40px;">World's First development·Largest scale·Best technology</div>
			<div class="box-text02 fl_right txt_right">‘TORAY’社에 의하여 세상에 빛을 본<br> 오리지널 헷세드의 제품 소재는 기존 소재와 전혀 다른 새로운 장르의 ... 7000BX</div>
			<div class="box-text03 fl_left">ultrasuede는 
1970 ‘TORAY'社의 한 과학자 Miyoshi Okamoto 의하여 세계 최초 개발 되어 초기 「ECSAINE」라 불렀습니다. 당시 뉴욕 타임스 등 해외 언론에는 「아담과 이브 이후 최고의 혁식적 소재」로 토픽화 되어 이슈화가 되어 오늘 날 기존의 천(패 브릭), 동물가죽, 합성피혁(인조피혁)의 한계점을 모두 장점 화 한 꿈의 소재로써 오늘 날에는 ultrasuede로 불리며 전 세계인들이  로망하는 명품의 가치를 높여 가는 대상이 되었 습니다.
 세계최초개발·세계최대규모·세계최고기술로써 세계시장을 독보적 지위에서 리드하고 있는 ultra-suede는 고도의 과학과 기술의 조건을 지님으로써 쓰여지는 용도마다 각기  최고치의 효과를 최적의 물성으로 규격화가 되어 각기 적용하는 아이템마다 성질이 크게 다릅니다.
7000bx는 2005’ultrasuede사업부와 헷세드가 빛이 밝은 가정에 공간 에 놓여져 가족들의 피부와 인체가 직접 접촉하는 시트의 용도로써 공동개발한 아이템입니다.</div>
			<div class="box-year-img fl_right txt_right"><img src="../public_html/newimg/since-1970-img.jpg" />
			</div>
		</div>

		<div class="space-height"></div>

		<div id="block-div3" class="frame-year">
			<div class="box-year fl_left">2010</div>
			<div class="box-text01 fl_right txt_right">세계최초·세계최대·세계최고의 지위</div>
			<div class="box-text02 fl_right txt_right">best of best 지위에서 탄생된 명품의 가치는</div>
			<div class="box-text03 fl_left">TORAY에 의해 세계최초개발 [아담과 이브 이후 최대의 혁신적 소재]로 뉴욕타임스 등 토픽으로 이슈 된 이후 소중한 가정에 최고급 시트로 사용하면서 
			[기존 소재의 한계점과 불편했던 단점을 해결한 꿈의 소재]로 전 세계에 센세이션을 불러일으켰습니다. 
			오늘날까지 세계최초개발을 이어 세계최대규모, 세계 최고기술력까지 보유함으로써 세계적 명품으로 인정받고 있습니다.</div>
			<div class="box-year-img fl_right txt_right"><img src="../public_html/newimg/since-2010-img.jpg" />
			</div>
		</div>

		<div class="space-height"></div>

		<div id="block-div4" class="frame-year">
			<div class="box-year fl_left" style="font-size:90px; letter-spacing:-1px; ">TODAY</div>
			<div class="box-text01 fl_right txt_right">세계최초 [헷세드 집꾸미기] 문화</div>
			<div class="box-text021 fl_right txt_right">가정의 멋진 아름다움과 화목, 행복과 건강을 바라봅니다</div>
			<div class="box-text03 fl_left">오늘 날엔 국내에서 <br>
세계최초로 [헷세드 집꾸미기] 문화를 <br>
새로운 장르로 창출하였으며  <br>
[헷세드 집꾸미기] 문화는 감동에서 감동으로, <br>
이웃에서 이웃으로 센세이션을 불러 일으키고 있습니다. <br>
.헷세드는 온 가족들과 함께 <br>
단순 상업적 음영의 멋이 아닌 <br>
가정의 멋진 아름다움과 화목, 행복과 건강을 바라봅니다. <br>
사실, 가정은 일시적으로 오가며 즐기는 카페 / 호텔<br>
로비 / 전시장 / 백화점이 아닙니다. <br>
365일 온 가족이 늘 함께 머물며 사랑하고 비전과 <br>
꿈을 꾸는 공간입니다.<br>
</div>
			<div class="box-year-img fl_right txt_right"><img src="../public_html/newimg/since-today-img2.jpg" />
			</div>
		</div>

		<div class="space-height"></div>

		<div id="block-div5" class="frame-year">
			<div class="box-year fl_left" style="font-size:90px; letter-spacing:-1px; ">CEO</div>
			<div class="box-text01 fl_right txt_right">"소파는 거실의 얼굴입니다."</div>
			<div class="box-text021 fl_right txt_right">가정의 멋진 아름다움과 화목, 행복과 건강을 바라봅니다</div>
			<div class="box-text03 fl_left">안녕하세요!<br>
대표이사 김기욱입니다...<br><br>

헷세드를 사랑해 주시는 많은 고객님들께 진심으로 감사드립니다.<br><br>

2010년 세계최고 및 국내 유일하게<br>
Original ECSAINE 전문 메이커브랜드로써 설립된 헷세드는<br>
소중한 가족들과 함께<br>
가정의 멋진 아름다움과 화목, 행복과 건강을 바라보며<br>
감동을 만들어왔습니다.<br><br>

헷세드는 고객님과 함께<br>
감동에 감동을 이루어 갈 것을 약속합니다.<br><br>

감사합니다.<br>
<br>
</div>
			<div class="box-year-img fl_right txt_right"><img src="../public_html/newimg/photo-ceo.jpg" />
			</div>
		</div>

		<div class="space-height"></div>

		<div id="block-div6" class="frame-year">
			<img src="../public_html/newimg/shop-info.jpg" />
		</div>

		<div class="space-height"></div>

		<div id="block-div7" class="frame-year" style="height:920px;">
			<img src="../public_html/newimg/department.jpg" />
		</div>


	</div>


	<!-- <div class="main_img_new">
	<video width="1064" height="550" autoplay loop muted>
	  <source src="public_html/movie/hassed-main7.mp4" type="video/mp4"> 
	Your browser does not support the video tag.
	</video>
	<br><br><br><br><br><br><br><br><br><br><br><br>
	<br><br><br><br><br><br><br><br><br>
	</div> -->