<link rel="stylesheet" type="text/css" href="/public_html/css_e/set_text-cb<?php echo CACHE_VERSION;?>.css" />
<link rel="stylesheet" type="text/css" href="/public_html/css_e/brand_style-cb<?php echo CACHE_VERSION;?>.css" />
<script type="text/javascript" src="/public_html/js/br_sliderN-cb<?php echo CACHE_VERSION;?>.js"></script>
<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/img_e/img_brand.jpg" border="0" alt="">
    </div>
    <div class="box_center" style="margin-top:90px;">
        <img src="/public_html/img_e/title_brand01.jpg" border="0" alt="">
    </div>
    <div id="" class="slide_mask">
        <div class="brand_slideN">
            <div id="bs01" class="">
                <img src="/public_html/img_e/br_slide01.jpg" border="0" alt="">
            </div>
            <div id="bs02" class="">
                <img src="/public_html/img_e/br_slide02.jpg" border="0" alt="">
            </div>
            <div id="bs03" class="">
                <img src="/public_html/img_e/br_slide03.jpg" border="0" alt="">
            </div>
            <div id="bs04" class="">
                <img src="/public_html/img_e/br_slide04.jpg" border="0" alt="">
            </div>
            <div id="bs05" class="">
                <img src="/public_html/img_e/br_slide05.jpg" border="0" alt="">
            </div>

        </div>
        <div id="" class="brand_slide_mask">
            <img src="/public_html/img_e/br_slide_mask.png" border="0" alt="">
        </div>
        <div id="bt_br_left" class="brand_slide_bt_leftN">
            <a href="#1"><img src="/public_html/img_e/br_slide_bt_l.png" border="0" alt=""></a>
        </div>
        <div id="bt_br_right" class="brand_slide_bt_rightN">
            <a href="#2"><img src="/public_html/img_e/br_slide_bt_l.png" border="0" alt=""></a>
        </div>
    </div>
    <div id="" class="box_center" style="border-top:1px solid #000;">
        <img src="/public_html/img_e/title_brand04.jpg" border="0" alt="">
    </div>
    <div class="box_center" style="display:block;">
        <div id="" class="fl_left">
            <img src="/public_html/img_e/img_brand12.jpg" border="0" alt="">
        </div>
        <div id="" class="fl_right" style="position:absolute; margin-top:-30px; margin-left:570px; display:block; font-size:15px;">
            <div id="" class="txtform01 txt_just" style="line-height:23px;">
                <span class="txtintitle">Daily life pattern</span> In western living rooms, hotel lobbies and cafes, people wear shoes. Thus, we seek a form of chair that allows us to sit on and leave temporarily. On the other hand, we seek a form of sofa that allows us to sit on comfortably, lie down, lean and relax freely for a long time in the floor sitting space of the home.
            </div>
            <div id="" class="txtform01 txt_just" style="margin-top:16px; line-height:23px;">
                <span class="txtintitle">Daily skin contact</span> Unlike standing style space in the western housing and commercial facility, people in the house today and in the future live wear casual or light clothes after the shower as soon as they enter throughout four seasons. And, it is inevitable for us to make a skin contact with sofa and beds for a long time. .HASSED uses eco-friendly systems and carefully selected eco-friendly materials throughout the whole process.
            </div>
            <div id="" class="txtform01 txt_just" style="margin-top:16px; line-height:23px;">
                <span class="txtintitle">.HASSED engineering</span> .HASSED is based on keeping a happy life rhythm and healthy human balance in any posture comfortably. It is designed with the preliminary conditions for satisfaction of daily life with production system to suit body types or various living room types.
            </div>

        </div>
    </div>
    <div id="" class="box_center" style="border-top:1px solid #000; margin-top:87px;">
        <img src="/public_html/img_e/title_brand05.jpg" border="0" alt="">
    </div>
    <div class="box_center" style="height:400px;">
        <div id="" class="fl_left">
            <img src="/public_html/img_e/img_brand13.jpg" border="0" alt="">
        </div>
        <div id="" class="fl_right" style="position:absolute; margin-top:-30px; margin-left:570px; display:block; font-size:15px;">
            <div id="" class="txtform01 txt_just" style="line-height:23px;">
                <span class="txtintitle">Emotion of home</span> It is designed under the premise of a .HASSED home style that is full of harmony with the beauty of daily life, rather than the charm of the commercial attraction that causes impulse purchase and a moment of recognition. In addition, the visual form, color and texture have a great influence on human thoughts, minds and attitude. .HASSED presupposes a beautiful emotion basically in order to convey the happiness and health of the family.
            </div>
            <div id="" class="txtform01 txt_just" style="margin-top:16px; line-height:23px;">
                <span class="txtintitle">Vision and Impression</span> Today's houses seek high-rise buildings with cutting-edge architectural technology and emphasize the whole light of the room. As all facts are revealed in natural light, .HASSED presupposes beautiful color and delicate touch with greater vision and impression at home.
            </div>
            <div id="" class="txtform01 txt_just" style="margin-top:16px; line-height:23px;">
                <span class="txtintitle">Aesthetics of .HASSED</span> .HASSED presupposes a design optimized for a lifestyle that everyone is impressed with even in different environments at home. In addition, it is designed with the presupposition of satisfying the hope where people are in the center of wonderful beauty.
            </div>

        </div>
    </div>

</div>