<div id="" class="wrap_middle">
    <div class="sub_img">
        <img src="/public_html/img_e/img_about.jpg" border="0" alt="">
    </div>

    <div id="" class="box_color bgcolor-ivory">
        <div id="" class="imgtitle" style="padding-top:50px; height:150px;">
            <img src="/public_html/img_e/copy_com02_01.png" border="0" alt="">
        </div>
        <div id="" class="comtext01" style="text-align:center;">
            <span class="" style="color:#94282d; font-weight:bold; margin-top:20px;">1970′ </span><br>
            .HASSED was founded in 1970 as an exclusive official partner of TORAY that leads the global textile market with the world’s first development, the world’s largest size and the world’s best original technology and introduced Original ECSAINE of TORAY for the first time in Korea.<br><br>


            <span class="" style="color:#94282d; font-weight:bold;">2010′</span><br>
            With the refined design and best quality through Original ECSAINE in the best position of the global textile market, .HASSED launches the world's first sofa & bed brand in 2010 creating a new culture with impressive beauty, harmony, happiness and health for the family. <br><br><br>
        </div>

    </div>


    <div id="" class="div1danp20 bgcolor-ivory">
        <div id="" class="div_brand">
            <div id="" class="fl_left bgcolor-white" style="height:784px; border: 1px solid #b86f73;">
                <img src="/public_html/img_e/brand_img02.jpg" border="0" alt="">
                <div class="comtext02" style="font-size:15px; font-weight:500">
                    .HASSED is a healthy and comfortable product that breathes with precious family members pursuing the wonderful beauty, harmony, happiness and health of the family. <br>

                    <div id="" class="" style="margin-top:10px; font-size:14px; font-weight:400">
                        It is not a general distribution brand operated by a dichotomy system with simple purchase and sale. It is a maker brand where <span class="" style="font-weight:bold; display:inline-block; color:#91242a;">[R&D / Design / Production / Sales / Shipping / Service]</span> operate as a one-stop system, which has an identity for customer impression beyond customer satisfaction.
                    </div>
                </div>
            </div>
            <div id="" class="fl_right bgcolor-gray" style="width:506px; height:784px;">
                <img src="/public_html/img_e/brand_img03_0.jpg" border="0" alt="">
                <div id="" class="box_since">
                    <div id="" class="bt_pluse">
                        <a href="javascript:windOPE3();"><img src="/public_html/img_e/bt_since.jpg" border="0" alt=""></a>
                    </div>
                    <div id="" class="box_since_txt">
                        Since its founding in 1926, Toray has kept expanding through business development in wide-range of areas. Starting from rayon filament production, Toray has developed various products such as polyester, nylon and acrylic fibers as well as high-performance films, engineering plastic resins, carbon fiber composite materials, electronics and information related products, high-performance membranes, pharmaceuticals and medical products.
                    </div>

                </div>
                <div id="" class="comtext03" style="margin-top:70px;">
                    <span class="" style="font-weight:bold;">World’s first development by TORAY</span>
                    Since it became an issue with foreign topics such as the New York Times as [the most innovative material after Adam and Eve], it has been used as the finest sheet for the precious home causing sensation of the world with [the material of dreams that solved the limitations and disadvantages of existing materials]. It is recognized as the world-class premium product with the world’s first development, the world’s largest size and the world’s best technology.
                </div>
            </div>
        </div>
    </div>

    <div id="" class="div1dan">
        <img src="/public_html/img_e/brand_img04.jpg" border="0" alt="">
    </div>

    <div id="" class="div1dan bgcolor_history" style="margin-top:80px;">
        <!-- <div id="" class="div1dan_title">
        history
        </div> -->
        <div id="" class="" style="padding-top:20px;">
            <img src="/public_html/img_e/brandhistory.png" border="0" alt="">
        </div>
        <div id="" class="div_history">
            <ul>
                <li>
                    <div id="" class="" style="top:0px; ">
                        <h5>2010~2013</h5>
                    </div>
                    <div id="" class="" style="padding-top:14px; letter-spacing: -2px;">
                        <h1>Open a new <br>genre market</h1>
                    </div>
                    <div id="" class="" style="padding-top:40px;">
                        <h5>2005. 10</h5>
                    </div>
                    <div id="" class="" style="padding-right:20px;">
                        <h6>Frenzen brand launching <br>
                            Only company which signed an exclusive contract with the TORAY company in Korea for Original ECSAINE with world-renowned fame</h6>
                    </div>
                    <div id="" class="" style="padding-top:10px;">
                        <h5>2010. 06</h5>
                    </div>
                    <div id="" class="" style="">
                        <h6>.HASSED Launching<br>
                            Creating and leading new living room culture</h6>
                    </div>
                    <div id="" class="" style="padding-top:10px;">
                        <h5>2010. 11</h5>
                    </div>
                    <div id="" class="" style="">
                        <h6>.HASSED Seoul Songpa Shop open </h6>
                    </div>
                    <div id="" class="" style="padding-top:10px;">
                        <h5>2013. 03</h5>
                    </div>
                    <div id="" class="" style="">
                        <h6>Corporation succession of .HASSED </h6>
                    </div>
                    <br><br><br><br>
                    <div id="" class="" style="top:0px;">
                        <h5>2013~2016</h5>
                    </div>
                    <div id="" class="" style="padding-top:14px; letter-spacing: -2px;">
                        <h1>Focus on <br>home and quality</h1>
                    </div>
                    <div id="" class="" style="padding-top:40px;">
                        <h5>2013. 07</h5>
                    </div>
                    <div id="" class="" style="">
                        <h6>.HASSED the 2nd Factory extension </h6>
                    </div>
                    <div id="" class="" style="padding-top:10px;">
                        <h5>2014. 03</h5>
                    </div>
                    <div id="" class="" style="">
                        <h6>.HASSED Busan Haeundae Shop open </h6>
                    </div>
                    <div id="" class="" style="padding-top:10px;">
                        <h5>2015. 06</h5>
                    </div>
                    <div id="" class="" style="">
                        <h6>.HASSED Jungbu Daejeon Shop open </h6>
                    </div>
                    <div id="" class="" style="padding-top:10px;">
                        <h5>2015. 09</h5>
                    </div>
                    <div id="" class="" style="">
                        <h6>.HASSED Lotte Department Store <br>Gwangbok Shop open </h6>
                    </div>

                    <div id="" class="mov_history">
                        <div id="" class="div_mov01">
                            <img src="/public_html/img_e/mov_title.jpg" border="0" alt="">
                        </div>
                        <div id="" class="">
                            <a href="javascript:layer_open();"><img src="/public_html/img_e/mov_history.jpg" width="720" height="336" border="0" alt=""></a>
                        </div>
                        <div id="" class="div_mov01">
                            <img src="/public_html/img_e/mov_bottom.jpg" border="0" alt="">
                        </div>
                    </div>

                    <!-- <img src="/public_html/public_html/img_e/brand_img05.jpg" border="0" alt=""> --></li>
                <li style="padding-left:50px;">
                    <div id="" class="" style="top:0px;">
                        <h5>2016</h5>
                    </div>
                    <div id="" class="" style="padding-top:14px; letter-spacing: -2px;">
                        <h1>Growth with <br>customer <br>impression </h1>
                    </div>

                    <div id="" class="" style="padding-top:40px;">
                        <h5>2016. 03</h5>
                    </div>
                    <div id="" class="" style="">
                        <h6>.HASSED Lotte Department Store <br>Myeongdong Shop / Jamsil Shop open </h6>
                        <h6>.HASSED Lotte Department Store <br>Daejeon Shop open </h6>
                    </div>
                    <div id="" class="" style="padding-top:10px;">
                        <h5>2016. 06</h5>
                    </div>
                    <div id="" class="" style="">
                        <h6>.HASSED Lotte Department Store Gangnam Shop open </h6>
                    </div>
                    <div id="" class="" style="padding-top:10px;">
                        <h5>2016. 08</h5>
                    </div>
                    <div id="" class="" style="">
                        <h6>.HASSED Daegu Suseong Shop open </h6>
                    </div>


                    <!-- <img src="/public_html/public_html/img_e/brand_img06.jpg" border="0" alt=""> --></li>
                <li style="padding-left:70px;">
                    <div id="" class="" style="">
                        <h5>2017</h5>
                    </div>
                    <div id="" class="" style="padding-top:14px; letter-spacing: -2px;">
                        <h1>Creation of premium living room culture </h1>
                    </div>
                    <div id="" class="" style="padding-top:40px;">
                        <h5>2017. 02</h5>
                    </div>
                    <div id="" class="" style="">
                        <h6>.HASSED Lotte Department Store Yeongdeungpo Shop open </h6>
                    </div>
                    <div id="" class="" style="padding-top:10px;">
                        <h5>2017. 04</h5>
                    </div>
                    <div id="" class="" style="">
                        <h6>.HASSED Shinsegae Department Store</h6>
                    </div>
                    <div id="" class="" style="padding-top:10px;">
                        <h5>2017. 10</h5>
                    </div>
                    <div id="" class="" style="">
                        <h6>.HASSED the 3rd factory extension </h6>
                        <h6>.HASSED theme experience hall & park setting up </h6>
                    </div>
                    <!-- <img src="./img/brand_img07.jpg" border="0" alt=""> --></li>
            </ul>
        </div>
    </div>
</div>
<div id="youtubeframe" class="" style="display:none;">
    <a href="javascript:layer_close();"><div id="" class="popupdivbg"></div></a>
    <div id="" class="popupdiv">
        <iframe id="player" type="text/html" width="1000" height="560" src="https://player.vimeo.com/video/215112333" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
    </div>
</div>
<script>
    // 2. This code loads the IFrame Player API code asynchronously.
    var tag = document.createElement('script');

    tag.src = "https://www.youtube.com/iframe_api";
    var firstScriptTag = document.getElementsByTagName('script')[0];
    firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

    // 3. This function creates an <iframe> (and YouTube player)
    //    after the API code downloads.
    var player;
    function onYouTubeIframeAPIReady() {
        player = new YT.Player('player', {
            // height: '560',
            //  width: '1000',
            // videoId: 'h-emsmP-WE0',
            events: {
                'onReady': onPlayerReady,
                'onStateChange': onPlayerStateChange
            }
        });
    }

    // 4. The API will call this function when the video player is ready.
    function onPlayerReady(event) {
        //event.target.playVideo();  플레이어 자동실행 (주의: 모바일에서는 자동실행되지 않음)
    }

    // 5. The API calls this function when the player's state changes.
    //    The function indicates that when playing a video (state=1),
    //    the player should play for six seconds and then stop.
    var done = false;
    function onPlayerStateChange(event) {
        if (event.data == YT.PlayerState.PLAYING && !done) {
            //setTimeout(stopVideo, 6000);
            done = true;
        }
    }
    function stopVideo() {
        player.stopVideo();
    }
</script>