<link rel="stylesheet" type="text/css" href="/public_html/css_e/imgslider.css" />
<!-- mySlider script file -->
<script src="/public_html/js/myslider.js"></script>
<script>
    $(document).ready(function () {
        //$('.main_img_toggle1').fadeOut(10);
        $('.main_img_toggle2').fadeOut(10);
        $('.main_img_toggle3').fadeOut(10);

        setInterval(imgfade, 3000); // 매 3초마다 함수 실행

        $( '#btpoint_img01').click(function() {
            imgfade(1);
        });

        $( '#btpoint_img02').click(function() {
            imgfade(2);
        });
        $( '#btpoint_img03').click(function() {
            imgfade(3);
        });

        var sum = 0; //

        function imgfade(k){
            if(k != null){sum = k-2;}
            sum = sum + 1; // 매 4초마다 숫자 1을 sum 변수에 더합니다.
            if(sum == 0){
                $('.slider_img_toggle2').fadeOut(500);
                $('.slider_img_toggle3').fadeOut(500);
                $('.slider_img_toggle1').fadeIn(500);
                $('.point_toggle_a').css({"background-position":"0px 0px"});
            }
            else if(sum == 1){
                $('.slider_img_toggle1').fadeOut(500);
                $('.slider_img_toggle3').fadeOut(500);
                $('.slider_img_toggle2').fadeIn(500);
                $('.point_toggle_a').css({"background-position":"0px -20px"});
            }
            else if(sum == 2){
                $('.slider_img_toggle1').fadeOut(500);
                $('.slider_img_toggle2').fadeOut(500);
                $('.slider_img_toggle3').fadeIn(500);
                $('.point_toggle_a').css({"background-position":"0px -40px"});
                sum = -1;
            }
        }

        $("#bttoggleA").on({
            mousedown: function () {
                $('#bttoggleA').animate({left: '-72px' });
                $('#bttoggleB').animate({left: '0px' });
                $('.img_toggleA').animate({left: '0px' });
                $('.img_toggleB').animate({left: '690px' });
            }
        });
        $("#bttoggleB").on({
            mousedown: function () {
                $('#bttoggleA').animate({left: '0px' });
                $('#bttoggleB').animate({left: '-72px' });
                $('.img_toggleA').animate({left: '-690px' });
                $('.img_toggleB').animate({left: '0px' });
            }
        });

        $("#bttoggleC").on({
            mousedown: function () {
                $('#bttoggleC').animate({left: '-72px' });
                $('#bttoggleD').animate({left: '0px' });
                $('.img_toggleC').animate({left: '0px' });
                $('.img_toggleD').animate({left: '690px' });
            }
        });
        $("#bttoggleD").on({
            mousedown: function () {
                $('#bttoggleC').animate({left: '0px' });
                $('#bttoggleD').animate({left: '-72px' });
                $('.img_toggleC').animate({left: '-690px' });
                $('.img_toggleD').animate({left: '0px' });
            }
        });

        $("#bttoggleE").on({
            mousedown: function () {
                $('#bttoggleE').animate({left: '-72px' });
                $('#bttoggleF').animate({left: '0px' });
                $('.img_toggleE').animate({left: '0px' });
                $('.img_toggleF').animate({left: '690px' });
            }
        });
        $("#bttoggleF").on({
            mousedown: function () {
                $('#bttoggleE').animate({left: '0px' });
                $('#bttoggleF').animate({left: '-72px' });
                $('.img_toggleE').animate({left: '-690px' });
                $('.img_toggleF').animate({left: '0px' });
            }
        });

        $("#bttoggleG").on({
            mousedown: function () {
                $('#bttoggleG').animate({left: '-72px' });
                $('#bttoggleH').animate({left: '0px' });
                $('.img_toggleG').animate({left: '0px' });
                $('.img_toggleH').animate({left: '690px' });
            }
        });
        $("#bttoggleH").on({
            mousedown: function () {
                $('#bttoggleG').animate({left: '0px' });
                $('#bttoggleH').animate({left: '-72px' });
                $('.img_toggleG').animate({left: '-690px' });
                $('.img_toggleH').animate({left: '0px' });
            }
        });


        $(".bt_depart").click(function(event){
            var offset_top = 3000;
            $('html, body').animate({scrollTop: offset_top}, 500);
        });

        $(".bt_store").click(function(event){
            var offset_top = 600;
            $('html, body').animate({scrollTop: offset_top}, 500);
        });
        <?php if(!empty($type) && $type =='point_store'){ ?>
        $(".bt_store").click();
        <?php }else if(!empty($type) && $type =='point_depart'){ ?>
        $(".bt_depart").click();
        <?php } ?>

    });//ready end ////////////////


</script>
<div id="" class="wrap_middle">

    <div class="main_img">
        <div class="myslider">
            <div id='layerA' class="slider_img01"><img src="/public_html/img_e/img_store01.jpg" border="0" alt=""></div>
            <div class="slider_img02"><img src="/public_html/img_e/img_store02.jpg" border="0" alt=""></div>
            <div class="slider_img03"><img src="/public_html/img_e/img_store03.jpg" border="0" alt=""></div>
        </div>
    </div>
    <div id="bx-point">
        <a href="#a"><div id="bt_point01"><img src="/public_html/img_e/pagepoint.png" /></div></a>
        <a href="#a"><div id="bt_point02"><img src="/public_html/img_e/pagepoint.png" /></div></a>
        <a href="#a"><div id="bt_point03"><img src="/public_html/img_e/pagepoint.png" /></div></a>
    </div>

    <div id="point_store"  class="box_title3" style="padding-top:40px;">
        <img src="/public_html/img_e/title_shopinfo.png" border="0" alt="">
    </div>

    <div id="" class="box_2dept_menu">
        <div id="" class="bt_2dept_left_menu bt_store">
            <a href="#">road shop</a>
        </div>
        <div id="bt_depart" class="bt_2dept_right_menu bt_depart">
            <a href="#">department store</a>
        </div>
    </div>


    <!-- 서울 본점 -->
    <div id="" class="box_shop">
        <div id="" class="box_shop_left">
            <div id="" class="box_shop_left_div01">
                r&nbsp;o&nbsp;a&nbsp;d&nbsp; s&nbsp;h&nbsp;o&nbsp;p<br>
                Seoul Songpa Head office
            </div>
            <div id="" class="bt_mapstore">
                <div id="bttoggleA" class="toggleA">
                    <a href="#a">Shop</a>
                </div>
                <div id="bttoggleB" class="toggleB">
                    <a href="#b">Map</a>
                </div>
            </div>
            <div id="" class="box_shop_left_div02">
                <b>Opening hour</b><br>
                <div class="box_shop_left_div02_in01">
                    Mon.~ Sat.<br>
                    Sunday<br>
                    Holiday<br>
                </div>
                <div class="box_shop_left_div02_in02">
                    AM 10:00 ~ PM 08:00<br>
                    Close<br>
                    Partial open [Notice before holiday]<br>
                </div>
            </div>
            <div id="" class="box_shop_left_div03">
                <b>Shop info.</b><br>
                <div class="box_shop_left_div03_in01">
                    T&nbsp;&nbsp;E&nbsp;&nbsp;L<br>
                    Road name<br>
                    Lot no.<br>
                    Parking
                </div>
                <div class="box_shop_left_div03_in02">
                    82-2 - 401 - 5073<br>
                    271, Jungdae-ro, Songpa-gu, Seoul<br>
                    33-6, Ogeum-dong, Songpa-gu, Seoul<br>
                    Parking equipped (B/D underground)
                </div>
            </div>
        </div>
        <div id="" class="box_shop_right">
            <div id="" class="img_toggleA">
                <img src="/public_html/img_e/store01_store.jpg" border="0" alt="">
            </div>
            <div id="" class="img_toggleB">
                <img src="/public_html/img_e/store01_map.jpg" border="0" alt="">
            </div>
        </div>
    </div>


    <!-- 대전 지점 -->
    <div id="" class="box_shop">
        <div id="" class="box_shop_left">
            <div id="" class="box_shop_left_div01">
                r&nbsp;o&nbsp;a&nbsp;d&nbsp; s&nbsp;h&nbsp;o&nbsp;p<br>
                Daejeon Shop
            </div>
            <div id="" class="bt_mapstore">
                <div id="bttoggleC" class="toggleC">
                    <a href="#a">Shop</a>
                </div>
                <div id="bttoggleD" class="toggleD">
                    <a href="#b">Map</a>
                </div>
            </div>
            <div id="" class="box_shop_left_div02">
                <b>Opening hour</b><br>
                <div class="box_shop_left_div02_in01">
                    Mon.~ Sat.<br>
                    Sunday<br>
                    Holiday<br>
                </div>
                <div class="box_shop_left_div02_in02">
                    AM 10:00 ~ PM 08:00<br>
                    Close<br>
                    Partial open [Notice before holiday]<br>
                </div>
            </div>
            <div id="" class="box_shop_left_div03">
                <b>Shop info</b><br>
                <div class="box_shop_left_div03_in01">
                    T&nbsp;&nbsp;E&nbsp;&nbsp;L<br>
                    Road name<br>
                    Lot no.<br>
                    Parking
                </div>
                <div class="box_shop_left_div03_in02">
                    82-42 - 542 - 7328<br>
                    1236, Gyebaek-ro, Seo-gu, Daejeon<br>
                    396, Jeonglim-dong, Seo-gu, Daejeon<br>
                    Parking equipped (B/D yard)
                </div>
            </div>
        </div>
        <div id="" class="box_shop_right">
            <div id="" class="img_toggleC">
                <img src="/public_html/img_e/store02_store.jpg" border="0" alt="">
            </div>
            <div id="" class="img_toggleD">
                <img src="/public_html/img_e/store02_map.jpg" border="0" alt="">
            </div>
        </div>
    </div>


    <!-- 부산점 -->
    <div id="" class="box_shop">
        <div id="" class="box_shop_left">
            <div id="" class="box_shop_left_div01">
                r&nbsp;o&nbsp;a&nbsp;d&nbsp; s&nbsp;h&nbsp;o&nbsp;p<br>
                Busan Haeundae Shop
            </div>
            <div id="" class="bt_mapstore">
                <div id="bttoggleE" class="toggleA">
                    <a href="#a">Shop</a>
                </div>
                <div id="bttoggleF" class="toggleB">
                    <a href="#b">Map</a>
                </div>
            </div>
            <div id="" class="box_shop_left_div02">
                <b>Opening hour</b><br>
                <div class="box_shop_left_div02_in01">
                    Mon.~ Sat.<br>
                    Sunday<br>
                    Holiday<br>
                </div>
                <div class="box_shop_left_div02_in02">
                    AM 10:00 ~ PM 08:00<br>
                    Close<br>
                    Partial open [Notice before holiday]
                </div>
            </div>
            <div id="" class="box_shop_left_div03" style="padding-top:20px;">
                <b>Shop info</b><br>
                <div class="box_shop_left_div03_in01">
                    T&nbsp;&nbsp;E&nbsp;&nbsp;L<br>
                    Road name<br><br>
                    Lot no.<br>
                    Parking
                </div>
                <div class="box_shop_left_div03_in02" style="font-size:13px;">
                    82-51 - 743 - 5093<br>
                    458, jwadongsunhwan-ro, Haeundae-gu, Busan<br>
                    1780-1,Jung-dong,Haeundae-gu,Busan<br>
                    Parking equipped (B/D)
                </div>
            </div>
        </div>
        <div id="" class="box_shop_right">
            <div id="" class="img_toggleE">
                <img src="/public_html/img_e/store03_store-20180501.jpg" border="0" alt="">
            </div>
            <div id="" class="img_toggleF">
                <img src="/public_html/img_e/store03_map-20180501.jpg" border="0" alt="">
            </div>
        </div>
    </div>

    <!-- 대구 수성지점 -->
    <div id="" class="box_shop">
        <div id="" class="box_shop_left">
            <div id="" class="box_shop_left_div01">
                r&nbsp;o&nbsp;a&nbsp;d&nbsp; s&nbsp;h&nbsp;o&nbsp;p<br>
                Daegu Suseong Shop
            </div>
            <div id="" class="bt_mapstore">
                <div id="bttoggleG" class="toggleC">
                    <a href="#a">Shop</a>
                </div>
                <div id="bttoggleH" class="toggleD">
                    <a href="#b">Map</a>
                </div>
            </div>
            <div id="" class="box_shop_left_div02">
                <b>Opening hour</b><br>
                <div class="box_shop_left_div02_in01">
                    Mon.~ Sat.<br>
                    Sunday<br>
                    Holiday<br>
                </div>
                <div class="box_shop_left_div02_in02">
                    AM 10:00 ~ PM 08:00<br>
                    Close<br>
                    Partial open [Notice before holiday]
                </div>
            </div>
            <div id="" class="box_shop_left_div03">
                <b>Shop info</b><br>
                <div class="box_shop_left_div03_in01">
                    T&nbsp;&nbsp;E&nbsp;&nbsp;L<br>
                    Road name<br>
                    Lot no.<br>
                    Parking
                </div>
                <div class="box_shop_left_div03_in02">
                    82-53-768-5073<br>
                    49, Muhak-ro, Suseong-gu, Daegu<br>
                    413-8, Sang-dong, Suseong-gu, Daegu<br>
                    Parking equipped (B/D yard)
                </div>
            </div>
        </div>
        <div id="" class="box_shop_right">
            <div id="" class="img_toggleG">
                <img src="/public_html/img_e/store04_store.jpg" border="0" alt="">
            </div>
            <div id="" class="img_toggleH">
                <img src="/public_html/img_e/store04_map-20180501.jpg" border="0" alt="">
            </div>
        </div>
    </div>

    <div id="point_depart" class="box_space">
        <a id="bt_depart"></a>
    </div>


    <div id="" class="box_2dept_menu">
        <div id="bt_store" class="bt_2dept_left_menu bt_store">
            <a href="#">road shop</a>
        </div>
        <div id="" class="bt_2dept_right_menu bt_depart">
            <a href="#">department store</a>
        </div>
    </div>

    <!-- 신세계백화점 대구점 -->
    <div id="" class="box_shop">
        <div id="" class="box_shop_left02">
            <div id="" class="box_shop_left_div04" style="background-color:#a93a2d;">
                <span class="" style="letter-spacing: 2px;">Shinsegae department store</span><br>
                Dae-gu Shop
            </div>

            <div id="" class="box_shop_left_div05">
                <b>Opening hour </b><br>
                <div class="box_shop_left_div05_in01">
                    Normal<br>
                    Extension<br>
                    Holiday<br>
                </div>
                <div class="box_shop_left_div05_in02">
                    AM 10:30 ~ PM 08:30<br>
                    AM 10:30 ~ PM 08:30<br>
                    Comply with closing schedule of Department Store.<br>
                </div>
            </div>
            <div id="" class="box_shop_left_div06">
                <b>Shop info</b><br>
                <div class="box_shop_left_div06_in01">
                    T&nbsp;&nbsp;E&nbsp;&nbsp;L<br><br>
                    Road name<br>
                </div>
                <div class="box_shop_left_div06_in02">
                    82-53 - 661- 6948<br>
                    82-53 - 768 - 5073<br>
                    Daegu Dong-gu Dongbu-ro 149<br>
                </div>
            </div>
        </div>
        <div id="" class="box_shop_right">
            <div id="" class="">
                <img src="/public_html/img_e/store12_map.jpg" border="0" alt="">
            </div>
        </div>
    </div>


    <!-- 롯데백화점 명동점 -->
    <div id="" class="box_shop">
        <div id="" class="box_shop_left02">
            <div id="" class="box_shop_left_div04">
                <span class="" style="letter-spacing: 2px;">Lotte department store</span><br>
                Myeongdong Shop
            </div>

            <div id="" class="box_shop_left_div05">
                <b>Opening hour </b><br>
                <div class="box_shop_left_div05_in01">
                    Normal<br>
                    Extension<br>
                    Holiday<br>
                </div>
                <div class="box_shop_left_div05_in02">
                    AM 10:30 ~ PM 08:30<br>
                    AM 10:30 ~ PM 08:30<br>
                    Comply with closing schedule of Department Store<br>
                </div>
            </div>
            <div id="" class="box_shop_left_div06">
                <b>Shop info</b><br>
                <div class="box_shop_left_div06_in01">
                    T&nbsp;&nbsp;E&nbsp;&nbsp;L<br>
                    Road name<br>
                </div>
                <div class="box_shop_left_div06_in02">
                    82-2-772-3849<br>
                    8F, 81, Namdaemun-ro, Jung-gu, Seoul<br>
                </div>
            </div>
        </div>
        <div id="" class="box_shop_right">
            <div id="" class="">
                <img src="/public_html/img_e/store05_map.jpg" border="0" alt="">
            </div>
        </div>
    </div>


    <!-- 롯데백화점 잠실점 -->
    <div id="" class="box_shop">
        <div id="" class="box_shop_left02">
            <div id="" class="box_shop_left_div04">
                <span class="" style="letter-spacing: 2px;">Lotte department store</span><br>
                Jamsil Shop
            </div>

            <div id="" class="box_shop_left_div05">
                <b>Opening hour </b><br>
                <div class="box_shop_left_div05_in01">
                    Normal<br>
                    Extension<br>
                    Holiday<br>
                </div>
                <div class="box_shop_left_div05_in02">
                    AM 10:30 ~ PM 08:30<br>
                    AM 10:30 ~ PM 08:30<br>
                    Comply with closing schedule of Department Store<br>
                </div>
            </div>
            <div id="" class="box_shop_left_div06">
                <b>Shop info</b><br>
                <div class="box_shop_left_div06_in01">
                    T&nbsp;&nbsp;E&nbsp;&nbsp;L<br>
                    Road name<br>
                </div>
                <div class="box_shop_left_div06_in02">
                    82-2-2143-1896<br>
                    10F, 240, Olympic-ro, Songpa-gu, Seoul<br>
                </div>
            </div>
        </div>
        <div id="" class="box_shop_right">
            <div id="" class="">
                <img src="/public_html/img_e/store11_map.jpg" border="0" alt="">
            </div>
        </div>
    </div>


    <!-- 롯데백화점 강남점 -->
    <div id="" class="box_shop">
        <div id="" class="box_shop_left02">
            <div id="" class="box_shop_left_div04">
                <span class="" style="letter-spacing: 2px;">Lotte department store</span><br>
                Gangnam Shop
            </div>

            <div id="" class="box_shop_left_div05">
                <b>Opening hour </b><br>
                <div class="box_shop_left_div05_in01">
                    Normal<br>
                    Extension<br>
                    Holiday<br>
                </div>
                <div class="box_shop_left_div05_in02">
                    AM 10:30 ~ PM 08:30<br>
                    AM 10:30 ~ PM 08:30<br>
                    Comply with closing schedule of Department Store<br>
                </div>
            </div>
            <div id="" class="box_shop_left_div06">
                <b>Shop info</b><br>
                <div class="box_shop_left_div06_in01">
                    T&nbsp;&nbsp;E&nbsp;&nbsp;L<br>
                    Road name<br>
                </div>
                <div class="box_shop_left_div06_in02">
                    82-2-531-2813<br>
                    8F, 401, Dogok-ro, Gangnam-gu, Seoul<br>
                </div>
            </div>
        </div>
        <div id="" class="box_shop_right">
            <div id="" class="">
                <img src="/public_html/img_e/store07_map.jpg" border="0" alt="">
            </div>
        </div>
    </div>

    <!-- 롯데백화점 영등포점
    <div id="" class="box_shop">
        <div id="" class="box_shop_left02">
            <div id="" class="box_shop_left_div04">
                <span class="" style="letter-spacing: 2px;">Lotte department store</span><br>
                Yeongdeungpo Shop
            </div>

            <div id="" class="box_shop_left_div05">
                <b>Opening hour </b><br>
                <div class="box_shop_left_div05_in01">
                    Normal<br>
                    Extension<br>
                    Holiday<br>
                </div>
                <div class="box_shop_left_div05_in02">
                    AM 10:30 ~ PM 08:30<br>
                    AM 10:30 ~ PM 08:30<br>
                    Comply with closing schedule of Department Store<br>
                </div>
            </div>
            <div id="" class="box_shop_left_div06">
                <b>Shop info</b><br>
                <div class="box_shop_left_div06_in01">
                    T&nbsp;&nbsp;E&nbsp;&nbsp;L<br>
                    Road name<br>
                </div>
                <div class="box_shop_left_div06_in02">
                    82-2-2630-6966<br>
                    9F, 846, Gyeongin-ro, Yeongdeungpo-gu, Seoul<br>
                </div>
            </div>
        </div>
        <div id="" class="box_shop_right">
            <div id="" class="">
                <img src="/public_html/img_e/store10_map.jpg" border="0" alt="">
            </div>
        </div>
    </div> -->

    <!-- 롯데백화점 대전점 -->
    <div id="" class="box_shop">
        <div id="" class="box_shop_left02">
            <div id="" class="box_shop_left_div04">
                <span class="" style="letter-spacing: 2px;">Lotte department store</span><br>
                Daejeon Shop
            </div>

            <div id="" class="box_shop_left_div05">
                <b>Opening hour </b><br>
                <div class="box_shop_left_div05_in01">
                    Normal<br>
                    Extension<br>
                    Holiday<br>
                </div>
                <div class="box_shop_left_div05_in02">
                    AM 10:30 ~ PM 08:30<br>
                    AM 10:30 ~ PM 08:30<br>
                    Comply with closing schedule of Department Store<br>
                </div>
            </div>
            <div id="" class="box_shop_left_div06">
                <b>Shop info</b><br>
                <div class="box_shop_left_div06_in01">
                    T&nbsp;&nbsp;E&nbsp;&nbsp;L<br>
                    Road name<br>
                </div>
                <div class="box_shop_left_div06_in02">
                    82-42-601-2034<br>
                    B1, 598, Gyeryong-ro, Seo-gu, Daejeon<br>
                </div>
            </div>
        </div>
        <div id="" class="box_shop_right">
            <div id="" class="">
                <img src="/public_html/img_e/store08_map.jpg" border="0" alt="">
            </div>
        </div>
    </div>



    <!-- 롯데백화점 광복점 -->
    <div id="" class="box_shop">
        <div id="" class="box_shop_left02">
            <div id="" class="box_shop_left_div04">
                <span class="" style="letter-spacing: 2px;">Lotte department store</span><br>
                Gwangbok Shop
            </div>

            <div id="" class="box_shop_left_div05">
                <b>Opening hour </b><br>
                <div class="box_shop_left_div05_in01">
                    Normal<br>
                    Extension<br>
                    Holiday<br>
                </div>
                <div class="box_shop_left_div05_in02">
                    AM 10:30 ~ PM 08:30<br>
                    AM 10:30 ~ PM 08:30<br>
                    Comply with closing schedule of Department Store<br>
                </div>
            </div>
            <div id="" class="box_shop_left_div06">
                <b>Shop info</b><br>
                <div class="box_shop_left_div06_in01">
                    T&nbsp;&nbsp;E&nbsp;&nbsp;L<br>
                    Road name<br>
                </div>
                <div class="box_shop_left_div06_in02">
                    82-51-678-3020<br>
                    9F, 20-1, Jungang-dong 7-ga, Jung-gu, Busan<br>
                </div>
            </div>
        </div>
        <div id="" class="box_shop_right">
            <div id="" class="">
                <img src="/public_html/img_e/store09_map.jpg" border="0" alt="">
            </div>
        </div>
    </div>


</div>