<!-- mySlider css file -->
<link rel="stylesheet" type="text/css" href="/public_html/css/imgslider-cb<?php echo CACHE_VERSION;?>.css" />
<!-- mySlider script file -->
<script src="/public_html/js/myslider-cb<?php echo CACHE_VERSION;?>.js"></script>
<script>
    $(document).ready(function () {
       


//imageslideA // 

			var mapA = 1; // 
			
			setInterval(imgslideA, 3200); // 매 3.2초마다 함수 실행

			function imgslideA(j){
				if(j != null){ mapA = j;}
				mapA = mapA * -1; // 매 4초마다 toggle
					if(mapA < 0){ 
						$('#bttoggleA').animate({left: '-72px' });
						$('#bttoggleB').animate({left: '0px' });
						$('.img_toggleA').animate({left: '0px' });
						$('.img_toggleB').animate({left: '690px' });
					}
					else if(mapA > 0){
						$('#bttoggleA').animate({left: '0px' });
						$('#bttoggleB').animate({left: '-72px' });
						$('.img_toggleA').animate({left: '-690px' });
						$('.img_toggleB').animate({left: '0px' });
					}
					else if(mapA == 0){

					}
			}

			$("#mapstoreA").mouseover(function(event){
				if(mapA != 0){
					imgslideA(0);
				}
			});
			$("#mapstoreA").mouseout(function(event){
					mapA = 1;
					imgslideA();
			});

//imageslideB // 
			var mapB = -1; // 

			setInterval(imgslideB, 3200); // 매 4초마다 함수 실행

			function imgslideB(j){
				if(j != null){ mapB = j;}
				mapB = mapB * -1; // 매 4초마다 toggle
					if(mapB < 0){ 
						$('#bttoggleC').animate({left: '-72px' });
						$('#bttoggleD').animate({left: '0px' });
						$('.img_toggleC').animate({left: '0px' });
						$('.img_toggleD').animate({left: '690px' });
					}
					else if(mapB > 0){
						$('#bttoggleC').animate({left: '0px' });
						$('#bttoggleD').animate({left: '-72px' });
						$('.img_toggleC').animate({left: '-690px' });
						$('.img_toggleD').animate({left: '0px' });
					}
					else if(mapB == 0){

					}
			}

			$("#mapstoreB").mouseover(function(event){
				if(mapB != 0){
					imgslideB(0);
					//var offset_top = $(document).scrollTop();
					//$('html, body').animate({scrollTop: offset_top}, 500);
				}
			});
			$("#mapstoreB").mouseout(function(event){
					mapB = 1;
					imgslideB();
					//var offset_top = $(document).scrollTop();
					//$('html, body').animate({scrollTop: offset_top}, 500);
			});


//imageslideC // 
			var mapC = 1; // 

			setInterval(imgslideC, 3200); // 매 4초마다 함수 실행

			function imgslideC(j){
				if(j != null){ mapC = j;}
				mapC = mapC * -1; // 매 4초마다 toggle
					if(mapC < 0){ 
						$('#bttoggleE').animate({left: '-72px' });
						$('#bttoggleF').animate({left: '0px' });
						$('.img_toggleE').animate({left: '0px' });
						$('.img_toggleF').animate({left: '690px' });
					}
					else if(mapC > 0){
						$('#bttoggleE').animate({left: '0px' });
						$('#bttoggleF').animate({left: '-72px' });
						$('.img_toggleE').animate({left: '-690px' });
						$('.img_toggleF').animate({left: '0px' });
					}
					else if(mapC == 0){

					}
			}

			$("#mapstoreC").mouseover(function(event){
				if(mapC != 0){
					imgslideC(0);
					//var offset_top = $(document).scrollTop();
					//$('html, body').animate({scrollTop: offset_top}, 500);
				}
			});
			$("#mapstoreC").mouseout(function(event){
					mapC = 1;
					imgslideC();
					//var offset_top = $(document).scrollTop();
					//$('html, body').animate({scrollTop: offset_top}, 500);
			});

//imageslideD //
			var mapD = -1; // 
			setInterval(imgslideD, 3200); // 매 4초마다 함수 실행

			function imgslideD(j){
				if(j != null){ mapD = j;}
				mapD = mapD * -1; // 매 4초마다 toggle
					if(mapD < 0){ 
						$('#bttoggleG').animate({left: '-72px' });
						$('#bttoggleH').animate({left: '0px' });
						$('.img_toggleG').animate({left: '0px' });
						$('.img_toggleH').animate({left: '690px' });
					}
					else if(mapD > 0){
						$('#bttoggleG').animate({left: '0px' });
						$('#bttoggleH').animate({left: '-72px' });
						$('.img_toggleG').animate({left: '-690px' });
						$('.img_toggleH').animate({left: '0px' });
					}
					else if(mapD == 0){

					}
			}

			$("#mapstoreD").mouseover(function(event){
				if(mapD != 0){
					imgslideD(0);
					//var offset_top = $(document).scrollTop();
					//$('html, body').animate({scrollTop: offset_top}, 500);
				}
			});
			$("#mapstoreD").mouseout(function(event){
					mapD = -1;
					imgslideD();
					//var offset_top = $(document).scrollTop();
					//$('html, body').animate({scrollTop: offset_top}, 500);
			});


//imageslideD1 //
			var mapD1 = 1; // 
			setInterval(imgslideD1, 3200); // 매 4초마다 함수 실행

			function imgslideD1(j){
				if(j != null){ mapD1 = j;}
				mapD1 = mapD1 * -1; // 매 4초마다 toggle
					if(mapD1 < 0){ 
						$('#departA1').animate({left: '-72px' });
						$('#departA2').animate({left: '0px' });
						$('.img_departA1').animate({left: '0px' });
						$('.img_departA2').animate({left: '690px' });
					}
					else if(mapD1 > 0){
						$('#departA1').animate({left: '0px' });
						$('#departA2').animate({left: '-72px' });
						$('.img_departA1').animate({left: '-690px' });
						$('.img_departA2').animate({left: '0px' });
					}
					else if(mapD1 == 0){

					}
			}

			$("#mapstoreD1").mouseover(function(event){
				if(mapD1 != 0){
					imgslideD1(0);
					//var offset_top = $(document).scrollTop();
					//$('html, body').animate({scrollTop: offset_top}, 500);
				}
			});
			$("#mapstoreD1").mouseout(function(event){
					mapD1 = 1;
					imgslideD1();
					//var offset_top = $(document).scrollTop();
					//$('html, body').animate({scrollTop: offset_top}, 500);
			});

//imageslideD2 //
			var mapD2 = -1; // 
			setInterval(imgslideD2, 3200); // 매 4초마다 함수 실행

			function imgslideD2(j){
				if(j != null){ mapD2 = j;}
				mapD2 = mapD2 * -1; // 매 4초마다 toggle
					if(mapD2 < 0){ 
						$('#departA3').animate({left: '-72px' });
						$('#departA4').animate({left: '0px' });
						$('.img_departA3').animate({left: '0px' });
						$('.img_departA4').animate({left: '690px' });
					}
					else if(mapD2 > 0){
						$('#departA3').animate({left: '0px' });
						$('#departA4').animate({left: '-72px' });
						$('.img_departA3').animate({left: '-690px' });
						$('.img_departA4').animate({left: '0px' });
					}
					else if(mapD2 == 0){

					}
			}

			$("#mapstoreD2").mouseover(function(event){
				if(mapD2 != 0){
					imgslideD2(0);
					//var offset_top = $(document).scrollTop();
					//$('html, body').animate({scrollTop: offset_top}, 500);
				}
			});
			$("#mapstoreD2").mouseout(function(event){
					mapD2 = -1;
					imgslideD2();
					var offset_top = $(document).scrollTop();
					$('html, body').animate({scrollTop: offset_top}, 500);
			});



//imageslideD3 //
			var mapD3 = 1; // 
			setInterval(imgslideD3, 3200); // 매 4초마다 함수 실행

			function imgslideD3(j){
				if(j != null){ mapD3 = j;}
				mapD3 = mapD3 * -1; // 매 4초마다 toggle
					if(mapD3 < 0){ 
						$('#departA5').animate({left: '-72px' });
						$('#departA6').animate({left: '0px' });
						$('.img_departA5').animate({left: '0px' });
						$('.img_departA6').animate({left: '690px' });
					}
					else if(mapD3 > 0){
						$('#departA5').animate({left: '0px' });
						$('#departA6').animate({left: '-72px' });
						$('.img_departA5').animate({left: '-690px' });
						$('.img_departA6').animate({left: '0px' });
					}
					else if(mapD3 == 0){

					}
			}

			$("#mapstoreD3").mouseover(function(event){
				if(mapD3 != 0){
					imgslideD3(0);
					//var offset_top = $(document).scrollTop();
					//$('html, body').animate({scrollTop: offset_top}, 500);
				}
			});
			$("#mapstoreD3").mouseout(function(event){
					mapD3 = 1;
					imgslideD3();
					//var offset_top = $(document).scrollTop();
					//$('html, body').animate({scrollTop: offset_top}, 500);
			});


//imageslideD4 //
			var mapD4 = -1; // 
			setInterval(imgslideD4, 3200); // 매 4초마다 함수 실행

			function imgslideD4(j){
				if(j != null){ mapD4 = j;}
				mapD4 = mapD4 * -1; // 매 4초마다 toggle
					if(mapD4 < 0){ 
						$('#departA7').animate({left: '-72px' });
						$('#departA8').animate({left: '0px' });
						$('.img_departA7').animate({left: '0px' });
						$('.img_departA8').animate({left: '690px' });
					}
					else if(mapD4 > 0){
						$('#departA7').animate({left: '0px' });
						$('#departA8').animate({left: '-72px' });
						$('.img_departA7').animate({left: '-690px' });
						$('.img_departA8').animate({left: '0px' });
					}
					else if(mapD4 == 0){

					}
			}

			$("#mapstoreD4").mouseover(function(event){
				if(mapD4 != 0){
					imgslideD4(0);
					//var offset_top = $(document).scrollTop();
					//$('html, body').animate({scrollTop: offset_top}, 500);
				}
			});
			$("#mapstoreD4").mouseout(function(event){
					mapD4 = -1;
					imgslideD4();
					//var offset_top = $(document).scrollTop();
					//$('html, body').animate({scrollTop: offset_top}, 500);
			});


//imageslideD5 //
			var mapD5 = 1; // 
			setInterval(imgslideD5, 3200); // 매 4초마다 함수 실행

			function imgslideD5(j){
				if(j != null){ mapD5 = j;}
				mapD5 = mapD5 * -1; // 매 4초마다 toggle
					if(mapD5 < 0){ 
						$('#departA9').animate({left: '-72px' });
						$('#departA10').animate({left: '0px' });
						$('.img_departA9').animate({left: '0px' });
						$('.img_departA10').animate({left: '690px' });
					}
					else if(mapD5 > 0){
						$('#departA9').animate({left: '0px' });
						$('#departA10').animate({left: '-72px' });
						$('.img_departA9').animate({left: '-690px' });
						$('.img_departA10').animate({left: '0px' });
					}
					else if(mapD5 == 0){

					}
			}

			$("#mapstoreD5").mouseover(function(event){
				if(mapD5 != 0){
					imgslideD5(0);
					//var offset_top = $(document).scrollTop();
					//$('html, body').animate({scrollTop: offset_top}, 500);
				}
			});
			$("#mapstoreD5").mouseout(function(event){
					mapD5 = 1;
					imgslideD5();
					//var offset_top = $(document).scrollTop();
					//$('html, body').animate({scrollTop: offset_top}, 500);
			});

//imageslideD6 //
			var mapD6 = -1; // 
			setInterval(imgslideD6, 3200); // 매 4초마다 함수 실행

			function imgslideD6(j){
				if(j != null){ mapD6 = j;}
				mapD6 = mapD6 * -1; // 매 4초마다 toggle
					if(mapD6 < 0){ 
						$('#departA11').animate({left: '-72px' });
						$('#departA12').animate({left: '0px' });
						$('.img_departA11').animate({left: '0px' });
						$('.img_departA12').animate({left: '690px' });
					}
					else if(mapD6 > 0){
						$('#departA11').animate({left: '0px' });
						$('#departA12').animate({left: '-72px' });
						$('.img_departA11').animate({left: '-690px' });
						$('.img_departA12').animate({left: '0px' });
					}
					else if(mapD6 == 0){

					}
			}

			$("#mapstoreD6").mouseover(function(event){
				if(mapD6 != 0){
					imgslideD6(0);
					//var offset_top = $(document).scrollTop();
					//$('html, body').animate({scrollTop: offset_top}, 500);
				}
			});
			$("#mapstoreD6").mouseout(function(event){
					mapD6 = -1;
					imgslideD6();
					//var offset_top = $(document).scrollTop();
					//$('html, body').animate({scrollTop: offset_top}, 500);
			});

//imageslideD7 //
			var mapD7 = 1; // 
			setInterval(imgslideD7, 3200); // 매 4초마다 함수 실행

			function imgslideD7(j){
				if(j != null){ mapD7 = j;}
				mapD7 = mapD7 * -1; // 매 4초마다 toggle
					if(mapD7 < 0){ 
						$('#departA13').animate({left: '-72px' });
						$('#departA14').animate({left: '0px' });
						$('.img_departA13').animate({left: '0px' });
						$('.img_departA14').animate({left: '690px' });
					}
					else if(mapD7 > 0){
						$('#departA13').animate({left: '0px' });
						$('#departA14').animate({left: '-72px' });
						$('.img_departA13').animate({left: '-690px' });
						$('.img_departA14').animate({left: '0px' });
					}
					else if(mapD7 == 0){

					}
			}

			$("#mapstoreD7").mouseover(function(event){
				if(mapD7 != 0){
					imgslideD7(0);
					//var offset_top = $(document).scrollTop();
					//$('html, body').animate({scrollTop: offset_top}, 500);
				}
			});
			$("#mapstoreD7").mouseout(function(event){
					mapD7 = 1;
					imgslideD7();
					//var offset_top = $(document).scrollTop();
					//$('html, body').animate({scrollTop: offset_top}, 500);
			});


//imageslideD8 현대 충청//
			var mapD8 = 1; // 
			setInterval(imgslideD8, 3200); // 매 4초마다 함수 실행

			function imgslideD8(j){
				if(j != null){ mapD8 = j;}
				mapD8 = mapD8 * -1; // 매 4초마다 toggle
					if(mapD8 < 0){ 
						$('#departA15').animate({left: '-72px' });
						$('#departA16').animate({left: '0px' });
						$('.img_departA15').animate({left: '0px' });
						$('.img_departA16').animate({left: '690px' });
					}
					else if(mapD8 > 0){
						$('#departA15').animate({left: '0px' });
						$('#departA16').animate({left: '-72px' });
						$('.img_departA15').animate({left: '-690px' });
						$('.img_departA16').animate({left: '0px' });
					}
					else if(mapD8 == 0){

					}
			}

			$("#mapstoreD8").mouseover(function(event){
				if(mapD8 != 0){
					imgslideD8(0);
					//var offset_top = $(document).scrollTop();
					//$('html, body').animate({scrollTop: offset_top}, 500);
				}
			});
			$("#mapstoreD8").mouseout(function(event){
					mapD8 = 1;
					imgslideD8();
					//var offset_top = $(document).scrollTop();
					//$('html, body').animate({scrollTop: offset_top}, 500);
			});


//imageslideD9 현대 목동//
			var mapD9 = -1; // 
			setInterval(imgslideD9, 3200); // 매 4초마다 함수 실행

			function imgslideD9(j){
				if(j != null){ mapD9 = j;}
				mapD9 = mapD9 * -1; // 매 4초마다 toggle
					if(mapD9 < 0){ 
						$('#departA17').animate({left: '-72px' });
						$('#departA18').animate({left: '0px' });
						$('.img_departA17').animate({left: '0px' });
						$('.img_departA18').animate({left: '690px' });
					}
					else if(mapD9 > 0){
						$('#departA17').animate({left: '0px' });
						$('#departA18').animate({left: '-72px' });
						$('.img_departA17').animate({left: '-690px' });
						$('.img_departA18').animate({left: '0px' });
					}
					else if(mapD9 == 0){

					}
			}

			$("#mapstoreD9").mouseover(function(event){
				if(mapD9 != 0){
					imgslideD9(0);
					//var offset_top = $(document).scrollTop();
					//$('html, body').animate({scrollTop: offset_top}, 500);
				}
			});
			$("#mapstoreD9").mouseout(function(event){
					mapD9 = 1;
					imgslideD9();
					//var offset_top = $(document).scrollTop();
					//$('html, body').animate({scrollTop: offset_top}, 500);
			});

//imageslideD10 //
			var mapD10 = 1; // 
			setInterval(imgslideD10, 3200); // 매 4초마다 함수 실행

			function imgslideD10(j){
				if(j != null){ mapD10 = j;}
				mapD10 = mapD10 * -1; // 매 4초마다 toggle
					if(mapD10 < 0){ 
						$('#departA19').animate({left: '-72px' });
						$('#departA20').animate({left: '0px' });
						$('.img_departA19').animate({left: '0px' });
						$('.img_departA20').animate({left: '690px' });
					}
					else if(mapD10 > 0){
						$('#departA19').animate({left: '0px' });
						$('#departA20').animate({left: '-72px' });
						$('.img_departA19').animate({left: '-690px' });
						$('.img_departA20').animate({left: '0px' });
					}
					else if(mapD10 == 0){

					}
			}

			$("#mapstoreD10").mouseover(function(event){
				if(mapD10 != 0){
					imgslideD10(0);
					//var offset_top = $(document).scrollTop();
					//$('html, body').animate({scrollTop: offset_top}, 500);
				}
			});
			$("#mapstoreD10").mouseout(function(event){
					mapD10 = 1;
					imgslideD10();
					//var offset_top = $(document).scrollTop();
					//$('html, body').animate({scrollTop: offset_top}, 500);
			});



//imageslideD11 //
			var mapD11 = 1; // 
			setInterval(imgslideD11, 3200); // 매 4초마다 함수 실행

			function imgslideD11(j){
				if(j != null){ mapD11 = j;}
				mapD11 = mapD11 * -1; // 매 4초마다 toggle
					if(mapD11 < 0){ 
						$('#departA21').animate({left: '-72px' });
						$('#departA22').animate({left: '0px' });
						$('.img_departA21').animate({left: '0px' });
						$('.img_departA22').animate({left: '690px' });
					}
					else if(mapD11 > 0){
						$('#departA21').animate({left: '0px' });
						$('#departA22').animate({left: '-72px' });
						$('.img_departA21').animate({left: '-690px' });
						$('.img_departA22').animate({left: '0px' });
					}
					else if(mapD11 == 0){

					}
			}

			$("#mapstoreD11").mouseover(function(event){
				if(mapD11 != 0){
					imgslideD11(0);
					//var offset_top = $(document).scrollTop();
					//$('html, body').animate({scrollTop: offset_top}, 500);
				}
			});
			$("#mapstoreD11").mouseout(function(event){
					mapD11 = 1;
					imgslideD11();
					//var offset_top = $(document).scrollTop();
					//$('html, body').animate({scrollTop: offset_top}, 500);
			});


//imageslideD12 롯데상인 //
			var mapD12 = -1; // 
			setInterval(imgslideD12, 3200); // 매 4초마다 함수 실행

			function imgslideD12(j){
				if(j != null){ mapD12 = j;}
				mapD12 = mapD12 * -1; // 매 4초마다 toggle
					if(mapD12 < 0){ 
						$('#departA23').animate({left: '-72px' });
						$('#departA24').animate({left: '0px' });
						$('.img_departA23').animate({left: '0px' });
						$('.img_departA24').animate({left: '690px' });
					}
					else if(mapD12 > 0){
						$('#departA23').animate({left: '0px' });
						$('#departA24').animate({left: '-72px' });
						$('.img_departA23').animate({left: '-690px' });
						$('.img_departA24').animate({left: '0px' });
					}
					else if(mapD12 == 0){

					}
			}

			$("#mapstoreD12").mouseover(function(event){
				if(mapD12 != 0){
					imgslideD12(0);
					//var offset_top = $(document).scrollTop();
					//$('html, body').animate({scrollTop: offset_top}, 500);
				}
			});
			$("#mapstoreD12").mouseout(function(event){
					mapD12 = 1;
					imgslideD12();
					//var offset_top = $(document).scrollTop();
					//$('html, body').animate({scrollTop: offset_top}, 500);
			});


//////////////////////

        $("#bttoggleA").on({
            mousedown: function () {
                $('#bttoggleA').animate({left: '-72px' });
                $('#bttoggleB').animate({left: '0px' });
                $('.img_toggleA').animate({left: '0px' });
                $('.img_toggleB').animate({left: '690px' });
            }
        });
        $("#bttoggleB").on({
            mousedown: function () {
                $('#bttoggleA').animate({left: '0px' });
                $('#bttoggleB').animate({left: '-72px' });
                $('.img_toggleA').animate({left: '-690px' });
                $('.img_toggleB').animate({left: '0px' });
            }
        });

        $("#bttoggleC").on({
            mousedown: function () {
                $('#bttoggleC').animate({left: '-72px' });
                $('#bttoggleD').animate({left: '0px' });
                $('.img_toggleC').animate({left: '0px' });
                $('.img_toggleD').animate({left: '690px' });
            }
        });
        $("#bttoggleD").on({
            mousedown: function () {
                $('#bttoggleC').animate({left: '0px' });
                $('#bttoggleD').animate({left: '-72px' });
                $('.img_toggleC').animate({left: '-690px' });
                $('.img_toggleD').animate({left: '0px' });
            }
        });

        $("#bttoggleE").on({
            mousedown: function () {
                $('#bttoggleE').animate({left: '-72px' });
                $('#bttoggleF').animate({left: '0px' });
                $('.img_toggleE').animate({left: '0px' });
                $('.img_toggleF').animate({left: '690px' });
            }
        });
        $("#bttoggleF").on({
            mousedown: function () {
                $('#bttoggleE').animate({left: '0px' });
                $('#bttoggleF').animate({left: '-72px' });
                $('.img_toggleE').animate({left: '-690px' });
                $('.img_toggleF').animate({left: '0px' });
            }
        });

        $("#bttoggleG").on({
            mousedown: function () {
                $('#bttoggleG').animate({left: '-72px' });
                $('#bttoggleH').animate({left: '0px' });
                $('.img_toggleG').animate({left: '0px' });
                $('.img_toggleH').animate({left: '690px' });
            }
        });
        $("#bttoggleH").on({
            mousedown: function () {
                $('#bttoggleG').animate({left: '0px' });
                $('#bttoggleH').animate({left: '-72px' });
                $('.img_toggleG').animate({left: '-690px' });
                $('.img_toggleH').animate({left: '0px' });
            }
        });


			$("#departA1").on({
               mousedown: function () {
				$('#departA1').animate({left: '-72px' });
				$('#departA2').animate({left: '0px' });
				$('.img_departA1').animate({left: '0px' });
				$('.img_departA2').animate({left: '690px' });
               }
			});
			$("#departA2").on({
               mousedown: function () {
				$('#departA1').animate({left: '0px' });
				$('#departA2').animate({left: '-72px' });
				$('.img_departA1').animate({left: '-690px' });
				$('.img_departA2').animate({left: '0px' });
               }
			});

			$("#departA3").on({
               mousedown: function () {
				$('#departA3').animate({left: '-72px' });
				$('#departA4').animate({left: '0px' });
				$('.img_departA3').animate({left: '0px' });
				$('.img_departA4').animate({left: '690px' });
               }
			});
			$("#departA4").on({
               mousedown: function () {
				$('#departA3').animate({left: '0px' });
				$('#departA4').animate({left: '-72px' });
				$('.img_departA3').animate({left: '-690px' });
				$('.img_departA4').animate({left: '0px' });
               }
			});

			$("#departA5").on({
               mousedown: function () {
				$('#departA5').animate({left: '-72px' });
				$('#departA6').animate({left: '0px' });
				$('.img_departA5').animate({left: '0px' });
				$('.img_departA6').animate({left: '690px' });
               }
			});
			$("departA6").on({
               mousedown: function () {
				$('#departA5').animate({left: '0px' });
				$('#departA6').animate({left: '-72px' });
				$('.img_departA5').animate({left: '-690px' });
				$('.img_departA6').animate({left: '0px' });
               }
			});

			$("#departA7").on({
               mousedown: function () {
				$('#departA7').animate({left: '-72px' });
				$('#departA8').animate({left: '0px' });
				$('.img_departA7').animate({left: '0px' });
				$('.img_departA8').animate({left: '690px' });
               }
			});
			$("departA8").on({
               mousedown: function () {
				$('#departA7').animate({left: '0px' });
				$('#departA8').animate({left: '-72px' });
				$('.img_departA7').animate({left: '-690px' });
				$('.img_departA8').animate({left: '0px' });
               }
			});

			$("#departA9").on({
               mousedown: function () {
				$('#departA9').animate({left: '-72px' });
				$('#departA10').animate({left: '0px' });
				$('.img_departA9').animate({left: '0px' });
				$('.img_departA10').animate({left: '690px' });
               }
			});
			$("departA10").on({
               mousedown: function () {
				$('#departA9').animate({left: '0px' });
				$('#departA10').animate({left: '-72px' });
				$('.img_departA9').animate({left: '-690px' });
				$('.img_departA10').animate({left: '0px' });
               }
			});

			$("#departA11").on({
               mousedown: function () {
				$('#departA11').animate({left: '-72px' });
				$('#departA12').animate({left: '0px' });
				$('.img_departA11').animate({left: '0px' });
				$('.img_departA12').animate({left: '690px' });
               }
			});
			$("departA12").on({
               mousedown: function () {
				$('#departA11').animate({left: '0px' });
				$('#departA12').animate({left: '-72px' });
				$('.img_departA11').animate({left: '-690px' });
				$('.img_departA12').animate({left: '0px' });
               }
			});

			$("#departA13").on({
               mousedown: function () {
				$('#departA13').animate({left: '-72px' });
				$('#departA14').animate({left: '0px' });
				$('.img_departA13').animate({left: '0px' });
				$('.img_departA14').animate({left: '690px' });
               }
			});
			$("departA14").on({
               mousedown: function () {
				$('#departA13').animate({left: '0px' });
				$('#departA14').animate({left: '-72px' });
				$('.img_departA13').animate({left: '-690px' });
				$('.img_departA14').animate({left: '0px' });
               }
			});

////////  현대백화점 /////
			$("#departA15").on({
               mousedown: function () {
				$('#departA15').animate({left: '-72px' });
				$('#departA16').animate({left: '0px' });
				$('.img_departA15').animate({left: '0px' });
				$('.img_departA16').animate({left: '690px' });
               }
			});
			$("departA16").on({
               mousedown: function () {
				$('#departA15').animate({left: '0px' });
				$('#departA16').animate({left: '-72px' });
				$('.img_departA15').animate({left: '-690px' });
				$('.img_departA16').animate({left: '0px' });
               }
			});

			$("#departA17").on({
               mousedown: function () {
				$('#departA17').animate({left: '-72px' });
				$('#departA18').animate({left: '0px' });
				$('.img_departA17').animate({left: '0px' });
				$('.img_departA18').animate({left: '690px' });
               }
			});
			$("departA18").on({
               mousedown: function () {
				$('#departA17').animate({left: '0px' });
				$('#departA18').animate({left: '-72px' });
				$('.img_departA17').animate({left: '-690px' });
				$('.img_departA18').animate({left: '0px' });
               }
			});
			$("#departA19").on({
               mousedown: function () {
				$('#departA19').animate({left: '-72px' });
				$('#departA20').animate({left: '0px' });
				$('.img_departA19').animate({left: '0px' });
				$('.img_departA20').animate({left: '690px' });
               }
			});
			$("departA20").on({
               mousedown: function () {
				$('#departA19').animate({left: '0px' });
				$('#departA20').animate({left: '-72px' });
				$('.img_departA19').animate({left: '-690px' });
				$('.img_departA20').animate({left: '0px' });
               }
			});

			$("#departA21").on({
               mousedown: function () {
				$('#departA21').animate({left: '-72px' });
				$('#departA22').animate({left: '0px' });
				$('.img_departA21').animate({left: '0px' });
				$('.img_departA22').animate({left: '690px' });
               }
			});
			$("departA22").on({
               mousedown: function () {
				$('#departA21').animate({left: '0px' });
				$('#departA22').animate({left: '-72px' });
				$('.img_departA21').animate({left: '-690px' });
				$('.img_departA22').animate({left: '0px' });
               }
			});




        $(".bt_depart").click(function(event){
            var offset_top = 3000;
            $('html, body').animate({scrollTop: offset_top}, 500);
        });

        $(".bt_store").click(function(event){
            var offset_top = 600;
            $('html, body').animate({scrollTop: offset_top}, 500);
        });

        <?php if(!empty($type) && $type =='point_store'){ ?>
            $(".bt_store").click();
        <?php }else if(!empty($type) && $type =='point_depart'){ ?>
         $(".bt_depart").click();
        <?php } ?>

    });//ready end ////////////////


</script>
<div id="" class="wrap_middle">
    <div class="main_img">
        <div class="myslider">
            <div id='layerA' class="slider_img01">
<img src="/public_html/img/img_store01.jpg" border="0" alt=""></div>
            <div class="slider_img02"><img src="/public_html/img/img_store02.jpg" border="0" alt=""></div>
        </div>
    </div>
    <div id="bx-point">
        <a href="#a"><div id="bt_point01"><img src="/public_html/img/pagepoint.png" /></div></a>
        <a href="#a"><div id="bt_point02"><img src="/public_html/img/pagepoint.png" /></div></a>
    </div>

   
    <div id="point_store"  class="box_title3_store">
        <img src="/public_html/img/flagshop.png" border="0" alt=""><br>
    </div>


<!-- 강남압구정점 -->
<div class="box_shop_A">

<img src="/public_html/img/img-gangnam.png" border="0" alt=""><br>
	<div class="box_shop_A_text">
	강남 압구정점    |    Tel 02-515-5807    |    서울시 강남구 언주로 854 헷세드B/D    |    주차 완비 (지상/지하)<br>
OPEN  AM 10:00~ PM 08:00    |    일요일 휴무
	</div>

</div>


<!-- 송파 본점 -->
<div class="box_shop_B">
	<div class="box_shop_B_left fl_left" ><img src="/public_html/img/img-songpa.png" border="0" alt=""></div>
	<div class="box_shop_B_right fl_right" >
	<div class="box_shop_B_text">
	서울 송파본점    |<br> 
Tel 02-401-5077    |<br>  
서울시 송파구 중대로 271 헷세드B/D    |<br>
주차 완비 (B1)   |<br>
OPEN  AM 10:00~ PM 08:00    |<br>
일요일 휴무   |    </div>
	</div>
</div>


<!-- 중부 대전지점 -->
<div class="box_shop_C">
	<div class="box_shop_C_left fl_left" >
		<div class="box_shop_C_text">
			|    중부 대전지점<br>
			|    Tel 042 - 542 - 7328<br>
			|    대전시 서구 계백로 1236 헷세드B/D <br>
			|    주차 완비<br>
			|    OPEN  AM 10:00~ PM 08:00<br>
			|    일요일 휴무
		</div>
	</div>
	<div class="box_shop_C_right fl_right" >
		<img src="/public_html/img/img-daejoeun.png" border="0" alt="">
	
	</div>
</div>


<!-- 인첱 송도점 -->
<div class="box_shop_B">
	<div class="box_shop_B_left fl_left" ><img src="/public_html/img/img-songdo.png" border="0" alt=""></div>
	<div class="box_shop_B_right fl_right" >
	<div class="box_shop_B_text">
	인천 송도점    |   <br> 
Tel 02-401-5077    |    <br>
인천시 연수구 송도동 10-96번지 헷세드B/D    |    <br>
주차 완비 (B1)   |    <br>
OPEN  AM 10:00~ PM 08:00    |  <br>  
일요일 휴무   |     </div>
	</div>
</div>


<!-- 중부 대전점 -->
<div class="box_shop_C">
	<div class="box_shop_C_left fl_left" >
		<div class="box_shop_C_text">
			|    대구 수성지점<br>
|    Tel 053-768-5073<br>
|    대구시 수성구 무학로 49 헷세드B/D <br>
|    주차 완비<br>
|    OPEN  AM 10:00~ PM 08:00<br>
|    일요일 휴무
		</div>
	</div>
	<div class="box_shop_C_right fl_right" >
		<img src="/public_html/img/img-daegoo.png" border="0" alt="">
	
	</div>
</div>

<!-- 부산 해운대점 -->
<div class="box_shop_B">
	<div class="box_shop_B_left fl_left" ><img src="/public_html/img/img-haundae.png" border="0" alt=""></div>
	<div class="box_shop_B_right fl_right" >
	<div class="box_shop_B_text">
부산 해운대지점    |     <br>
Tel 051 - 743 - 5093    |     <br>
부산 해운대구 좌동순환로 458 헷세드B/D    |  <br>   
주차 완비 (B1)   |     <br>
OPEN  AM 10:00~ PM 08:00    |     <br>
일요일 휴무   |    </div>
	</div>
</div>


<!-- 호남 광주점 -->
<div class="box_shop_C">
	<div class="box_shop_C_left fl_left" >
		<div class="box_shop_C_text">
|    호남 광주지점<br>
|    Tel 02 - 401 - 5073<br>
|    광주시 남구 대남대로 348 (월산동 1001-8)<br>
|    주차 완비<br>
|    OPEN  AM 10:00~ PM 08:00<br>
|    일요일 휴무
		</div>
	</div>
	<div class="box_shop_C_right fl_right" >
		<img src="/public_html/img/img-gwangjoo.png" border="0" alt="">
	
	</div>
</div>


<!-- 부산 해운대점 -->
<div class="box_shop_B">
	<div class="box_shop_B_left fl_left" ><img src="/public_html/img/img-jeju.png" border="0" alt=""></div>
	<div class="box_shop_B_right fl_right" >
	<div class="box_shop_B_text">
	 <br>
	  <br>
	   <br>
	    <br>
제주 지점    |     <br>
COMING SOON   |       </div>
	</div>
</div>


    <!-- 서울 본점 
    <div id="" class="box_shop">
        <div id="" class="box_shop_left">
            <div id="" class="box_shop_left_div01">
                r&nbsp;o&nbsp;a&nbsp;d&nbsp; s&nbsp;h&nbsp;o&nbsp;p<br>
                서울 송파본점
            </div>
            <div id="" class="bt_mapstore">
                <div id="bttoggleA" class="toggleA">
                    <a href="#a">매장</a>
                </div>
                <div id="bttoggleB" class="toggleB">
                    <a href="#b">약도</a>
                </div>
            </div>
            <div id="" class="box_shop_left_div02">
                <b>영업시간</b><br>
                <div class="box_shop_left_div02_in01">
                    월&nbsp;-&nbsp;토<br>
                    일요일<br>
                    공휴일<br>
                </div>
                <div class="box_shop_left_div02_in02">
                    AM 10:00 ~ PM 08:00<br>
                    휴무<br>
                    부분개점 [휴일 전 공지]<br>
                </div>
            </div>
            <div id="" class="box_shop_left_div03">
                <b>매장정보</b><br>
                <div class="box_shop_left_div03_in01">
                    T&nbsp;&nbsp;E&nbsp;&nbsp;L<br>
                    도로명<br>
                    지&nbsp;&nbsp;&nbsp;&nbsp;번<br>
                    주&nbsp;&nbsp;&nbsp;&nbsp;차
                </div>
                <div class="box_shop_left_div03_in02">
                    02 - 401 - 5077<br>
                    서울시 송파구 중대로 271 헷세드B/D<br>
                    서울시 송파구 오금동 33-6 헷세드B/D<br>
                    주차 완비(B/D 지하)
                </div>
            </div>
        </div>
        <a href="#A"><div id="mapstoreA" class="box_shop_right">
            <div id="" class="img_toggleA">
                <img src="/public_html/img/store01_map.jpg" border="0" alt="">
            </div>
            <div id="" class="img_toggleB">
                <img src="/public_html/img/store01_store2019.jpg" border="0" alt="">
            </div>
        </div>
    </div>
-->



</div>